### ISSUE TITLE
Override mode leads to negative eventual BG

### ISSUE THREAD

**Issue by mylma** [LoopKit/Loop#1030]
**Describe the bug**
Using override mode or toggling override on/off leads to dramatically negative eventual BG and missing active carbs. 

CASE 1
I was testing overrides and toggling them on/off. Suddenly prediction curve changed and Loop was showing -12.9 mmol/l eventual BG. At that moment there was COB 14g and IOB 1.64U. I closed and re-opened Loop, but then COB changed to 0g. Re-opened again, waited Loop to self-correct, but the incorrect prediction did not resolve. After this issue Loop thought there was no active carbs on board at all, and way too much active insulin, which led to zero temp basals. Switched to open loop for few hours to clear the issue.

_Case 1 screenshots_
![IMG_0204](https://user-images.githubusercontent.com/44064056/61750307-b4749f00-adad-11e9-9cea-54550f383866.PNG)
![IMG_0205](https://user-images.githubusercontent.com/44064056/61750308-b4749f00-adad-11e9-81f5-348f97e18247.PNG)
![IMG_0206](https://user-images.githubusercontent.com/44064056/61750309-b4749f00-adad-11e9-800e-e13449436bc1.PNG)

_Case 1 issue report_
[Loop Report 2019-07-22 20-59-00+03-00.txt](https://github.com/LoopKit/Loop/files/3424206/Loop.Report.2019-07-22.20-59-00%2B03-00.txt)

CASE 2
During override active, I discovered that eventual BG was -31,1 mmol/l. No toggling overrides on/off. At that time there was 24g active carbs. Loop did not self-resolve it's prediction after several loops. Restarted Loop app and after that it was displaying 15g active carbs. Switched to open loop for few hours to clear the issue.

_Case 2 screenshots_
![IMG_0214](https://user-images.githubusercontent.com/44064056/61751290-85136180-adb0-11e9-8237-245e2c224476.PNG)
![IMG_0215](https://user-images.githubusercontent.com/44064056/61751291-85136180-adb0-11e9-857f-ee93eea834b9.PNG)
![IMG_0216](https://user-images.githubusercontent.com/44064056/61751292-85136180-adb0-11e9-8258-6591b0aaec17.PNG)
![IMG_0217](https://user-images.githubusercontent.com/44064056/61751293-85136180-adb0-11e9-8ea0-c472fc006b24.PNG)
![IMG_0218](https://user-images.githubusercontent.com/44064056/61751294-85abf800-adb0-11e9-9a19-6a21ab18eb17.PNG)
![IMG_0221](https://user-images.githubusercontent.com/44064056/61751295-85abf800-adb0-11e9-86d6-ba7c6681f444.PNG)
![IMG_0223](https://user-images.githubusercontent.com/44064056/61751296-85abf800-adb0-11e9-8ab6-3f3f6551b86f.PNG)

_Case 2 issue report_ 
[Loop Report 2019-07-23 21-58-19+03-00.txt](https://github.com/LoopKit/Loop/files/3424251/Loop.Report.2019-07-23.21-58-19%2B03-00.txt)

**To Reproduce**
I have tried to reproduce this issue by using and/or toggling randomly overrides on/off, but it doesn't happen every time. 
1. Activate override or toggle overrides on/off.
2. At some point Loop's eventual BG shifts to negative value. Active carbs looks correct.
3. After Loop app restart all or part of active carbs is missing and carbs calculation is incorrect.
4. Negative prediction does not resolve back to normal after override is turned off. 
5. It takes several hours to clear the incorrect prediction (open looping is a safer way). During this time Loop won't recommend any bolus because of the low predicted BG.

**Expected behavior**
Using or toggling overrides on/off should not lead to a permanent negative eventual BG or loss of active carbs.

**Phone**
 - Hardware: iPhone SE
 - OS Version: iOS 12.3.1

**Loop Version**
 - Version Number: 1.10.0DEV and 1.10.0DEV-JOJO
 - Repo: Dev and Jojo

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom app

**Pump**
 - Manufacturer: Medtronic
 - Model: 722
 - Firmware version: 2.4A

**Additional context**
Using mmol/l. 1.10.0DEV shows override target line incorrectly too low in BG graph. No such issue with 1.10.0DEV-JOJO.

**Comment by mylma** [comment]
Today was the fourth time this issue happened in a few days. I turned 'activity override' on and next loop showed -50,5 mmol/l eventual BG. I turned override off, but prediction did not resolve. At this time I did not restart Loop app, but decided to follow how the prediction changes and Loop behaves.

**What is noteworthy** 

- Looks like override somehow breaks or messes up Loop's carbs absorption model. 

- She ate 1 banana (20g carbs) before I turned the override on, but afterwards Loop thinks that it was 34g (see the first screenshot).

- I needed switch to open loop, because the prediction was so off. She ate her 19g slow carb supper, but Loop calculated that it was completely absorbed in 36 minutes and it was 40g carbs. It must be completely wrong. There wasn't so fast and big rise that it would match the calculation.

I haven't found any other safe way to clear this issue than open loop for few hours. I also need to calculate meal boluses by myself, because Loop won't recommend anything because of the low eventual BG.

**Issue report 40 mins after using the override**
[Loop Report 2019-07-25 20-07-45+03-00.txt](https://github.com/LoopKit/Loop/files/3433264/Loop.Report.2019-07-25.20-07-45%2B03-00.txt)

**Issue report 1,5 h after supper and app restart**
[Loop Report 2019-07-25 22-07-58+03-00.txt](https://github.com/LoopKit/Loop/files/3433271/Loop.Report.2019-07-25.22-07-58%2B03-00.txt)


![IMG_0234-35](https://user-images.githubusercontent.com/44064056/61907926-2debc900-af37-11e9-877d-d42db39c19f4.PNG)

### **40 mins after using the override (red loop because of suspended pump)**

![IMG_0225](https://user-images.githubusercontent.com/44064056/61908105-9fc41280-af37-11e9-96e1-2829f8f73db5.PNG)

### **Carbohydrates screen after supper**

![IMG_0230](https://user-images.githubusercontent.com/44064056/61908241-f0d40680-af37-11e9-9ff4-0908287ccfe8.PNG)

### **Main screen after supper**

![IMG_0233](https://user-images.githubusercontent.com/44064056/61908329-195c0080-af38-11e9-9e3d-277f6607886b.PNG)

**Comment by mylma** [comment]
**What was not mentioned before. These customizations have been made to our Loop app:**

- Disable Authentication for Bolusing

- Recommended Bolus Autofill (dev)

- UI toolbar icons & app icon

**Comment by mylma** [comment]
Made a test. Set an override having only a target at 8,0 mmol/l. Nothing else changed. Look at the prediction curve. Does it look normal?

On the last screen Loop pill is showing Predicted BG 4.3–12.7 mmol/l, Eventually 5.9.

![ns01](https://user-images.githubusercontent.com/44064056/61913374-993c9780-af45-11e9-9f2a-b2c2c87dfee8.png)

![ns02](https://user-images.githubusercontent.com/44064056/61913387-9f327880-af45-11e9-9438-ea2935e8c38a.png)

![ns03](https://user-images.githubusercontent.com/44064056/61913392-a48fc300-af45-11e9-8652-ab609e0e279a.png)

![ns04](https://user-images.githubusercontent.com/44064056/61913400-a8234a00-af45-11e9-8d91-d9b1e8b78d50.png)

**Comment by SarahJHayes** [comment]
Same issue as described above. Significantly negative BG predictions ( -40mmol) when toggling on an override branch ( (90% of normal basal , isf, carb ratios ie 10% reduction). Carbs on board were set prior to override ( 10gm, with 2 units IOB I:C 1:5), erroneous BGs predictions occurred for 3+ hours, Had to delete app and rebuild. 

Next day similarly erroneous negative BG predictions with an override of 130% activated. No carbs on board. 0.3 units of insulin on board. Predicted BSL of -17.

**Comment by Mlbauman89** [comment]
Same issues for me as above as well. Running Loop V1.10.0DEV-JOJO.

Used an override of -70% for one hour around 630PM. At 9pm I entered 25g and gave the suggested insulin, it was at this point I noticed it predicted my BG to end up at -47. I have since opened the loop and 1.5 hours later it is predicting -24. The carbs I entered at 9pm are still in the history although it is saying I have absorbed 69g.

[Loop Report 2019-07-29 22:13:31-06:00.txt](https://github.com/LoopKit/Loop/files/3445185/Loop.Report.2019-07-29.22.13.31-06.00.txt)

**Comment by JELCRAWFORD** [comment]
Also experiencing this issue - with several occurrences over the weekend.  In several of these occurrences, BG rise was significant due to basal rate being reduced to zero due to erroneous prediction of negative future BG.   See images below. Actual BG was 14.1 with 20 cob, IOB = 1.22 and ISF at the time was 7.0. Projected bg was -16.8. Because BG was rising and temp basal was zero (reasonable if the prediction was correct to start with and -bg was a likely consequence) I did two small bolus corrections w/o insulin of .5 and .6. These corrections were well within what should have been ok based on ISF, total IOB and COB as well as current BG. We had a temp target on earlier in the evening, that was cancelled perhaps 1-2 hours before the attached images.

In searching for a solution, we turned the phone on and off, quit and restarted the app as well as Spike, with no change. Suddenly, perhaps about 1.5-2 hours after having cancelled a low temp that was put on earlier in the evening the prediction resolved to a non-negative BG.  This behaviour is somewhat unpredictable, but has been observed with remote overrides (NS initiated) as well as overrides initiated by the Looping phone.  There is no obvious action by the user that can revise the negative prediction until is runs its course.
![IMG_0004](https://user-images.githubusercontent.com/24684595/62102407-1a51a280-b256-11e9-907d-fc63fd270971.PNG)
![IMG_0005](https://user-images.githubusercontent.com/24684595/62102414-2178b080-b256-11e9-9d82-c59a26625de3.PNG)

**Comment by diggabyte** [comment]
I noticed all of these reports are in mmol/L/U. Wondering if there’s a conversion bug in there somewhere. I’ve been using overrides for months (in mg/dL) and never seen an issue like this.

**Comment by mylma** [comment]
It's true that at least these reports here are in mmol/L. I've seen couple of posts on Looped FB page which use mg/L and look similar:

https://www.facebook.com/groups/TheLoopedGroup/permalink/2278306752385978/
https://www.facebook.com/groups/TheLoopedGroup/permalink/2267027920180528/

But I'm not 100% sure if these are the same issue...


I have also noticed couple of cases where user set a pre-meal target and experienced similar very low negative prediction which did not resolve within next few loops.

https://github.com/LoopKit/Loop/issues/1006
(https://www.facebook.com/groups/TheLoopedGroup/permalink/2303539273196059/)

https://github.com/LoopKit/Loop/issues/1043
(https://www.facebook.com/groups/TheLoopedGroup/permalink/2321334061416580/)

**Comment by JELCRAWFORD** [comment]
hm..  good question. Thoughts about easiest way to go about testing that theory?

**Comment by mylma** [comment]
I have tried to reproduce this issue using Loop dev with Simulator pump and CGM but no success so far...

**Comment by Mairead101** [comment]
I've had this issue too. The pic below shows what happened when we tried to run a 10% override, but this also happens with more subtle overrides such as 130%. I don't have as much documentation or testing as mylma because my daughter is young and I'm afraid to try too many overrides now. But his post is an accurate description of our experience with Jojo overrides as well. Thank you!
![override pic 1](https://user-images.githubusercontent.com/50084497/62155469-f5e9da80-b2d6-11e9-87e1-a8e349c1b640.jpg)

**Comment by Kdisimone** [comment]
closed with fix above
