### ISSUE TITLE
Feature Request: Show calculations in bolus screen

### ISSUE THREAD

**Issue by CodeByMini** [LoopKit/Loop#1086]
I would like to see the calculations for bolus in the bolus screen

Especially for open loop situations when I would like to make my own decisions on insulin needs, a more sugar surfing approach to open loop, without having to whip out the calculator for every meal.

But also for closed loop when, for example treating a low just before a meal and waiting to be able to bolus, if I miss that small window just when it rises above bolus treshold I feel like Loop is over correcting due to the quick rise, being able to see how much is for correction would make it easier to give an amount that suits the meal and not the treatment rise

I did a quick mockup for what I would like to see
<img width="328" alt="Skärmavbild 2019-08-23 kl  10 41 47" src="https://user-images.githubusercontent.com/42831533/64120271-0ee52000-cd9c-11e9-8815-7aa32b709816.png">

**Comment by CaspianGeben** [comment]
(and Eric Jensen told me that what I call future temp basal is actually the number in "pending insulin" so loop is already presenting us with one of the numbers)

**Comment by jimsiff** [comment]
I second this suggestion.  There are edge cases such as a missed / late meal bolus where Loop isn't aware that recent BG rise is due to previously consumed carbs.  In those cases, Loop ramps up basal in response, and the suggested bolus of carbs + correction can be too much.  Having the breakdown of carbs + correction = recommended helps provide the user better context and ability to override the recommendation.

**Comment by babybluesky1** [comment]
I think you misunderstand how the recommendations are derived. Loop blends four sources of adjustments to prediction curve (carbs, insulin, BG momentum, and retrospective correction) into one curve and THEN does the dosemath.swift to get the recommendations. The data isn't available (in the way that you are thinking) to simply display. You're missing the contributions of all the pieces by thinking there are only carbs and corrections...that's not Loop's math. This is a lot more complex too. If you are getting into the weeds of trying to manage loop manually, you'd also want to see how much loop is withholding now due to a predicted low later? This is a slippery slope into the opposite direction of how Loop works and is designed...less thought and less micromanaging. Instead, you'll find that with more experience, you'll get your settings adjusted and micromanaging like this screen suggests will be unnecessary.

**Comment by Kdisimone** [comment]
I think you misunderstand how the recommendations are derived. Loop blends four sources of adjustments to prediction curve (carbs, insulin, BG momentum, and retrospective correction) into one curve and THEN does the dosemath.swift to get the recommendations. The data isn't available (in the way that you are thinking) to simply display. You're missing the contributions of all the pieces by thinking there are only carbs and corrections...that's not Loop's math. This is a lot more complex too. If you are getting into the weeds of trying to manage loop manually, you'd also want to see how much loop is withholding now due to a predicted low later? This is a slippery slope into the opposite direction of how Loop works and is designed...less thought and less micromanaging. Instead, you'll find that with more experience, you'll get your settings adjusted and micromanaging like this screen suggests will be unnecessary.

**Comment by jimsiff** [comment]
Thanks Katie.  I understand that Loop evaluates additional inputs when calculating a bolus recommendation.  My initial reply was certainly an oversimplification.  That being said, we all know the simple math of Carbs / IC = Bolus.  I guess my hope would be for the ability to break down the total bolus into Carb Bolus and other factors.  There are times when we as a parent or pwd have situational context that Loop cannot evaluate.  Having additional information at least optionally available has value.  You're right that tuning settings goes a long way towards minimizing any manual adjustments.  To that end, I've backed off max basal some to blunt Loop's response to BG momentum.  

On a related note, it would be nice to be able to set max basal as a ratio of current basal rates rather than a hard maximum.  That way we could set a variable basal profile that works, and set a max basal ratio that stays at say 3x rather than a drifting ratio depending on current basal rate.  But, I understand that may not be feasible or practical because Loop would be manipulating max basal as part of the basal schedule.

**Comment by elnjensen** [comment]
> On a related note, it would be nice to be able to set max basal as a ratio of current basal rates rather than a hard maximum. That way we could set a variable basal profile that works, and set a max basal ratio that stays at say 3x rather than a drifting ratio depending on current basal rate. But, I understand that may not be feasible or practical because Loop would be manipulating max basal as part of the basal schedule.

My worry with that approach would be that it would reduce some of the safety functionality of the max basal setting.  To me the max basal rate is a number that you look at and say, “I never, under any circumstances, would feel safe getting more basal than this.”  Then that will keep Loop in check in the event of wonky CGM data, or data mis-entry as you’re changing basal rates. A 3x multiplier on scheduled basal would be especially susceptible to entry errors for the basal rates themselves.  I think there are more guards in place now to prevent entering crazy basal rates by accident, but the range of “normal” is still wide, so could be an issue. 

Back on the original issue,  I could see the utility of breaking out carbs and pending from other factors, though I worry a bit that it would lead to more confusion rather than less, overall.

**Comment by ps2** [comment]
I would like bolusing to show the forecast, and how the forecast would change if you overrode Loop's suggestion. I think this would give users a better idea of how to override things, and what kinds of risks they're taking when doing so.

**Comment by jimsiff** [comment]
I can understand the hesitancy to use a ratio in place of a hard cap max basal.  That could definitely detract from overall safety.  A fixed hard cap along with a max basal ratio that cannot exceed the hard cap should satisfy the safety concern while adding some tuning capability for those with variable basals.

The rationale for the ratio is that my son has consistently had a bell curve basal requirement for the past few years.  During the day at school he needs less than at night.  I have lowered his max basal so it's under 3x during the day while at school.  The downside is that loop can't react as aggressively at night when sleeping and hormones kick in.

**Comment by ps2** [comment]
Max temp basal shouldn't be a treatment parameter. It's really a safety check for bad settings. Once you have your settings figured out, max basal can be raised.

**Comment by CaspianGeben** [comment]
The main reason for wanting this (or at least show the IC calculation) is when our son goes just below 3.9mmol during recess and we want to bolus for lunch, but loop is not suggesting anything due to him being low. We would like to be able to bolus for the meal and not let him wait until dexcom picks up that he's actually going up after treating the low. and this without taking out a calculator, and looking up his I:C ratio and calculation this ourself, overriding loop.

This might not be a feature that everybody likes to enable, still I think alot of user, especially coming from the omnipod pdm, would like to have.

**Comment by Kdisimone** [comment]
We have same desire (below suspend but need to bolus). We have modified Loop code to allow a lower bolus Bg. You could do same

**Comment by CaspianGeben** [comment]
In dev?

**Comment by Nightfoxy** [comment]
It would be nice to see the full bolus amount based on carb ratio. This would be useful for the situation described, for learning, and for open looping when you don't plan on actually taking open loop basal recommendations later, but just want Loop to be a dumb PDM for a while.

The lower bolus guard, once paired with the new carb absorption model, will probably take care of most of the soft bolus recommendations, but I still think it would be a good idea to see the ICR calculation.

**Comment by CaspianGeben** [comment]
Have another scenario when this could be useful:
If the pump breaks for whatever reason and you need to take shots, it would be really useful to have a built in boluscalculator in the loop app instead of, in most cases for us atleast, do stressful calculations with a calculator and our rationumbers. Of course I can do it, but its not convinient.

**Comment by marionbarker** [comment]
I believe this issue should be closed with Loop v2.2 which added prediction to the bolus screen to assist in user decision making.
