### ISSUE TITLE
Feature Request Show schedueled basal on main screen

### ISSUE THREAD

**Issue by CodeByMini** [LoopKit/Loop#1088]
In the top status part of loop, where the temp basal is showing I would like to see the scheduled basal alongside, not just the change.
We have about 8 different basals during the day due to the activity of our 6 year old and it's quite the headache to try to remember which one is active and then calculating how much of it loop is giving. This might be a problem that fades with time, but in the beginning of our looping experience it was pretty hard to calculate the numbers on the fly

With the recent implementation of overrides it would be nice to see this number to see how much a 10 % or 20% change actually is affecting the basal

**Comment by CaspianGeben** [comment]
For clarification, this is the part I'm talking about
<img width="375" alt="Skärmavbild 2019-09-02 kl  16 34 03" src="https://user-images.githubusercontent.com/42831533/64121613-a4ce7a00-cd9f-11e9-9bd6-4a68a200a00e.png">

**Comment by Kdisimone** [comment]
I think you are correct in saying this is an issue that fades with time...but also, probably more immediately helpful, is that the values you are seeking are shown directly in Nightscout. Do you have a Nightscout site setup with your Loop yet? That would be invaluable to have with your kid being a Looper.  You'll see enacted basal rate, can see scheduled basal rate, and can see the overrides info all in Nightscout.

**Comment by CaspianGeben** [comment]
We have a nightscout account. Wouldn’t want to live without it. 
Its the first two months of looping that made me really think about it and figured this was something that was missing to me.
The omnipod icon in the same place show very clearly how many days has passed and how many days is left and I feel this could be achived with basal as well. 
Are there a reason why its not showing for example 0,5 +0,10 or 0,5 -0,5?

**Comment by Kdisimone** [comment]
Simply put (in my mind) the reason is because the absolute value is unimportant in looping.  Scheduled basals (when realistically representative of what a basal should be) will keep your BGs steady...so the absolute numeric value of a scheduled basal is unimportant. The offset from scheduled basals is important....little offset, little correction. Big offset, big correction. And the little and big are drawn in that HUD icon...smaller offsets are drawn with a smaller offset from the x-axis (orange bar is smaller from 0.0 datum).

Looping should be a minimal-time-investment glance...it isn't about re-crunching hard numbers yourself...the algorithm should be doing that instead. So, Loop displays hold true to that idea as well. Glanceable data presented in easy visuals as opposed to every last bit of numeric value for every displayed info piece.

**Comment by CaspianGeben** [comment]
Perhaps this should be a future future feature request. That also uses a slider in settings that could trigger it on and off for those who want and for those who don’t. Like beeps in dev

I would have loved the option in the beginning of our looping experience and now I wouldnt mind if it where there now after 3 months
