### ISSUE TITLE
Feature Request: Add option for ISF depending on BG

### ISSUE THREAD

**Issue by benndy72** [LoopKit/Loop#1112]
A feature that allows for setting separate ISF schedules based on when BGs exceed (or fall below) a given level would be hugely helpful. I, for one, often have to increase my ISF by as much as 50% when my BG rises above 250, and factoring in that manual Bolus increase proves troublesome for the Loop algo. If Loop were able to incorporate that data it would make a notable difference in Time-In-Range.

**Comment by sleibrand** [comment]
I would advise being very careful with such a feature. I have yet to see anyone willing to do an experiment showing that high BG alone causes resistance (do variable amounts of fast carbs when flat in range, and see how big a bolus it takes to return to target). Instead, it seems that high BG is caused by resistance, more than the other way around. As such, it is better to directly measure the increased resistance, as autosens does in OpenAPS, rather than using high BG as a proxy. The risk of the latter is that you end up overcorrecting, and causing a bad hypo if the observed resistance is actually due to something else, like underestimated carbs, pooled insulin at an infusion site, or similar. We’ve already seen one adverse event with the current Loop algorithm very reasonably high temping for high BG, and then after some period of time BG dropping precipitously (perhaps due to pooling), causing a severe hypo where paramedics were called. If the algorithm were more aggressive at dosing for high BG, that severe hypo could have been worse.

**Comment by ps2** [comment]
You can use temporary overrides to adjust your sensitivity if you think you see a pattern that gives you confidence you can be more aggressive about treating.  Loop's current method for dealing with additional observed resistance is via the retrospective correction feature, that is now enabled by default in the dev branch of Loop.  It is fairly conservative, in order to be able to react quickly when ISF returns back to normal levels. 

Scott's advice about not rolling your own based on bg is good, but he misses pointing out the current tools Loop already has.  I'm not sure why he's posting here as he is not a Loop user nor a Loop developer.  Sounds like he's trying to advertise for OpenAPS, which is pretty poor form.

**Comment by scottleibrand** [comment]
My apologies for not being fully familiar with the existing tools in Loop. I don't expect anyone using Loop to switch to OpenAPS: I just want to make sure that we direct people toward safe approaches to closed looping, avoid implementing anything that could be dangerous, and make sure lessons learned on DIY systems are communicated to users and developers of all other DIY systems. I thought about mentioning IRC, but I know that didn't end up making it to prod.  I agree that tools like RC are the best way to automatically address this, and from your comments it sounds like it serves this purpose well, even without IRC.  I also agree that further adjustments should be made manually only by individuals who are familiar enough with their own diabetes, and the tools available, to be confident they can do so safely.

**Comment by ps2** [comment]
The event in question involved a user using Spike, with a calibration event dramatically increasing the scale factor of the algorithm.  This was followed by a period of high bg readings, and then a sudden drop. This kind of pattern is symptomatic of the scale factor being too large.  This is one reason we advise against using non-fda approved CGM algorithms with Loop.

**Comment by scottleibrand** [comment]
Thanks for that additional detail. I'm very much in agreement on using native CGM algorithms wherever possible. It's probably off-topic for this particular issue, but if you have any suggestions for approaches to make all DIY closed-loop software, and its documentation, clearer about how to avoid the risks of DIY CGM algorithms, I'd be happy to push for more there.

**Comment by benndy72** [comment]
Using the overrides is an interesting approach that I hadn't really thought of.  However, that would only allow a user to set a lower target range, which in some cases might conflict with the suspend thresholds if the ISF increase was significant enough.  Also, as you said, employing an override would be most useful when you can establish a pattern vs. when you have an episodic high BG due to some cause that is not easily observable or repeatable (ie. Dawn Phenomenon, Illness, etc.).  

The loop algo does a great job as is of correcting the BG back to target through the use of the temp basals, but that is often a correction that takes several hours and that can prove problematic if you're heading into a meal and want a faster correction.

I fully understand the safety considerations, but with the max basal rate and suspend thresholds in place, I think their fairly minimal and easily addressable.  Also, I'm not suggesting this feature as a required input, just as an optional override for those of us who ARE familiar enough with our diabetes and have the experience to successfully use those types of tools.  As someone who was a long time Podder before using Loop (as are many others), there's no lack of familiarity with increasing correction boluses to accommodate lower ISFs due to high BGs.

All in all, just a suggestion, not a requirement.

**Comment by th122** [comment]
> showing that high BG alone causes resistance 

There's a bit of literature in that area - a German doc (Bernhard Teupe) has been collecting and evaluating his patients logs for years, resulting in an impressive wealth of data. He ended up formulating a rather large ruleset, also addressing corrections.  (Final outcome: "Advice Device", a KB-System designed to determine therapy parameters, designed to be used by patients, and his book Die¬ Logik meines Diabetes : [Insulinpumpen-Therapiewissen; Behandlung diabetischer Fußleiden; 30Jahre Erfahrung als Handbuch] / Bernhard Teupe. - 1. Aufl.. 2011)

Basically, he's making a distinction between 3 levels of resistance:
* **A**  "normal" insulin sensitivity, free of any additional resistance 
* **B**  Lipolysis, and his ruleset would recommend to increase corrective Insulin by 50% (simplification - that corrective scheme was first designed for Patients on MDI and without CGM at hand)
* **C** Ketoacidosis, and a separate plan to deal with that.

### So how does this relate to the feature request discussed here?
From the data Teupe had at hand, he would consider a BG > 140mg/dl for a period of 4hours or more cause enough to suspect a Lipolysis-related resistance at play, and calculate in an increased need of insulin to battle the free fatty acids blocking the insulin receptors.

Now the corrective schemes suggested in his publications are based and tested on MDI dosing patients drawing their conclusions from BG readings, so they are designed to calculate the entire amount needed for correction into a single dose. (As pumps became available, the same scheme was applied to their users)

Side-note on the obvious: Loop (or OpenAPS, or AAPS) works different, and by micro-dosing, can do a lot better than the single hit-or-miss corrective dose, so I am not suggesting to "just increase insulin by 50%". Don't get me wrong on that, please :)

Back to the initial question if there's any evidence for an increasing sgv also hinting at a decreasing ISF
When messing around with BR testing and/or or ISF calculations (using different variants of the autosens algorithm in AndroidAPS), I found it useful to only correlate data gathered during "in-range" timespans. In-range I had defined as between 70 and 160, provided the 140 hadn't been crossed for more than two hours. Data gathered above that region would show a rather noticable drop in ISF, while Data below, while rare, was usually due to activity messing up the picture (and increasing ISF). 

So my 2mg/dl on this topic would be: Yes, ISF does decline with raising BG/sgv, but the fast carb tests suggested by @sleibrand would *not* run into them as long as the correction gets the PWD back into range quick enough. I don't know about Loop in particular, but with AndroidAPS the cautious dosing of SMB has the tradeoff of taking its time to get the user back into range safely (as opposed to the single correction bolus which would do the job a lot faster, but at an increased risk, especially if a sudden bout of activity should happen). To me, it seems that the algorithm at play can loose out in this race, allowing fatty acids to do their part, resulting in a lower ISF. 

I have been considering (and testing) a few ways around that myself
1.  using a "pp" profile after larger meals, lowering ISF by 30% to 50% initially (50% if fat and proteins have been playing a major role in that meal). In an ideal world, the ISF would be raised back to normal taking time passed and sgv into consideration. So far, I've had that profile limited in time, and would overrule it if necessary.
1.  modifying autosens to react faster and more decidedly to the most recent deviations, even after meals. I was less happy with this, since while basically working, it was still a tad slow to react (so the rise/fall had already taken a leap before autosens would adapt), and it had the obvious drawback of compensating for misjudged meals more than anything else. So I would not recommend to use this to lower the ISF. I have been using it successfully to detect increased ISF (at prolonged activity). especially when a timed activity profile had been running out previously.

**Comment by Kdisimone** [comment]
Closing this as it is a duplicate of this old issue https://github.com/LoopKit/Loop/issues/656 and the current tracking is best suited to here https://github.com/LoopKit/Loop/issues/431
