### ISSUE TITLE
Bolus Recorded Twice In Event History

### ISSUE THREAD

**Issue by ljcaswell** [LoopKit/Loop#1115]
**Describe the bug**
Using Dev 1.10.1, Minimed 722, Dexcom G6 it appears that boluses are being recorded twice in the Event History. My only two boluses so far using this version have done this. Deleting the entry from event history does not work, as the entry is re-added.

This is my first ever Github bug report, so if I have forgotten anything, please let me know.

FYI - I have reverted to Jojo since this is affecting my health. 

**Attach an Issue Report**
[Loop Report 2019-09-19 11:39:35-04:00.md.zip](https://github.com/LoopKit/Loop/files/3632163/Loop.Report.2019-09-19.11.39.35-04.00.md.zip)

**To Reproduce**
1. Bolus
2. View Event History and Apple Health
3. See bolus recorded twice

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: iPhone X
 - OS Version: ios 13.1 Beta 4

**Loop Version**
 - Version Number: 1.10.1
 - Repo: Dev

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom

**Pump**
 - Manufacturer: Medtronic
 - Model: 722
 - Firmware version: 2.4A 1.1 0B 0B

**Additional context**
None
![IMG_4667](https://user-images.githubusercontent.com/14313196/65262161-b8841b00-dad7-11e9-830f-8e78eadaaa07.jpeg)
![IMG_4668](https://user-images.githubusercontent.com/14313196/65262162-b8841b00-dad7-11e9-8524-5c7a7a252a3f.jpeg)
![IMG_4669](https://user-images.githubusercontent.com/14313196/65262163-b8841b00-dad7-11e9-9367-ca1c4f7ac612.jpeg)
![IMG_4671](https://user-images.githubusercontent.com/14313196/65262164-b8841b00-dad7-11e9-923c-b3ec2c97eb5c.jpeg)
![IMG_4672](https://user-images.githubusercontent.com/14313196/65262165-b8841b00-dad7-11e9-8aea-510b3e056832.jpeg)
![IMG_4673](https://user-images.githubusercontent.com/14313196/65262166-b8841b00-dad7-11e9-82cf-0c5cf749191b.jpeg)
![IMG_4674](https://user-images.githubusercontent.com/14313196/65262167-b91cb180-dad7-11e9-8fa8-88d67350e04e.jpeg)

**Comment by Kdisimone** [comment]
Line 1608 in your Issue Report only shows one bolus event being read.
Line 1916 in your Issue Report shows only one bolus event being recorded.

A pump event and a dose entry are not duplication of IOB. One is a pump event, the other is an insulin recorded into Health app. Go check your Health app's insulin data records for what Loop recorded as your insulin delivery. That is where it is storing information.

**Comment by ljcaswell** [comment]
Hi Katie. Thanks for checking. Yes, there were two bolus entries in health. Not sure why the picture didn't attach to the first post.

![IMG_4670](https://user-images.githubusercontent.com/14313196/65262999-8d9ac680-dad9-11e9-82be-6dc434073060.png)

**Comment by Kdisimone** [comment]
can you click on the 7:51pm and post the details on that?

**Comment by ljcaswell** [comment]
So sorry, but I had to stop using this branch and switch back to Jojo. I ate my normal meal this AM, bolused, and my sugar shot up from 95 to 260. The entry in health is no longer there.

**Comment by Kdisimone** [comment]
Next time when you delete a Loop app, you can answer No to the question about deleting Health data (it’s the second question when you delete the app). That way your old entries are retained 👍

**Comment by cyoung1024** [comment]
I'm also experiencing this. Loop 1.10.1-spike with personal, local repo for rileylink_ios that's up to date with remote dev but has the x15 fix. I can push it to GitHub if needed. All boluses are recorded twice regardless of amount of open versus closed loop. Using Medtronic 715 firmware 2.3A 1.1 0B0B, Dexcom G5 with Spike. [Here's my issue report.](https://github.com/LoopKit/Loop/files/3635044/Loop.Report.2019-09-20.10.51.30%2B02.00.txt) 

No matter how many times I delete the readings in Health, they come back. What I've been trying to do is delete both in Health and delete only one from Event History, but both come back in each location. If I delete both from Event History and leave only one in Health that will either solve the problem and only one will reappear in Event History or the bolus will get deleted entirely from Event History - meaning active insulin is correct but there will be no bolus triangle on the Insulin Delivery graph.

Sometimes when there are multiple instances of double bolus recordings the Insulin Delivery graph will show a sharp peak in insulin, one bar being above 50u, sometimes with and sometimes without a triangle. I'll post back later in the day if I observe this again. I'm going to try my best to not delete data and get a full report by the end of the day with all double boluses for the day recorded, but I expect I'll need to start deleting things at some point in order to bolus for meals. These two boluses are for breakfast.

[Here's the link to the Spike repo](https://github.com/cyoung1024/loop/tree/dev-spike) if that could help as well.

![Loop_homescreen](https://user-images.githubusercontent.com/42605906/65315184-f3e61e80-db97-11e9-93c9-9b0bd886f786.PNG)
![Event_History](https://user-images.githubusercontent.com/42605906/65315243-05c7c180-db98-11e9-87da-ef010b1db6ab.jpg)
![Health_entries](https://user-images.githubusercontent.com/42605906/65315290-1a0bbe80-db98-11e9-8cd7-196618277e0f.jpg)
![Bolus_1A_Loop](https://user-images.githubusercontent.com/42605906/65315319-2abc3480-db98-11e9-9c5f-a77a6bf49793.jpg)
![Bolus_1A_Health](https://user-images.githubusercontent.com/42605906/65315336-30b21580-db98-11e9-8603-13f8f427e540.jpg)
![Bolus_1B_Loop](https://user-images.githubusercontent.com/42605906/65315378-46273f80-db98-11e9-8f45-ba98b151506d.jpg)
![Bolus_1B_Health](https://user-images.githubusercontent.com/42605906/65315387-4c1d2080-db98-11e9-95dc-cc4f4840d709.jpg)
![Bolus_2A_Loop](https://user-images.githubusercontent.com/42605906/65315407-5a6b3c80-db98-11e9-900f-aca1349c632a.jpg)
![Bolus_2A_Health](https://user-images.githubusercontent.com/42605906/65315428-60f9b400-db98-11e9-9a2f-6bf2d53f0fe8.jpg)
![Bolus_2B_Loop](https://user-images.githubusercontent.com/42605906/65315468-753db100-db98-11e9-8464-1b8b25db1499.jpg)
![Bolus_2B_Health](https://user-images.githubusercontent.com/42605906/65315487-7a9afb80-db98-11e9-948d-039c484a7edf.jpg)
<img width="913" alt="Pump Bolus History" src="https://user-images.githubusercontent.com/42605906/65315561-9dc5ab00-db98-11e9-81c9-450e2d007ec8.png">

**Comment by rumil** [comment]
I can also confirm the issue. Below you can find 3 Issue reports:
1. Just after meal bolus stopped being delivered (but before "next" loop) [Loop Report 2019-09-22 14_19_39+02_00.txt](https://github.com/LoopKit/Loop/files/3639752/Loop.Report.2019-09-22.14_19_39%2B02_00.txt)
1. When bolus is recorded twice [Loop Report 2019-09-22 14_33_29+02_00.txt](https://github.com/LoopKit/Loop/files/3639753/Loop.Report.2019-09-22.14_33_29%2B02_00.txt)

The duplication is:
```
* PersistedPumpEvent(date: 2019-09-22 12:14:27 +0000, persistedDate: 2019-09-22 12:23:23 +0000, dose: Optional(LoopKit.DoseEntry(type: LoopKit.DoseType.bolus, startDate: 2019-09-22 12:14:27 +0000, endDate: 2019-09-22 12:18:39 +0000, value: 6.3, unit: LoopKit.DoseUnit.units, deliveredUnits: nil, description: nil, syncIdentifier: Optional("aed827f370c64e6c87d15586386999c3"), scheduledBasalRate: nil)), isUploaded: true, objectIDURL: x-coredata://EF32AE0C-2E4A-468A-8E0C-402284F6619E/PumpEvent/p219468, raw: Optional(16 bytes), title: Optional("BolusNormalPumpEvent(length: 9, rawData: 9 bytes, timestamp: calendar: gregorian (fixed) year: 2019 month: 9 day: 22 hour: 14 minute: 14 second: 18 isLeapMonth: false , unabsorbedInsulinRecord: nil, amount: 6.3, programmed: 6.3, unabsorbedInsulinTotal: 0.0, type: MinimedKit.BolusNormalPumpEvent.BolusType.normal, duration: 0.0, deliveryUnitsPerMinute: 1.5)"), type: Optional(LoopKit.PumpEventType.bolus), isMutable: false)
```
and
```
* PersistedPumpEvent(date: 2019-09-22 12:14:18 +0000, persistedDate: 2019-09-22 12:28:20 +0000, dose: Optional(LoopKit.DoseEntry(type: LoopKit.DoseType.bolus, startDate: 2019-09-22 12:14:18 +0000, endDate: 2019-09-22 12:14:18 +0000, value: 6.3, unit: LoopKit.DoseUnit.units, deliveredUnits: nil, description: nil, syncIdentifier: Optional("013f3f00924e2e5613"), scheduledBasalRate: nil)), isUploaded: true, objectIDURL: x-coredata://EF32AE0C-2E4A-468A-8E0C-402284F6619E/PumpEvent/p219911, raw: Optional(9 bytes), title: Optional("BolusNormalPumpEvent(length: 9, rawData: 9 bytes, timestamp: calendar: gregorian (fixed) year: 2019 month: 9 day: 22 hour: 14 minute: 14 second: 18 isLeapMonth: false , unabsorbedInsulinRecord: nil, amount: 6.3, programmed: 6.3, unabsorbedInsulinTotal: 0.0, type: MinimedKit.BolusNormalPumpEvent.BolusType.normal, duration: 0.0, deliveryUnitsPerMinute: 1.5)"), type: Optional(LoopKit.PumpEventType.bolus), isMutable: false)
```
This happens for *every* bolus. @cyoung1024 workaround works for me fine 👍

**Comment by dm61** [comment]
I can also confirm the same issue (dev 1.10.1 commit f798c8e, Minimed 523). Bolus duplications look the same as reported above. Wonder if this may be an issue only with Medtronic pumps?

**Comment by lydiaoxley** [comment]
Same issue with Lydia. We deleted duplicate entry from Health App and it was put back in next Dexcom cycle. Dev 1.10.1 MT 722
We turned Face ID off because her phone was not always recognizing her face, but that made no difference.

**Comment by dm61** [comment]
Here is some more data to hopefully help identify the problem. The duplicate bolus entries are: 
[Pump Event 1.txt](https://github.com/LoopKit/Loop/files/3640029/Pump.Event.1.txt)
[Pump Event 2.txt](https://github.com/LoopKit/Loop/files/3640030/Pump.Event.2.txt)
Interestingly, the first one has start at 17:00:03 and end at 17:00:03, probably based on the time when the bolus of 1.0 U was initiated, while the second one has start at 17:00:07 and end at 17:00:47, probably corresponding to the time captured from pump history. 

I've captured debug stream from Xcode for couple of cycles before the bolus was issued, and for several Loop cycles after the bolus:
[duplicate-bolus-debug-capture.txt](https://github.com/LoopKit/Loop/files/3640035/duplicate-bolus-debug-capture.txt)
Here is also an Issue Report captured after the duplicate bolus appeared in Loop:
[Loop Report 2019-09-22 11-11-15-06-00.txt](https://github.com/LoopKit/Loop/files/3640036/Loop.Report.2019-09-22.11-11-15-06-00.txt)

The duplicate bolus appeared some time after the second Loop cycle after the bolus was issued. An attempt to delete just from Health failed - duplicate bolus reappeared.  Deleting the duplicate bolus from both Health and Event History succeeded - duplicate bolus did not reappear.

**Comment by adamd9** [comment]
You'll also notice that the "offending" duplicate has a different syncIdentifier length too.

Standard / pre-update id has a length of 15 chars:
**syncIdentifier: Optional("1601b85c0e5513")**

Duplicate entry id has a length of 33 chars
syncIdentifier: Optional("**4dc3cf943be34b84af5eb76bcd57074c**")

Looking back at my historical data, these 33 char syncIdentifiers were not appearing.

**Comment by ps2** [comment]
The identifiers are part of the dose tracking system.  Longer identifiers are identifiers for doses that Loop is tracking that it initiated. The short identifiers should only show up for events that are either a) not doses, or b) doses that Loop did not initiate. Seeing short identifiers here is symptomatic of Loop losing track of matching up a dose it issued with the dose in the pump's event history.
