### ISSUE TITLE
Dark Mode observations?

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#1120]
Quick debugging place for Dark Mode issues on Dev?

Adding Dexcom G6 or Dexcom G5 has some grey/blacks missing

![IMG_7739](https://user-images.githubusercontent.com/12402160/65382975-f09b8180-dcc2-11e9-91f7-26b5aa7edcf1.PNG)

**Comment by panctronic** [comment]
Expiration Reminder also has a white background:

![IMG_1633](https://user-images.githubusercontent.com/26213122/66145186-27c13b00-e5bf-11e9-8d0e-253926cba228.png)

I also saw a white box around the Pod header on the settings page, but I need to confirm that wasn't fixed with the updated assets in https://github.com/ps2/rileylink_ios/pull/539

**Comment by agottsd1** [comment]
Darkmod fail in Carb Ratios
v1.10.0DEV enter value not visible white background white digits.

**Comment by justinr1234** [comment]
I have all sorts of wonky UI from dark mode, am I missing something?

**Comment by beached** [comment]
This is tangentially to related to my issue https://github.com/LoopKit/Loop/issues/1213 where the dialogs are all offset from the top too much

**Comment by t1dloop** [comment]
Seems to have cleared up all my display issues. Thanks.

**Comment by ps2** [comment]
Recent release of CGMBLEKit, which is included in latest release of Loop, should fix dark mode issues.
