### ISSUE TITLE
Loop on Watch broken after watchOS 5.3.2 upgrade

### ISSUE THREAD

**Issue by seanknox** [LoopKit/Loop#1146]
Since installing watchOS 5.3.2, the Loop app on my Apple Watch crashes when opening. 

- Re-installing the app on the watch doesn't help.
- I've tried to rebuilding Loop in Xcode but it is stuck at "Installing Symbols for watchOS 5.3.2 (16U611).

![image](https://user-images.githubusercontent.com/1231630/66706674-99e5fe00-ecea-11e9-9782-abf40384566a.png)

**Comment by NightScoutForSeb** [comment]
I just saw on the Xcode 11.1 downloads page that there’s a bug specific to 5.3. It says to try a different watchOS. Maybe try 5.0. That is also the workaround described in the loop docs. 


Sent from Yahoo Mail for iPhone


On Saturday, October 12, 2019, 12:21 PM, Sean Knox <notifications@github.com> wrote:


Since installing watchOS 5.3.2, the Loop app on my Apple Watch crashes when opening.
   
   - Re-installing the app on the watch doesn't help.
   - I've tried to rebuilding Loop in Xcode but it is stuck at "Installing Symbols for watchOS 5.3.2 (16U611).

**Comment by seanknox** [comment]
> I just saw on the Xcode 11.1 downloads page that there’s a bug specific to 5.3. It says to try a different watchOS. 

@NightScoutForSeb can you point me to the link that says that?

**Comment by NightScoutForSeb** [comment]
See the release notes section for watchOS https://developer.apple.com/documentation/xcode_release_notes/xcode_11_1_release_notes 


Sent from Yahoo Mail for iPhone


On Monday, October 14, 2019, 6:39 PM, Sean Knox <notifications@github.com> wrote:



I just saw on the Xcode 11.1 downloads page that there’s a bug specific to 5.3. It says to try a different watchOS.


@NightScoutForSeb can you point me to the link that says that?

**Comment by seanknox** [comment]
Thanks for the link @NightScoutForSeb.

Problem was fixed by rebooting my Apple Watch. Very weird, considering the watch reboots as part of upgrading to a new version. 🤷‍♂
