### ISSUE TITLE
Loop not matching dexcom, not finding Riley link, and issues with lightning icon

### ISSUE THREAD

**Issue by mys385** [LoopKit/Loop#1187]
Hello,

Over the last few days I’ve noticed my loop app lagging behind and not matching Dexcom. It also constantly is turning yellow even with Riley link right nearby. And when I try to see Bolus suggestions via the lighting icon, it’s blank. 

I downloaded the latest dev branch last night but that doesn’t seem to have helped. I’ve included screenshots and any help would be greatly appreciated!

![970B04D6-38AF-48BF-A2A6-81B69AD01CA0](https://user-images.githubusercontent.com/52628363/69479799-10d0e500-0dc7-11ea-86de-ee4d76073e91.png)
![D201210E-D09A-4FA9-838C-4A89C1EF0C12](https://user-images.githubusercontent.com/52628363/69479800-11697b80-0dc7-11ea-96d5-4d9f4860b42c.png)
![C87C7205-8E46-4054-95C9-4213CF5A9B36](https://user-images.githubusercontent.com/52628363/69479801-11697b80-0dc7-11ea-90dc-35cbcf0955d4.png)

**Comment by mys385** [comment]
The issues report also does not seem to generate. 
![1E92F97C-4888-41DC-819D-6C7BE3585256](https://user-images.githubusercontent.com/52628363/69479825-555c8080-0dc7-11ea-9e24-f5169b77f0d1.png)

**Comment by mys385** [comment]
Another screen shot of Riley link device. Also, I use omnipod, not Medtronic. 

![13055CDA-AD18-46B6-9B8B-D785E178BBCC](https://user-images.githubusercontent.com/52628363/69480136-41664e00-0dca-11ea-9df7-f5d036fe001c.png)

**Comment by Kdisimone** [comment]
https://loopkit.github.io/loopdocs/troubleshooting/yellow-red-loop/

**Comment by Kdisimone** [comment]
These kind of issues, by the way, are best resolved with a post on Zulipchat or Looped group. They represent a more temporary issue rather than a true bug to be resolved. So I'm going to close this issue and encourage you to check out the troubleshooting steps in link above and to post in one of the groups if you need further help. If posting in groups, make sure to provide a detailed description of the steps you took and screenshots to help demonstrate that you've done those steps. Thanks.

**Comment by mys385** [comment]
Thank you, Katie.
