### ISSUE TITLE
Persistent Red Loop - RileyLink did not respond in time (RileyLink/Minimed722/G6)

### ISSUE THREAD

**Issue by adamcin** [LoopKit/Loop#1212]
**Describe the bug**
RileyLink connectivity appears to degrade to a point requiring a restart of the iphone. This error state appears in Xcode debug logging as a consistent timeout during device autotune. 

Once error is observed in Loop Status indicator, I confirmed that RileyLink LED is green, Loop Settings -> Minimed 722 -> RileyLink Signal Strength is ~ -50dB. Flipping the RileyLink GUI switch forces autotune reattempt, but fails to resolve this error.

When any RileyLink communication errors are observed, including this timeout scenario, I have attempted to resolve them with a few methods in the following order:

1. Flip GUI RileyLink switch in Loop Settings -> Minimed 722.
2. Flip physical on/off switch on RileyLink.
3. Force restart Loop app
4. Restart iPhone

Only a restart of the iPhone appears to resolve this particular persistent timeout error with consistency.

**Screenshots**

![Screenshot 2019-12-25 at 2 10 45 PM](https://user-images.githubusercontent.com/524972/71450497-1c8e2f00-2718-11ea-9712-475acbe4963c.jpeg)

**To Reproduce**
Appears to be non-deterministic when starting from working state. Occurs after a few hours. 

**Expected behavior**
Autotune timeout errors should not persist when rileylink and pump are in close proximity to iphone, and battery strength for all three devices is above 50%.

**Phone**
 - Hardware: iPhone 8 Plus
 - OS Version: iOS 13.1.2

**Loop Version**
 - Version Number: v1.10.1
 - Repo: LoopKit/Loop
 - gitRevision: ac31e0b26bdbdab7688be702d5f4c1f61940de44
 - gitBranch: dev

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 722
 - Firmware version: 2.4A1.1

**Additional context**
See attached issue report and debug log, which captured multiple failed autotune attempts before eventually correcting itself with no apparent cause, at which point the phone was disconnected and logging was terminated without restarting the app.

[LoopIssueReport.txt](https://github.com/LoopKit/Loop/files/4000814/LoopIssueReport.txt)

[LoopDebugLog.txt](https://github.com/LoopKit/Loop/files/4000815/LoopDebugLog.txt)

**Comment by kathyaa** [comment]
I too am having this error. I had upgraded to Loop 2.0. Medtronic 522, Firmware version 2.1A 1.1 0B 0B, G5, iPhone 11 Pro,  running Loop Master, downloaded and loaded to devices:  January 2, 2020. Apple Watch v. 5, stopped running Loop, also. Watch screen would appear, then go away. Appeared to crash. Could not reproduce the error. Loop spent 3 days coming and going, mostly going.

Decided to re-compile on January 24. Downloaded/updated Homebrew, new Xcode version 11.3.1. Since reload to hardware devices, Loop appears to stay up and running on iPhone, Riley, and Watch.

**Comment by Foxbat15** [comment]
I too am having this issue with an iphone 7

**Comment by arvindagarwallibre** [comment]
I am having this issue as well but flipping physical on/off switch on RileyLink gets it going again.

**Comment by oldebeken** [comment]
> **Describe the bug**
> RileyLink connectivity appears to degrade to a point requiring a restart of the iphone. This error state appears in Xcode debug logging as a consistent timeout during device autotune.
> 
> Once error is observed in Loop Status indicator, I confirmed that RileyLink LED is green, Loop Settings -> Minimed 722 -> RileyLink Signal Strength is ~ -50dB. Flipping the RileyLink GUI switch forces autotune reattempt, but fails to resolve this error.
> 
> When any RileyLink communication errors are observed, including this timeout scenario, I have attempted to resolve them with a few methods in the following order:
> 
> 1. Flip GUI RileyLink switch in Loop Settings -> Minimed 722.
> 2. Flip physical on/off switch on RileyLink.
> 3. Force restart Loop app
> 4. Restart iPhone
> 
> Only a restart of the iPhone appears to resolve this particular persistent timeout error with consistency.
> 
> **Screenshots**
> 
> ![Screenshot 2019-12-25 at 2 10 45 PM](https://user-images.githubusercontent.com/524972/71450497-1c8e2f00-2718-11ea-9712-475acbe4963c.jpeg)
> 
> **To Reproduce**
> Appears to be non-deterministic when starting from working state. Occurs after a few hours.
> 
> **Expected behavior**
> Autotune timeout errors should not persist when rileylink and pump are in close proximity to iphone, and battery strength for all three devices is above 50%.
> 
> **Phone**
> 
> * Hardware: iPhone 8 Plus
> * OS Version: iOS 13.1.2
> 
> **Loop Version**
> 
> * Version Number: v1.10.1
> * Repo: LoopKit/Loop
> * gitRevision: [ac31e0b](https://github.com/LoopKit/Loop/commit/ac31e0b26bdbdab7688be702d5f4c1f61940de44)
> * gitBranch: dev
> 
> **CGM**
> 
> * Device: Dexcom G6
> * Manager app: Dexcom App
> 
> **Pump**
> 
> * Manufacturer: Medtronic
> * Model: 722
> * Firmware version: 2.4A1.1
> 
> **Additional context**
> See attached issue report and debug log, which captured multiple failed autotune attempts before eventually correcting itself with no apparent cause, at which point the phone was disconnected and logging was terminated without restarting the app.
> 
> [LoopIssueReport.txt](https://github.com/LoopKit/Loop/files/4000814/LoopIssueReport.txt)
> 
> [LoopDebugLog.txt](https://github.com/LoopKit/Loop/files/4000815/LoopDebugLog.txt)

Hey, I’m having the same issue. Restarting the RL and iPhone seem to correct it for only a few hours. When you say “recompiled” to correct the issue, what are you referring to? 

Running loop 2.0 master and then dev, RL 0.9 firmware, 722, batteries charged up.

**Comment by oldebeken** [comment]
> I too am having this error. I had upgraded to Loop 2.0. Medtronic 522, Firmware version 2.1A 1.1 0B 0B, G5, iPhone 11 Pro, running Loop Master, downloaded and loaded to devices: January 2, 2020. Apple Watch v. 5, stopped running Loop, also. Watch screen would appear, then go away. Appeared to crash. Could not reproduce the error. Loop spent 3 days coming and going, mostly going.
> 
> Decided to re-compile on January 24. Downloaded/updated Homebrew, new Xcode version 11.3.1. Since reload to hardware devices, Loop appears to stay up and running on iPhone, Riley, and Watch.

Hey, I’m having the same issue. Restarting the RL and iPhone seem to correct it for only a few hours. When you say “recompiled” to correct the issue, what are you referring to? 

Running loop 2.0 master and then dev, RL 0.9 firmware, 722, ios13.6, Xcode beta, batteries charged up.

**Comment by billybooth** [comment]
@kathyaa, has this issue reoccurred for you, or has it remained resolved?

I am a fairly new Loop user (a couple of weeks in) on a MiniMed 723 on 2.3A on both the `development` and `automatic-bolus` branches, and this issue has been absolutely driving me crazy. I've been running into it for what seems like only the last week or so, but perhaps I was just fiddling with everything enough not to have noticed in the first week.  I have experienced it roughly once every 24 hrs.  I have experienced it with two RileyLinks, both in a W2 wireless charging case, and the only reliable (although temporary) resolution for me is to physically restart the RileyLink, although occasionally trying to suspend and resume the pump a few times will kick the tires and get things working again.  I will attempt to pull some debug and issue logs the next time this occurs for review, but it seems like there's too many reports here for this to be anomalous.

I have a second MiniMed 723 on 2.4A that I'm inclined to switch to see whether the pump hardware is a factor, although I assume this is something nascent in `rileylink_ios` or `Loop`.  Any further troubleshooting tips or insights are welcome.

**Comment by kathyaa** [comment]
I am running 2.2.0 which seems to resolve that issue. Recompile means to re-run the build process and re-install on the iPhone. A compiler, or sorts, such as x code ‘translates’ source code (what the programmer writes) into machine language that the device understands. I too, have changed pumps, Riley, etc, looking for resolution. Loop 2.2 master seems to have resolved that issue, but the watch flat-out doesn’t work. It used to, but doesn’t now. Since it isn’t ‘essential’ to the system, I quit re-booting the watch twice a day to get it to work.

Kathy Alexander

**Comment by billybooth** [comment]
@kathyaa, thank you for your quick reply.  Did you happen to remove Loop from your phone and re-enter your settings from scratch when you recompiled it?  @oldebeken above seems to indicate that his build from `master` produced the same issue, and the original report was from v1.x, so I'm thinking that this problem can occur in a build from any branch if the circumstances are right.  In the past week I have seen the issue across two RileyLinks, two RileyLink BLE firmware builds, three or so LoopWorkspace builds (`development`, `automatic-bolus`) against a vanilla and forked/modified `rileylink_ios` `dev` branch, so basically the only things I haven't put it through are a pump change and an app deletion and setup from scratch.  I'm not opposed to getting dirty and trying to scratch out a resolution, but I'm still trying to figure out where the issue actually is, since there are a good number of moving parts.
