### ISSUE TITLE
[Idea]24h target curve

### ISSUE THREAD

**Issue by mblgmblgmblg** [LoopKit/Loop#1261]
Hello Dev-Team
i would like to be able to plan my target sugar level over several hours in advance (e.g. for an upcoming sports activity in 8h, with a duration of 3h, a high intensity and in the post with changed insulin sensitivity including refilling of the sugar storage).
I suspect that it should be possible to adjust a target curve over 24h with the help of a graphical support. 
The adjustment should be adjustable in freely configurable time windows regarding target value, insulin intensity and should be storable as a peset (like the Temporary Override). A flexibal adjustment during the use of this specific configuration would be nice, too.
I hope that someone wants to implement this and can program it accordingly.
Thanks in advance!!!!

**Comment by rodig03** [comment]
Sorry, but I think we do not need it as it can be done already. 
Just klick on the calender symbol (version 2.1) of the override, enter the start time and duration ...

**Comment by cyoung1024** [comment]
I believe what OP means is the ability to set multiple overrides, as they referenced being able to specify a different ISF in the follow-up after the initial 3 hour sports override. This can of course be done manually after the initial 3 hour override, but automating the process could be interesting.

**Comment by rodig03** [comment]
Cal, I agree that this might be interesting and might be the intention of the OP. 
In my personal life, however, I wouldn't do it to ensure I will check the sitution and adapt it to the reality then. Automating also is increasing the risk if the timing changes or the intensity of the workout, or the glucose level of the sports drink, or ... Let's see if there is anyone who thinks this is the topic to work on now - for me perfecting auto bolus / micro bolus would rate higher.

**Comment by mblgmblgmblg** [comment]
Thank you for the quick answer. As assumed, I meant the sequence of several overrides with different settings. As an example I would like to describe the following application. If I want to do an exercise session at 6 a.m, than I don't want to have to adjust my override at 4 a.m. (and eat a lot of sports carbohydrates). Instead, it would be nice if i could go to sleep in the evening the day before with my default settings and have them automatically change to a predefined preset / override (in this case reducing the basal rate and raising the target curve from 4am at night) without having to get up during night and do it manually. But this is only one of many use cases that would be covered by this feature. I hope to find supporters who like the idea.

**Comment by rodig03** [comment]
Hi mblgmblgmblg,

you already *can* set the override to start in the night at 4am and enter this during the evening before! Just set the start time accordingly.

As Cal said, you only can set one override in advance, but your example can be easily covered right now.

 

Von: mblgmblgmblg <notifications@github.com> 
Gesendet: Dienstag, 4. Februar 2020 15:28
An: LoopKit/Loop <Loop@noreply.github.com>
Cc: Robert Henke <robert.henke@gmx.de>; Comment <comment@noreply.github.com>
Betreff: Re: [LoopKit/Loop] [Idea]24h target curve (#1261)

 

Thank you for the quick answer. As assumed, I meant the sequence of several overrides with different settings. As an example I would like to describe the following application. If I want to do an exercise session at 6 a.m, than I don't want to have to adjust my override at 4 a.m. (and eat a lot of sports carbohydrates). Instead, it would be nice if i could go to sleep in the evening the day before with my default settings and have them automatically change to a predefined preset / override (in this case reducing the basal rate and raising the target curve from 4am at night) without having to get up during night and do it manually. But this is only one of many use cases that would be covered by this feature. I hope to find supporters who like the idea.

**Comment by cyoung1024** [comment]
>Automating also is increasing the risk if the timing changes or the intensity of the workout, or the glucose level of the sports drink, or ...

Agreed, I personally wouldn't put this into place with sports because of those factors, but there have been times where I've wanted two overrides set up in advance. Exams are a good example for me. I like to set a high temp for stress during the exam itself, but around an hour or two afterwards I crash after the stress dissipates. In that case I'd love to be able to set a high temp with a lower target for the first 2/3rds of the exam, but let Loop know that, an hour before it's over, I'd like to set a lower temp and / or a higher target in preparation for the crash, instead of pulling my phone out during the exam. So far having the high temp set for only a portion of the exam isn't enough to stop the drop from happening, though if coupled with a snack towards the end and annoyed glances from my neighbours that does the trick, haha.

mblgmblgmblg, as Robert said you can set your 6am target far in advance, before you go to bed even. By clicking on the override button, then on the calendar icon next to the override description, you can set a temp target even days in advance if you so choose. This is possible in both master and dev.

**Comment by mblgmblgmblg** [comment]
Thanks a lot for your advice, I will try it.
