### ISSUE TITLE
App immediately crashing 

### ISSUE THREAD

**Issue by KattyGents** [LoopKit/Loop#1288]
Running V2.1.0 

Payed account 

Account not expired 

Loop is still “working”. Not getting any loop has not completely successfully in ____ time errors and can see a green circle right before it closes.

**Comment by Kdisimone** [comment]
There isn't a loop v2.1.0 release at this point in time. Perhaps you mean you're using dev branch?  

But this also isn't really a good place for putting this problem. Instead, I'd recommend posting to looped fb group or Zulipchat if you want troubleshooting help. The issues list is more for reporting and catching bugs in Loop. 

Sounds like you may have a phone or iOS issue as we don't have any other reports of this problem on dev builds from other users. I'll close this out and encourage you to use one of the two places mentioned above for troubleshooting ideas. (I'd suggest restarting phone, rebuilding, and then deleting and rebuilding...in order of things to try depending on how stubborn your issue is.)

**Comment by scottf51** [comment]
I have actually seen this but assumed it was my fault 

It happened when I upgraded the workspace version , despite doing git stash for me creds etc 

In the end I just nuked the local copy of the git repo and started again and it was fine , worth a try if that’s what you have done
