### ISSUE TITLE
Proposal: Remove or extend future date limit on carb entry in Loop

### ISSUE THREAD

**Issue by sraka1** [LoopKit/Loop#1299]
**Describe the problem**
Maximum carb entry date is limited to 4 hours in the future by `maximumDateFutureInterval` in CarbEntryViewController when entering carbs in Loop.

**Attach an Issue Report**
N/A

**To Reproduce**
1. Go to CarbEntryViewController
2. Click on Date
3. Scroll down to the maximum date period
4. See maximum date

**Expected behavior**
Do not limit this behaviour or set the limit higher (+8 hours). I understand that this is most likely a safety feature, but consider the following use case - on a keto diet, eat a large stick of butter (i.e. 100g). The effects of gluconeogenesis on BG may appear several (even >4) hours later (specific to each individual). If this issue only pertains to me, then please close the issue. If Loop maintainers agree, I will open a PR to either remove or prolong the time limit.

**Screenshots**
N/A

**Phone**
N/A

**Loop Version**
 - Version Number: dev
 - Repo: LoopKit/Loop

**CGM**
N/A

**Pump**
N/A

**Additional context**
N/A

**Comment by marionbarker** [comment]
This request is desired by a lot of people. It is a very popular customization to set 4 hours as the future limit.

**Comment by jeremybarnum** [comment]
It seems as if based on the recent refactoring, this should now be an easy customization by changing the value of maxCarbEntryFutureTime in LoopConstants.  But that doesn't seem to work. The reason seems to be that the behavior is controlled by the variable maximumDate in the CarbEntryViewModel class, which is hard coded.  However, setting maximumDate to LoopConstants.maxCarbEntryFutureTime produces unexpected behavior.  The cap on the entry time in the picker is removed completely, rather than moved to the level specified in LoopConstants.  I can't figure out why.   It's worth noting that changing the hard coded value in CarbEntryViewModel to another value, like 2 hours, the picker behavior is as expected.  The problem is only when trying to link that field to the value specified in LoopConstants.
