### ISSUE TITLE
No glucose prediction when using Open Loop mode

### ISSUE THREAD

**Issue by ggsubs** [LoopKit/Loop#1319]
There is no glucose prediction shown when Loop is in open-loop mode.

![IMG_1904](https://user-images.githubusercontent.com/2170237/80774031-a90a8d00-8b10-11ea-8eec-78bbbe182828.PNG)

![IMG_1905](https://user-images.githubusercontent.com/2170237/80774477-fdfad300-8b11-11ea-87ee-177aa1cc5a56.PNG)

In earlier Loop 1.x version glucose prediction was present. The prediction tool toggles are set - no combination of the settings produce a prediction curve.

 - Hardware: [iPhone XS Max]
 - OS Version: [iOS 13]

**Loop Version**
 - Version Number: [2.2.0]
 - Repo: [LoopKit/Loop master]

**CGM**
 - Device: [ Dexcom G6]
 - Manager app: [Dexcom App]

**Pump**
No pump. Using an open loop. Insulin entries in HealthKit by the InPen App.

**Comment by Kdisimone** [comment]
This is not a Loop version-related issue. You don't have a prediction because your Loop doesn't have pump data. Notice the dashes under the pump in the HUD in Loops main screen. 

Please try Loopdocs page for resolving red loops under the Troubleshooting section. Thanks. 

I'm going to close this issue because this more a typical red loop issue. If you can't resolve it using the suggestions in Loopdocs, then make a post explaining what you've tried in Looped group or Zulipchat. Thanks.
