### ISSUE TITLE
Driver for Accu-chek Solo pump?

### ISSUE THREAD

**Issue by pbudzon** [LoopKit/Loop#1327]
Hi all,  

I'm interested in helping develop a driver for Accu-check Solo pump. Has there been any work done in this area, any thoughts or issues identified?
From what I can gather, I need to wait for my next base change so the sniffer can listen in on the pairing between the base and the pilot to get the code to decrypt later communication. 

The pump uses BLE - which (as far as I know) is supported by iOS, so Loop wouldn't need to use RileyLink to "talk" to the pump. Is an interface like that possible in Loop? I imagine all new pumps are coming with BLE or "normal" bluetooth, so Loop will need to be able to talk to the them without Riley anyway, unless there's no plan to support such pumps?

Any thoughts or comments would be appreciated.

**Comment by pusewicz** [comment]
Same applies to Accu-Check Insight. It already works with AndroidAPS, which could be used as a guide for the driver for Loop. I'd love to help too!

**Comment by dcallagh** [comment]
Hi,  We are coming up for pump change soon, would love to help, how do I sniff the traffic?

**Comment by pbudzon** [comment]
@dcallagh Do you have a BLE sniffer device? Usage depends on the device, instructions usually come with it.

**Comment by dcallagh** [comment]
No unfortunately. I'll try wireshark on linuxSent from my Samsung Galaxy smartphone.
-------- Original message --------From: Paulina Budzoń <notifications@github.com> Date: 17/6/20  5:31 pm  (GMT+10:00) To: LoopKit/Loop <Loop@noreply.github.com> Cc: dcallagh <dcallagh@iname.com>, Mention <mention@noreply.github.com> Subject: Re: [LoopKit/Loop] Driver for Accu-chek Solo pump? (#1327) 
@dcallagh Do you have a BLE sniffer device? Usage depends on the device, instructions usually come with it.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/LoopKit/Loop/issues/1327#issuecomment-645204988",
"url": "https://github.com/LoopKit/Loop/issues/1327#issuecomment-645204988",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by bwauge82** [comment]
I wanted to check if anyone has been successful in looping with the ACCU-CHEK Solo? I am on the hunt for a new pump.

**Comment by DanUK3** [comment]
Hello. Is there any news on this? I use the Solo pump and Dexcom G6 on iPhone. Would love to be able to loop! Thanks :-)

**Comment by dcallagh** [comment]
Well, turns out I need a Bluetooth snooper and at the moment they are 300 so it may have to wait until they come down  to 100, others may have snooped the sessions though?Sent from my Galaxy
-------- Original message --------From: DanUK3 <notifications@github.com> Date: 13/11/20  5:33 pm  (GMT+10:00) To: LoopKit/Loop <Loop@noreply.github.com> Cc: dcallagh <dcallagh@iname.com>, Mention <mention@noreply.github.com> Subject: Re: [LoopKit/Loop] Driver for Accu-chek Solo pump? (#1327) 
Hello. Is there any news on this? I use the Solo pump and Dexcom G6 on iPhone. Would love to be able to loop! Thanks :-)

**Comment by dcallagh** [comment]
Ok, will be another 4 months to get a capture unfortunately. I have the ubertoothOne. Had difficulty isolating the control unit. Does anyone know the actual manufacturer? Could it be Texas Instruments? For anyone else having a try the pump shows up as 'Roche diagnostics' and you should look for the 'new' Roche BT address when pairing to the new pump..--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 13/11/20, 6:33 pm DanUK3 <notifications@github.com> wrote:

   
  Hello. Is there any news on this? I use the Solo pump and Dexcom G6 on iPhone. Would love to be able to loop! Thanks :-)

**Comment by SebastianUrbicain** [comment]
I'm in a Discord group related with the Android APS develope. There is a channel for "solo-dev". In that group, the are a couple of hackers who try to comunicate with the micro pump. What I understand is:
1) [DavidWillems13] "the pump bases have the "LE discoverable mode flag" set to 'false' after they've been configured to the pump base the first time. I'm not sure if this is going to prevent us from being being able to communicate with a pump base if it's been previously paired to the manager". 
2) Is not possible to use the tecnique "man-in-the-middle" (between the diabetes manager and the micro pump) to see the traffic because is encripted (as I understand)...

I also frustate... 

Hope some hacker could break the comunication... 

Best Reagrds.
Sebastian.

**Comment by DadeKuma** [comment]
Any news? This is the last update (5 June 2021):

> These are the things that we must solve:
> 1) When the Diabetes Manager (DM) is paired (Bluetooth LE) with the micropump, the micro pump stops "advertising" (set the "LE discoverable mode flag" flag to 'false') and no one else can connect to it.
We do not know how to (hardware or software) reset the micro pump so we can make tests from others devices.
> 2) We have the APKs (and the Java source code) of the apps that run on DM (which runs on Android version 4.2). 
Also, there is a native library (not the source code) programmed in C and is compiled for old ARM processors (32-bit technology) which is the one that handles the communication between DM and micro pump.
It is difficult to disassemble this library (but not impossible) and then migrate it to the new architecture (ARMv8, x86, x64).

[Link to the decompiled APK and C library](https://drive.google.com/drive/folders/1Shz4vuerh1CI9EQIwcn3i7eFFtKh-WPr)

**Comment by dcallagh** [comment]
Sorry, it is beyond my capabilities. I gave up. We moved to a tslim.Sent from my Galaxy
-------- Original message --------From: Dave ***@***.***> Date: 25/1/23  9:15 am  (GMT+10:00) To: LoopKit/Loop ***@***.***> Cc: dcallagh ***@***.***>, Mention ***@***.***> Subject: Re: [LoopKit/Loop] Driver for Accu-chek Solo pump? (#1327) 
Any news? This is the last update (5 June 2021):

These are the things that we must solve:

When the Diabetes Manager (DM) is paired (Bluetooth LE) with the micropump, the micro pump stops "advertising" (set the "LE discoverable mode flag" flag to 'false') and no one else can connect to it.
We do not know how to (hardware or software) reset the micro pump so we can make tests from others devices.
We have the APKs (and the Java source code) of the apps that run on DM (which runs on Android version 4.2).
Also, there is a native library (not the source code) programmed in C and is compiled for old ARM processors (32-bit technology) which is the one that handles the communication between DM and micro pump.
It is difficult to disassemble this library (but not impossible) and then migrate it to the new architecture (ARMv8, x86, x64).


Link to the decompiled APK and C library

**Comment by coone983** [comment]
Hi,

Anybody got any further with this?
Using a solo pump because it's easy to remove when I'm diving, only would really love to be able to loop it
