### ISSUE TITLE
Feature Request - Override Setting for Auto-Bolus/Temp Basal Strategy

### ISSUE THREAD

**Issue by tabula-raza** [LoopKit/Loop#1329]
Problem: On automatic-bolus branch, I want to select dosing strategy (automatic bolus vs temp basal) specific to the override I'm programming. E.g. For exercise mode I want temp-basal, not automatic bolus. Similarly, for custom overrides, it may make more sense for dosing to be more cautious (temp basal) and in others more confident (auto-bolus).

Solution: Add a picker for dosing strategy (automatic bolus vs temp basal) to the override settings screen.

**Loop Version**
 - Version Number: 2.3.0
 - Repo: LoopKit/Loop/tree/automatic-bolus

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros

**Additional context**

**Comment by ps2** [comment]
Automatic bolus vs temp basal strategies both attempt to deliver the same amount of insulin. Where they vary is that bolusing is faster than temp basals. This can help with correcting highs faster, but does not impact delivery as much when bg is lower. If you feel you need less insulin when exercising, the right nobs to tweak are ISF and target range.

**Comment by absmindedprof** [comment]
There are other scenarios where I don't want Loop delivering insulin quickly (or to put another way, where I don't want the default dosing strategy, which in my case is automatic bolus).

For example I'm using overrides for fasting during Ramadan. This is a situation with higher levels of uncertainty (insulin needs are fluctuating) and less margin for error (I'm probably close to target BG, and I'm trying to avoid using carbs to nudge my BG during the daytime). In those circumstances, I prefer to leave Loop on temp-basal during the day time. Because there are no food spikes, I don't need the correction effect of automatic bolus. And because less insulin is delivered in between each closing of the loop and insulin need recalculation, that gives Loop more room to maneuver with low-temps. (By contrast, I want auto-bolus on overnight when I'm typically trying to combat the post-prandial spike and stubborn highs that often follow breaking the fast.) 

I already use a higher correction range in order to give myself greater margin for error during the daytime, but would like to backstop it with the change in dosing strategy.

Another scenario where I would not want the 'default' of automatic bolus, is when I've treated a low. Like others, I have an override that temporarily sets a higher correction range to keep Loop from aggressively reacting to the sudden (but typically short) rise after eating fast carbs. Backstopping that with a change in dosing strategy would also help, I think.

To be clear, I already do this manually (set the override, then change the dosing strategy). But because they're not coupled, and there's no indication of what dosing strategy is in effect on the main screen, I sometimes forget. And diving into the menus repeatedly is a hassle.

**Comment by ps2** [comment]
Let me put it a different way: if loop is dosing you with automatic bolus when you don't need insulin, it would still be dosing you with temp basal when you don't need insulin. The thing we need to fix in this case is why Loop is calling for insulin, not how it delivers it.

**Comment by absmindedprof** [comment]
"Automatic bolus vs temp basal strategies both attempt to deliver the same amount of insulin"

"The thing we need to fix in this case is why Loop is calling for insulin, not how it delivers it."

I acknowledge and agree with both of these statements. What I'm saying is that there are situations (like the Ramadan example) where to the extent the settings are the problem, they are going to continue to be a problem and/or I need time to figure out what the correct settings are. 

As you said above, both strategies *attempt* to deliver the same amount of insulin. But in both scenarios Loop is also re-evaluating the amount of insulin needed every 5 minutes. In a scenario where there is low confidence, I would rather Loop have delivered less of that insulin by the time it reevaluates. 

I guess what I'm getting at is that as a Loop user of AB branch there is a setting that affects Loop's behavior that I cannot set when programming an override, and I would like to be able to set it.

**Comment by ps2** [comment]
In general I would advise not using dosing strategy as a therapy setting; it's not designed that way (i.e. no visual indicator, deep in nav to change). The only reason it's toggleable at all is that this is an experimental branch and this makes it easy to enter the experiment, and leave it if needed.  It's not supposed to be something you turn on and off. If the on setting isn't working, let's dig into where it's failing for you.

**Comment by ps2** [comment]
Here's another reason why I think using bolus vs tb as a therapy setting is problematic: in the cases of connectivity issues, which unfortunately do happen rather frequently in DIY loop, tb can be *more* aggressive than bolus. Say you had a snack before exercising in an attempt to keep up your bg, and your bg starts rising, and then you go offline, and bg starts dropping, and your food doesn't hit because you're exercising. 100% of the insulin could be delivered within 30m after the initial dose on tb, but only 40% on bolus. 

Adjusting your temporary target upwards is a better strategy with Loop at this point if you feel like you want more wiggle room to deal with uncertainty.

**Comment by ps2** [comment]
Ultimately, I would like automatic bolus to be the de-facto delivery method for loop. With the right partial application factor, I believe it can be more effective *and* just as safe if not safer than temp basal delivery.

**Comment by Nightfoxy** [comment]
I'd love to have a override that just affects ISF for exercise.

FreeAPS has a solution that doesn't totally solve the problem, but has a
toggle for setting a target threshold that switches back to temp basal when
the an override has a target range above a certain BG Level.

**Comment by sthrthxs5** [comment]
> Ultimately, I would like automatic bolus to be the de-facto delivery method for loop. With the right partial application factor, I believe it can be more effective _and_ just as safe if not safer than temp basal delivery.

I firmly disagree with this statement.  I understand that they have the same end result but there are far more variables that loop will never be able to compensate for beyond things like ISF.  Take a teenage girl for example, there are soooo many factors that can throw dosing out of wack in the span of a couple hours that loop just can’t deal with.  TB is far more gentle in dealing with this than AB. This is why I have asked for a floor to AB where TB takes back over before and why this subject keeps coming up.  I’m starting to feel like you have simply dug in your heels Pete and are not interested in what others actually are seeing. My $0.02 that should not be confused with the great amount of appreciation I have for your contributions.

**Comment by ps2** [comment]
@sthrthxs5 This topic in particular isn't a matter of opinion as much as it is a design choice. For instance, if we add some terms to loop dealing with our confidence level in the forecast, we can be more bold about dosing in some cases, and dose less in others, regardless of the actual delivery.

Think about this: if you did automatic bolus with a 16.6% partial application factor, it's exactly the same delivery as temp basal in a five minute period, with the benefit of not continuing high temp on signal loss. Right?  There you have an automatic bolus solution that has less chance of overdelivery than temp basals. 

For any given scenario, where we think there can be a dosing improvement in one direction or the other, that change can be implemented in different parts of the algorithm. Let's pick one where we think we are less certain about outcomes, and we expect more variability. We could just as easily say "cut the desired dose in this situation by 40%" and deliver it via boluses, and it would be the same effective dosing as choosing to deliver via temp basal.

Loop is an algorithm designed to achieve a certain end; there are many different ways to go about trying to achieve that end. I am choosing to organize the algorithm such we try to optimize aspects of how much insulin is needed, separately from how that insulin is delivered.

It's a complex algorithm, and it should be organized and well tended so that we can continue to improve it and make tweaks to it easily.  Lack of organization leads to a tangled mess where we can't play with individual parts of the algorithm without having inadvertent effects elsewhere.

**Comment by ps2** [comment]
Having said all that, it *is* open source and you are free to organize your own changes how you see fit.  As I said above, what is most helpful is people describing how using automatic bolus isn't working for them. Show some particular situations, describe what you've tried, show data, etc. Those help a lot more than arguing opinions about *how* you think the problem should be solved.

**Comment by sthrthxs5** [comment]
I believe there have been multiple times where people have described what isn’t working across multiple threads.  And yes, I realize anyone can branch this and create their own version but I hung up my programming skills a couple decades ago and now I’m just a lowly technologist that tries to bridge the gap between the market and our product teams.

**Comment by ps2** [comment]
@sthrthxs5 Not really. There have been a few mentions of vague problems, and requests to add feature x, but not really getting into what isn't working.  Most people are just saying it's working great for them.

A request that says "I want to shut off AB when x", or "can I automatically do X" aren't descriptions of problems, those are just feature requests. And unfortunately, even reading between the lines there is often little to go on in terms of what was tried, or what the situation was really like.

**Comment by ps2** [comment]
I would love to hear more about any issues people are having with the automatic bolus branch.  It's been really quiet on that front, actually.

**Comment by ps2** [comment]
There was one person recently who submitted a lot of screen shots and an issue report (awesome!) that was running the ab branch, but her issue ended up being unrelated to automatic bolusing, and just carb entry usage issues.

**Comment by Kdisimone** [comment]
@ps2 two brief things that are tangential but related:

1. AB branch does have a problem, but I failed to open an issue for it. The ABs need to be denied if the user has manually suspended the pump. When Anna had her glucagon incident, I suspended the pump...but loop on AB branch still gave a bolus. This shouldn't happen. I will open an issue for it now that my memory has been jogged. 

2. Multiple profiles are still needed to help get to that goal of having more reliable predictions for which loop to work from. It is still unnecessarily difficult for women to navigate hormone cycle changes. Because of the user interface being difficult/tedious to switch between hormonal settings changes, and overrides not being designed to address hormone change needs per se, the design is failing the users...especially women.  I support the design ethic to keep prediction algorithm as solid as possible, but that should include ways to help users tell Loop of times that change has happened. Overrides is part of the answer...but multiple profiles to quickly switch is critical. Otherwise people aren't helping Loop best help them. They sit on substandard settings for too long because of the inconvenience causing predictions to be incorrect. Or they rely on hacks like two incorrect things canceling each other out (carb ratio is wrong but adjust carb counts incorrectly to compensate)

**Comment by ps2** [comment]
Let's try to keep this on topic, folks. Raza had a request for a feature, I explained why I think switching between AB and TB is not a good solution to dosing problems, and asked to focus on understanding the problem first. And people are jumping in with all kinds of other commentary.

**Comment by Kdisimone** [comment]
Sorry, I think the Ramadan issue could be helped by multiple profiles. A way for a user to switch profiles cleanly and quickly with a single touch or two would help transition between nights and mornings that are so different, and where all the differences are not on an single insulin adjustment multiplier as overrides offers. 

Offering suggestions to the original topic (Ramadan) about times when adjustments are needed.  I wasn't simply narrowing the topic to AB/TB picker being a new override setting...as the original poster stated the true topic he was trying to address...Ramadan management made difficult.
