### ISSUE TITLE
Decreased decrements with Temporary Override and lowered Overall Insulin Needs

### ISSUE THREAD

**Issue by discodrake** [LoopKit/Loop#1352]
I run Loop v2.0, and when I activate a Temporary Override with a higher target and Lower Overall Insulin Needs, the decrements of the basal rate is decreased.
So, if my current glucose is 180 mg/dl and falling to like eventually -120 mg/dl the basal rate should be -0.8 (when my actual basal rate is 0.8 U/h). But if I set the ”Overall Insulin Needs” to 40%, the current basal rate becomes -0.32 U/h and not -0.8 U/h. This has to be a bug right, and possibly aleeady taken care of?

**Comment by Kdisimone** [comment]
Not a bug. The displays are relative to the OVERRIDE ADJUSTED basal rate schedule. (Caps for emphasis). If your regular basal schedule is 1.0 u/hr, you set an override for -20%, then your override adjusted scheduled basal would be 0.8 u/hr. So when loop decides you need a 0 u/hr basal due to predicted below suspend threshold (for example), you'd see a -0.8 u/hr in the status bar on Loop app.  

Hope that helps.

**Comment by discodrake** [comment]
I see, thanks a lot for the explanation!
