### ISSUE TITLE
Pod pairing didn't finish cleanly...

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#1369]
Pod pairing process didn't finish cleanly.  The cannula inserted, but Loop didn't apparently realize it.  Loop got stuck on insert cannula step. She had to do a backwards step in Loop's UI steps, and then needed to go through pairing steps again to "insert cannula" even though it was already inserted.

(I'm posting this on behalf of Dorrie Nuttall, who experienced the problem)

[Loop Report 2020-07-10 181108-0700.pdf](https://github.com/LoopKit/Loop/files/5206036/Loop.Report.2020-07-10.181108-0700.pdf)

**Comment by itsmojo** [comment]
Here's my Omnipod communications log analysis of this failure:

[2020-07-10_Nutall_insert_cannula_checking_failure_analysys.txt](https://github.com/LoopKit/Loop/files/5213194/2020-07-10_Nutall_insert_cannula_checking_failure_analysys.txt)

In summary, it appears to the user that the pod setup was successful, but Loop would not operate because the setup hadn't actually been completed. Thus Loop would go into a mystery red loop state. The recovery occurred only after 2-1/2 hours later when the user notices that the Pod Setting view indicated that the pod needed to "Finish pod setup" and then the "Insert Cannula" button was pressed (which must have felt weird if the user knows that they had already had the cannula inserted) and Loop finally was able to notice that pod was already in a ready state with a successful get status command.

For cannula insertions, the InsertCannulaSetupViewController thread waits 10 seconds and believes that the Insertion has successfully completed and the pod is ready without checking any status (assuming that the lower levels will handle?). The lower level OmnipodPumpManager::checkCannulaInsertionFinished() thread waits 10 seconds and calls PodCommsSession::checkInsertionCompleted() which tries to verify that the pod is ready (i.e., the insertion bolus has completed), but if this get status call fails for any reason (e.g., the RL is out of range), markSetupProgressCompleted() will never be called and the pod is never marked as ready. When checkInsertionCompleted() throws an error, checkInsertionCompleted() will simply log an error, but it doesn't report this failure to another layer and it doesn't retry.

**Comment by itsmojo** [comment]
Submitted https://github.com/ps2/rileylink_ios/pull/641 to fix this problem.
+ Don't have OmnipodPumpManager check cannula insertion as errors are lost
+ Have InsertCannulaSetupViewController do completion checking & report errors
+ Add optional finish case & Finish button to InsertCannulaSetupViewController
+ Add additional guard to prevent potential bad setup state problem
+ Remove unused cancelErrorCount var in InsertCannulaSetupViewController

Normally the only difference a user will notice is a few seconds of spinner after the insert cannula progress bar has finished while InsertCannulaSetupViewController synchronously checks the completion status before displaying "Continue" after the setup has been verified to be complete. If there is an error reading the pod status to verify that the setup has completed, the error and a new "Finish" button will be displayed which the user can then use to retry the get status to verify that the setup has been successfully completed.
