### ISSUE TITLE
Unable to build loop in xcode 12.6beta with simulator

### ISSUE THREAD

**Issue by timmy354321** [LoopKit/Loop#1374]
**Describe the bug**
I wanted to test if i could build this with ios 14 in xcode 12 beta. the build failed

**Attach an Issue Report**
See the screenshot

**To Reproduce**
1. download loop zip
2. sign all the required targets.
3.build loop in xcode 12 beta.

**Expected behavior**
Build successful

**Screenshots**
See attached

**Phone**
 - Hardware: [e.g. iPhone XS]
 - OS Version: catilina 10.15.6

**Loop Version**
 - latest version 2.2.1 

Omnipod version

![Image 9-16-20 at 12 09 PM](https://user-images.githubusercontent.com/48967293/93370272-29a6fd00-f816-11ea-8768-e7f9876ea04b.JPG)

**Comment by rodig03** [comment]
It works with the latest (GM) releases of ios and xcode – I did it today. Please update the command line tools as well.

 

Von: timmy354321 <notifications@github.com> 
Gesendet: Mittwoch, 16. September 2020 19:15
An: LoopKit/Loop <Loop@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [LoopKit/Loop] Unable to build loop in xcode 12.6beta with simulator (#1374)

 

Describe the bug
I wanted to test if i could build this with ios 14 in xcode 12 beta. the build failed

Attach an Issue Report
See the screenshot

To Reproduce
Steps to reproduce the behavior:

1.	download loop zip
2.	sign all the required targets.
3.build loop in xcode 12 beta.

Expected behavior
Build successful

Screenshots
See attached

Phone

*	Hardware: [e.g. iPhone XS]
*	OS Version: catilina 10.15.6

Loop Version

*	latest version 2.2.1

Omnipod version

 <https://user-images.githubusercontent.com/48967293/93370272-29a6fd00-f816-11ea-8768-e7f9876ea04b.JPG>

**Comment by andrew-anguiano** [comment]
@rodig03 I'm testing Xcode 12 (12A7209) with iOS 14 GM and am getting the same issue as OP :(

**Comment by timmy354321** [comment]
I've updated the command line tools to 12.0 and it's still failing.

**Comment by rodig03** [comment]
Die you download Xcode 12 GM today? It is not the same as the latest beta. 

Von meinem iPhone gesendet

**Comment by andrew-anguiano** [comment]
I downloaded it today. I actually switched to Loop/LoopWorkspace and built using the submodules and that worked just fine. @timmy354321 maybe give that a shot?
