### ISSUE TITLE
Loop build fail after compiling Amplitude.framework

### ISSUE THREAD

**Issue by cyoung1024** [LoopKit/Loop#1388]
**Describe the bug**
When building master 2.2.2, the build systematically fails after compiling Amplitude. The same error occurs when running a Carthage update.

**Attach an Issue Report**
Build log : 
[xcode_log.txt](https://github.com/LoopKit/Loop/files/5285538/xcode_log.txt)

Carthage update log : 
[xcode_log_carthage.txt](https://github.com/LoopKit/Loop/files/5285567/xcode_log_carthage.txt)

**To Reproduce**
After seeing a Facebook group member's post about this issue I built from Terminal and got the above output, they built in Xcode and got the same error.
I'm using Xcode 12.0, but they're using Xcode 12.0.1
We both have Carthage up to date (36)
I'm running macOS 10.15.6

**Screenshots**
Build fail : 
<img width="569" alt="Amplitude_build_fail" src="https://user-images.githubusercontent.com/42605906/94319277-8cbd3000-ff8a-11ea-9ced-a8ee9fadfeee.png">

Carthage fail : 
<img width="604" alt="Carthage_update_fail" src="https://user-images.githubusercontent.com/42605906/94319513-140aa380-ff8b-11ea-8a9e-8622af902c17.png">

**Phone**
 - Hardware: iPhone X (but ran my build using Simulator)
 - OS Version: 14.0

**Loop Version**
 - Version Number: 2.2.2
 - Repo: LoopKit

**Additional context**
Can confirm that Workspace works fine

**Comment by jenniferacooper** [comment]
Building master 2.2.2 downloaded today from Loopdocs Master link
Catalina 10.15.7
Xcode 12.0.1
carthage version 0.36.0
brew --version    Homebrew 2.5.2
Homebrew/homebrew-core (git revision a3a57e; last commit 2020-09-25)
Target Phone iPhone 7 Plus 14.0.1


![Screen Shot 2020-09-25 at 3 25 17 PM](https://user-images.githubusercontent.com/64930116/94321153-a8511800-ff43-11ea-8e3a-fc226f1ab344.png)





Showing Recent Issues
 	/usr/bin/xcrun lipo -create /Users/markoldham/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/Amplitude-iOS/2137d5fd44bf630ed33e1e72d7af6d8f8612f270/Build/Intermediates.noindex/ArchiveIntermediates/AmplitudeFramework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Amplitude.framework/Amplitude /Users/markoldham/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/Amplitude-iOS/2137d5fd44bf630ed33e1e72d7af6d8f8612f270/Build/Products/Release-iphonesimulator/Amplitude.framework/Amplitude -output /Users/markoldham/DevelopLoop/Loop-master-200925/Carthage/Build/iOS/Amplitude.framework/Amplitude


fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/markoldham/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/Amplitude-iOS/2137d5fd44bf630ed33e1e72d7af6d8f8612f270/Build/Intermediates.noindex/ArchiveIntermediates/AmplitudeFramework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Amplitude.framework/Amplitude and /Users/markoldham/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/Amplitude-iOS/2137d5fd44bf630ed33e1e72d7af6d8f8612f270/Build/Products/Release-iphonesimulator/Amplitude.framework/Amplitude have the same architectures (arm64) and can't be in the same fat output file



2.3 workspaces does not have issue.

**Comment by markjoldham** [comment]
Building master 2.2.2 downloaded today from Loopdocs Master link
Catalina 10.15.7
Xcode 12.0.1
carthage version 0.36.0
brew --version    Homebrew 2.5.2
Homebrew/homebrew-core (git revision a3a57e; last commit 2020-09-25)
Target Phone iPhone 7 Plus 14.0.1


![Screen Shot 2020-09-25 at 3 25 17 PM](https://user-images.githubusercontent.com/52680740/94321259-f2d29480-ff43-11ea-8de9-395687de6f65.png)





Showing Recent Issues
 	/usr/bin/xcrun lipo -create /Users/markoldham/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/Amplitude-iOS/2137d5fd44bf630ed33e1e72d7af6d8f8612f270/Build/Intermediates.noindex/ArchiveIntermediates/AmplitudeFramework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Amplitude.framework/Amplitude /Users/markoldham/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/Amplitude-iOS/2137d5fd44bf630ed33e1e72d7af6d8f8612f270/Build/Products/Release-iphonesimulator/Amplitude.framework/Amplitude -output /Users/markoldham/DevelopLoop/Loop-master-200925/Carthage/Build/iOS/Amplitude.framework/Amplitude


fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/markoldham/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/Amplitude-iOS/2137d5fd44bf630ed33e1e72d7af6d8f8612f270/Build/Intermediates.noindex/ArchiveIntermediates/AmplitudeFramework/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Amplitude.framework/Amplitude and /Users/markoldham/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0.1_12A7300/Amplitude-iOS/2137d5fd44bf630ed33e1e72d7af6d8f8612f270/Build/Products/Release-iphonesimulator/Amplitude.framework/Amplitude have the same architectures (arm64) and can't be in the same fat output file



2.3 workspaces does not have issue.

**Comment by ranagill** [comment]
**Describe the bug**
When building master 2.2.2, the build systematically fails . The same error occurs when running a Carthage update.

Attach an Issue Report
Build log :
Build Loop_2020-09-25T12-02-52.txt

**To Reproduce**
I have been facing this issue since yesterday, despite multiple attempts and updating everything, I am still unsuccessful to build the app, Cal and 1 other member were helping me fix the issue and they both got the same error as well, there is another user who posted similar issue on the facebook group.

Iphone X : IOS version 14.0.1
Mac: 10.15.17
Xcode: 12.0.1
Carthage 0.36.0
Loop Version Number: 2.2.2
Developer Account: Free

**Screenshots**

Build fail :
![image](https://user-images.githubusercontent.com/57372527/94321268-f6661b80-ff43-11ea-8048-b231f2cd9b92.png)


Carthage fail :
![image](https://user-images.githubusercontent.com/57372527/94321279-ff56ed00-ff43-11ea-8e16-f45cb863747c.png)

**Comment by rajid** [comment]
I don't claim to have a lot of experience with xcode, but after trying various "fixes" to deal with this, I'm now thinking that probably it simply has to do with the IPHONEOS_DEVELOPMENT_TARGET for Amplitude-iOS being set to 8.0.  Apparently, xcode 12 removed support for 8.0 and the lowest value allowed now is 9.0.  As I said, I don't have enough experience with xcode, so I can't really suggest what change would be needed.

https://developer.apple.com/forums/thread/656616

**Comment by NightScoutForSeb** [comment]
I also am getting this issue. Latest downloads / branch from last night don’t make a difference. I have everything up to date. It does sound like it’s an issue within the code, but why doesn’t everyone run I to this then?

**Comment by rajid** [comment]
I think everyone running xcode 12 runs into it.  I didn't see the problem until I upgraded to the latest xcode.

**Comment by Jimw338** [comment]
<warning: this post is a small/moderate/lot bit snippy> So, can I fix this by downgrading xCode to 11.7?  Will that create problems if I want to install on an iPod that has iOS 14?  (I have a gen6 with 12.4.7 and a gen7 with 14.0.)  I assume until whoever runs the Amplitude project updates the IPHONEOS_DEVELOPMENT_TARGET.

Is there a way to compile ResetTransmitter without having to compile the whole LoopWorkspace?  That also failed, on SwiftCharts-tvOS of all things.  (I have *no* idea why it's trying to compile for tvOS).

I have a  Dexcom G5 that I've "re-batteried" and am trying to figure out if it works at all (I don't have a software defined radio yet to sniff out whether it's transmitting directly).  The xDripSwift app doesn't pick up anything after an hour, although it’s not hooked up to a sensor that is actually on the body - I don’t know if that makes a difference.  (Could I just run a lead between the two contacts?)

Grrr..  When I get the G6 I'm definitely going to get the DexG5Rechargeable upgrade - assuming I am lucky enough to get two 80/81 series transmitters.  Or someone figures out how to hack 8G/H ones.  (%$^#-ing Dexcom/FDA meddlers who don't trust people with their own health.  [“Do only if you check BG obsessively"])

Here's my re-batterying job, which may or may not actually work.  I don't have a Dremel so went with an awl and hammer..  (I don't *really* need to G5 as I'm moving to a G6 and only have 3 sensors left so it doesn't make sense to send it off to the person who does it professionally - I assume Dexcom has ceased shipping G5 sensors in US as well as transmitters.  Anthem is being slow with the G6 prior auth.)  I managed to break the bottom contact in one of the battery wells on all of them, so I stuffed two batteries under a the single contact.  If it's designed so that the circuit can't take all 3V (rather than 1.5) for each battery's sub-circuit, then it's gone.

![DexG5-ReBatt](https://user-images.githubusercontent.com/22551894/95642474-bc823280-0a76-11eb-8538-22ff06fcc4d7.jpeg)

**Comment by NightScoutForSeb** [comment]
I was able to get past the error by building loop using the workspace method! No need to downgrade anything.


Hanna SandovalSent from Yahoo Mail for iPhone


On Friday, October 9, 2020, 6:56 PM, Jim Witte <notifications@github.com> wrote:




<warning: this post is a small/moderate/lot bit snippy> So, can I fix this by downgrading xCode to 11.7? Will that create problems if I want to install on an iPod that has iOS 14? (I have a gen6 with 12.4.7 and a gen7 with 14.0.) I assume until whoever runs the Amplitude project updates the IPHONEOS_DEVELOPMENT_TARGET.

Is there a way to compile ResetTransmitter without having to compile the whole LoopWorkspace? That also failed, on SwiftCharts-tvOS of all things. (I have no idea why it's trying to compile for tvOS).

I have a Dexcom G5 that I've "re-batteried" and am trying to figure out if it works at all (I don't have a software defined radio yet to sniff out whether it's transmitting directly). The xDripSwift app doesn't pick up anything after an hour, although it’s not hooked up to a sensor that is actually on the body - I don’t know if that makes a difference. (Could I just run a lead between the two contacts?)

Grrr.. When I get the G6 I'm definitely going to get the DexG5Rechargeable upgrade - assuming I am lucky enough to get two 80/81 series transmitters. Or someone figures out how to hack 8G/H ones. (%$^#-ing Dexcom/FDA meddlers who don't trust people with their own health. [“Do only if you check BG obsessively"])

Here's my re-batterying job, which may or may not actually work. I don't have a Dremel so went with an awl and hammer.. (I don't really need to G5 as I'm moving to a G6 and only have 3 sensors left so it doesn't make sense to send it off to the person who does it professionally - I assume Dexcom has ceased shipping G5 sensors in US as well as transmitters. Anthem is being slow with the G6 prior auth.) I managed to break the bottom contact in one of the battery wells on all of them, so I stuffed two batteries under a the single contact. If it's designed so that the circuit can't take all 3V (rather than 1.5) for each battery's sub-circuit, then it's gone.

**Comment by Kdisimone** [comment]
> <warning: this post is a small/moderate/lot bit snippy> So, can I fix this by downgrading xCode to 11.7? Will that create problems if I want to install on an iPod that has iOS 14? (I have a gen6 with 12.4.7 and a gen7 with 14.0.) I assume until whoever runs the Amplitude project updates the IPHONEOS_DEVELOPMENT_TARGET.
> 
> Is there a way to compile ResetTransmitter without having to compile the whole LoopWorkspace? That also failed, on SwiftCharts-tvOS of all things. (I have _no_ idea why it's trying to compile for tvOS).
> 
> I have a Dexcom G5 that I've "re-batteried" and am trying to figure out if it works at all (I don't have a software defined radio yet to sniff out whether it's transmitting directly). The xDripSwift app doesn't pick up anything after an hour, although it’s not hooked up to a sensor that is actually on the body - I don’t know if that makes a difference. (Could I just run a lead between the two contacts?)
> 
> Grrr.. When I get the G6 I'm definitely going to get the DexG5Rechargeable upgrade - assuming I am lucky enough to get two 80/81 series transmitters. Or someone figures out how to hack 8G/H ones. (%$^#-ing Dexcom/FDA meddlers who don't trust people with their own health. [“Do only if you check BG obsessively"])
> 
> Here's my re-batterying job, which may or may not actually work. I don't have a Dremel so went with an awl and hammer.. (I don't _really_ need to G5 as I'm moving to a G6 and only have 3 sensors left so it doesn't make sense to send it off to the person who does it professionally - I assume Dexcom has ceased shipping G5 sensors in US as well as transmitters. Anthem is being slow with the G6 prior auth.) I managed to break the bottom contact in one of the battery wells on all of them, so I stuffed two batteries under a the single contact. If it's designed so that the circuit can't take all 3V (rather than 1.5) for each battery's sub-circuit, then it's gone.
> 
> ![DexG5-ReBatt](https://user-images.githubusercontent.com/22551894/95642474-bc823280-0a76-11eb-8538-22ff06fcc4d7.jpeg)

Yeah, you're transmitter won't work like that.  Sorry.  It's gone

**Comment by davidivison** [comment]
> I was able to get past the error by building loop using the workspace method! No need to downgrade anything.

Could anyone give me some pointers about using the workspace method?  Thanks!

**Comment by kevinconroy** [comment]
I had this problem after upgrading to XCode 12.0.1. I believe the root cause has to do with the target iOS that Loop is using and XCode 12.0.1 changing the default settings.

In short, I got Loop 2.2.4 to build after changing my iOS deployment target to 13.6 on the main project settings as well as for each target with the option.

Additionally, I removed the watch app from my build and removed the iPad target as I don't own an Apple Watch or iPad and was only targeting our old iPhone SE v1. YMMV, but hopefully this works!

<img width="736" alt="Loop_xcodeproj" src="https://user-images.githubusercontent.com/1325888/95829158-e2703700-0d03-11eb-9d1f-6499c12ed747.png">
<img width="705" alt="Loop_xcodeproj" src="https://user-images.githubusercontent.com/1325888/95829230-fa47bb00-0d03-11eb-9c68-fa8206cbe110.png">

**Comment by rajid** [comment]
Having seen that this branch is actually archived, I started looking elsewhere to see if someone else was maintaining a Loop version which could read from Spike.  Finally, I ended up posting to the "Looped" Facebook group and was told about this branch:
    https://github.com/Andrei0105/Loop/branches
This seems to build with no problems, supports reading values from Spike, and has the Autobolus changes, so I'm now using this.

**Comment by rsilvers129** [comment]
I had this "Command PhaseScriptExecution failed with a nonzero exit code" issue when trying to build for my phone that is running iOS 14.2 Beta.

This is with both the Master branch, and the latest Dev.

First I tried with Xcode 12.01, and Loop built, but it would not install on the phone. I realized that I needed the latest Beta Xcode to install on a phone with 14.2. So I got 12.2 Beta 3, and that is when I got the endless PhaseScriptExecution errors when AmplitudeFramework was being built.

So then I tried the suggestion to change the target to IOS 13.6. That failed with the same error. Seems like what I nd to try next is this "Workspace Method," but not sure how to do that, and I doubt it will fix it.

**Comment by elnjensen** [comment]
Using a workspace to build Loop is documented here: https://loopkit.github.io/loopdocs/build/loopworkspace/

Not obvious that that will fix issues with building with beta iOS, though.

**Comment by SippingTheKoolaid** [comment]
Using Xcode 12.2 on Big Sur and encountered this issue.  Same error occurred when running _carthage update_ from Terminal. 

In an effort to enable a build, I removed all references to Amplitude from the Loop code and Cartfile.  The attempt to build resulted in the same error for the next framework that attempted to build with Carthage.  

I located this as an open issue that began with Xcode 12 beta, and it currently has a workaround: https://github.com/Carthage/Carthage/issues/3019

Following the workaround instructions, I completed running _carthage update_ with no errors.  

I updated the Loop program and edited the following:

In _Scripts/copy-frameworks.sh_, replace `carthage copy-frameworks` on the last line with:
`/{PathToYourLoopProgram}/carthage.sh copy-frameworks`

In _Loop.xcodeproj_, comment out this line, so you can recover if/when this is fixed:
`/usr/local/bin/carthage bootstrap --project-directory "$SRCROOT" --cache-builds`

add this one:
`/{PathToYourLoopProgram}/carthage.sh bootstrap --project-directory "$SRCROOT" --cache-builds`

Both _carthage update_ and my Loop build were successful after implementing the workaround.  

I hope this is beneficial for others experiencing this same issue.

**Comment by NightScoutForSeb** [comment]
This is not an issue with the auto bolus download from Oct 22 update. I built successfully yesterday 


Hanna SandovalSent from Yahoo Mail for iPhone


On Sunday, December 6, 2020, 9:31 PM, SippingTheKoolaid <notifications@github.com> wrote:




Using Xcode 12.2 on Big Sur and encountered this issue. Same error occurred when running carthage update from Terminal.

In an effort to enable a build, I removed all references to Amplitude from the Loop code and Cartfile. The attempt to build resulted in the same error for the next framework that attempted to build with Carthage.

I located this as an open issue that began with Xcode 12 beta, and it currently has a workaround: Carthage/Carthage#3019

Following the workaround instructions, I completed running carthage update with no errors.

I updated the Loop program and edited the following:

In Scripts/copy-frameworks.sh, replace carthage copy-frameworks on the last line with:
/{PathToYourLoopProgram}/carthage.sh copy-frameworks

In Loop.xcodeproj, comment out this line, so you can recover if/when this is fixed:
/usr/local/bin/carthage bootstrap --project-directory "$SRCROOT" --cache-builds

add this one:
/{PathToYourLoopProgram}/carthage.sh bootstrap --project-directory "$SRCROOT" --cache-builds

Both carthage update and my Loop build were successful after implementing the workaround.

I hope this is beneficial for others experiencing this same issue.

**Comment by elnjensen** [comment]
@SippingTheKoolaid The exact workaround you describe is already part of the Loop master branch; see ec7e952dbfa0b5edd8adef3541536e64ae1f2efb.    Did you use a fresh download?  Not sure why this didn’t work for you.

**Comment by SippingTheKoolaid** [comment]
I did not.  I was deploying the latest modified version supporting Spike integration published by @cyoung1024 (Thanks Caroline - great mod)

**Comment by cyoung1024** [comment]
@SippingTheKoolaid I no longer maintain the Spike branches, and have not since August. To update your branch please see https://github.com/Andrei0105/loop/tree/spike-master, which has the update that Eric is referencing.

**Comment by SippingTheKoolaid** [comment]
I wondered, since it was archived, but have been happy with the operation since my initial build back in December 2019 using your code, so figured August would be fine.  Again, thanks @cyoung1024 for the great work integrating Spike and the guidance on calibration.  I'll check out the latest update you and @elnjensen referenced.  I appreciate the additional guidance.

**Comment by dekimsey** [comment]
Did anyone get anywhere with this? I'm running into the same issue with the v2.2.6 branch (I've also tried master havinge noted the XCode 13 commit for rileylink). I'm using XCode 13.2.1 and OSX 11.6.2.

There is frustratingly little diagnostic information regarding what exactly failed.

```
** BUILD SUCCEEDED **

Build Failed
	Task failed with exit code 1:
	/usr/bin/xcrun lipo -create /Users/dkimsey/Library/Caches/org.carthage.CarthageKit/DerivedData/13.2.1_13C100/Amplitude-iOS/de32f16cf1d4d83002bafa31b0aab129b991f82b/Build/Intermediates.noindex/ArchiveIntermediates/Amplitude_iOS/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/Amplitude.framework/Amplitude /Users/dkimsey/Library/Caches/org.carthage.CarthageKit/DerivedData/13.2.1_13C100/Amplitude-iOS/de32f16cf1d4d83002bafa31b0aab129b991f82b/Build/Products/Release-iphonesimulator/Amplitude.framework/Amplitude -output /Users/dkimsey/Loop/Carthage/Build/iOS/Amplitude.framework/Amplitude

This usually indicates that project itself failed to compile.
```

**Comment by elnjensen** [comment]
I’d suggest (a) cleaning the build folder in Xcode and the (b) making sure you’re doing a Workspace build.  Non-workspace builds are known not to work any more, per the docs.

**Comment by dekimsey** [comment]
@elnjensen I think it's the change in the Workspace builds I missed that in the documentation. My last build, v2.2.4 (I think) build was out of Loop.git itself. I'm going to work on switching my build method. Unfortunately, I suspect I'll need to also apply the #1324 patch to support Archiving action, so it'll be a bit messy now with the submodules. Thank you very much for the pointer!
