### ISSUE TITLE
"Loop" is no longer available

### ISSUE THREAD

**Issue by swdoran** [LoopKit/Loop#1400]
woke up this morning and saw this message "Loop" is no longer available.  i have never had this happen?  do i need to remove and reinstall the app?  when i touch the app this message appears and the loop app will not even open up.

**Comment by loudestnoise** [comment]
Sounds like perhaps you have elapsed the 1 year time you're allowed to use a build assuming you have a paid Apple developer account. Solution in that case would be build again in Xcode.

**Comment by loudestnoise** [comment]
Also see this helpful page - https://loopkit.github.io/loopdocs/troubleshooting/loop-crashing/

**Comment by swdoran** [comment]
i just rebuilt loop a month ago and it was working fine for the last month; and then all of a sudden this message this morning.

**Comment by swdoran** [comment]
I just rebuilt loop a month ago and it was working fine and then all of a sudden this message this morning.


[cid:image002.png@01D5572F.459575C0]<http://www.galwaycompanies.com/>
Steve Doran
Galway Companies, Inc.<http://www.galwaycompanies.com/>
800 W Broadway, Suite 400 - Monona, WI 53713
P 608-327-4006 F 608-237-2117 C 608-347-6208
E sdoran@galwaycompanies.com<mailto:sdoran@galwaycompanies.com>

**Comment by loudestnoise** [comment]
- App Expiration
- Correction range set to reverse on < Loop 2.0 versions

are the two main reasons people see this behavior. If neither apply to you, it would suggest something else is going on with your app and perhaps your iPhone. Have you checked to make sure you're not out of storage on your phone?

**Comment by swdoran** [comment]
weird.  i wouldnt have changed the correction range but i cannot even open the loop app right now to check.  i just checked storage and only 12.9 of 64 GB is being used.

i am currently trying to rebuild the loop app to see if that works.  this is so weird.  i have never had any issues like this with loop...
![Loop is not available](https://user-images.githubusercontent.com/56494121/95218521-f70b7700-07b9-11eb-928b-e6996ffeb95e.jpg)

**Comment by swdoran** [comment]
just finished building loop and its still not working.  Got this message at the end of build.  i just updated xcode a month ago so i dont understand why this is popping up now.
![xcode failure](https://user-images.githubusercontent.com/56494121/95219297-d263cf00-07ba-11eb-8679-8a2798ca3501.jpg)

**Comment by loudestnoise** [comment]
You need Xcode 12 to build for iOS 14. Download the update from the Mac App Store and also get the latest Loop version from Github [here](https://github.com/LoopKit/Loop/archive/master.zip) as there were specific fixes you need to build for iOS 14.

**Comment by swdoran** [comment]
will do that right now.  Thanks....

still not sure why this all just stopped working last night when it was working just fine from a rebuild a month ago.

**Comment by loudestnoise** [comment]
Did you update to iOS 14 in the last month? Most people reported being able to continue to use Loop after update to iOS 14, but maybe that's isn't always true. I updated to iOS 14 and it kept working for me, but then I also decided to rebuild Loop with a new version and had to do the Xcode 12 and new version of Loop thing.

**Comment by hhinma** [comment]
Just a polite reminder folks,  general technical support should really be directed to the facebook group until something has been identified as a potential defect.

**Comment by swdoran** [comment]
sorry hhinma; i think thats what were trying to determine.  i will update all and then report if i have any further issues.  i am sorry for any inconvenience and appreciate the help.

**Comment by loudestnoise** [comment]
@hhinma 1) not everyone has Facebook and 2) you're not the boss. 

I volunteered my time to help @swdoran identify the issue and make a determination to the best of my knowledge if it was a "defect" of software or not. Had they responded that it was a regular 'ol troubleshooting issue my next step was going to be direct them to Zulip or Looped on FB. Sorry we didn't do it fast enough to your liking.

**Comment by Kdisimone** [comment]
Just FYI overall...@ps2 as well

iOS 14 updates are breaking many loops spontaneously with that same message as started this thread. 

It appears (based on the several people I've helped via teamviewer so I could dig a little deeper) that Apple has been expiring their certificates early. Very odd stuff. 

People have not been doing anything odd at all. Apple developer enrollment has current and paid. Builds and Rebuilds are well younger than 12 months. But shortly after having the iPhone update to iOS 14, the app is killed and certificates appear expired when I look at them in keychain. 

It isn't user error. It's an Apple thing. 

Rebuild fixes things though.

**Comment by swdoran** [comment]
Thanks Katie and David.  this seemed to be the issue.  i was able to download a new version of Xcode and then rebuild the app and all is working well again.  i hope someone else finds this chain useful because this was weird for sure.

**Comment by Kdisimone** [comment]
We've seen about a dozen reports of this over in Looped group over the last week or so. Definitely a strange issue and don't quite understand all the triggers that seem to be needed to have it happen...but iOS 14 seems to be the first trigger we know of. 

Glad to hear you're up and working again. I'll leave this open for a bit in case someone else sees same problem and isn't in looped. We have a pinned post for this in looped now.

**Comment by ps2** [comment]
The expiration date on a certificate cannot change once created. So these certificates must’ve already been set to expire at the time they did, when they were built into the app. What is the start date of these certificates?

**Comment by Kdisimone** [comment]
These people had certs for apps that were built in April and June...all within 2020. And developer accounts were auto renewal types and all had no lapses.

**Comment by Kdisimone** [comment]
The expiration date *should not* change. 

I previously would said the statement as you did so assuredly...except that these people built in 2020, have current developer accounts and yet their certificates are strangely expired when you investigate after they get a "loop app is not available" error.

**Comment by ps2** [comment]
I'm wondering about the dates on the certs specifically. I think there might be a way Apple can revoke a cert remotely, but it's not by changing the expiration date on the cert. Do you have any of these certs that appeared expired? Or a screenshot of the details of the cert?

**Comment by Kdisimone** [comment]
I have a couple...but not all captured when I was sure what I was looking to document at the time.

<img width="1392" alt="Screen Shot 2020-10-06 at 7 57 20 PM" src="https://user-images.githubusercontent.com/12402160/95283319-5dbb7f80-0810-11eb-9631-ed47b01665b4.png">

<img width="918" alt="Screen Shot 2020-10-02 at 11 57 36 AM" src="https://user-images.githubusercontent.com/12402160/95283351-762b9a00-0810-11eb-97bc-d50716f655aa.png">

**Comment by Kdisimone** [comment]
The process now is that we have to watch both the date of the certificate and the 12 months since build date...which used to not always be the case? that's what it is looking like

**Comment by Kdisimone** [comment]
(And all of these people got the error within a couple days of the update to iOS 14 on the Loop device)

**Comment by ps2** [comment]
If you double click on the certificate, you'll see the details. The "Not valid before" date is the date the certificate was created.  I'm guessing those are valid dates for the first time Xcode created their developer cert. I believe what is happening is that the developer cert used to sign the app expired. Developer certs can be created at any time when you have a valid developer license, and they last for one year.  So If you bought a developer license on Oct 6 2019, and created a developer certificate that day, it would expire Oct 6, 2020, and any apps created with that certificate would no longer load after Oct 6, 2020. 

The part that might be seeming to conflict with past experience is that you could create a new developer certificate at any point, and it wouldn't expire for a year. So even with your developer license that you bought on Oct 6, 2019, you could create a new developer certificate in Aug 2020, and it would be valid until Aug 2021, even though your developer *license* expires Oct 6, 2020.

Xcode has gotten better over the years with automatically managing certificates, and I think creation of new developer certificates has decreased; In the past we'd often create a new developer certificate for some signing problem, so as we re-built loop, the expiration date would often be pushed out later than the expiration date of our license. That is probably happening less for some users now, and they're seeing this error happen at their developer cert expiration, even though they built more recently. Does that make sense and explain what you've seen?

**Comment by ps2** [comment]
This might point to a new recommendation to have people update their development certificate when they build a new version of Loop.

**Comment by Kdisimone** [comment]
Yes, that would comport with exactly what I've seen so far (to the best that people can remember their build dates and such).  I might be a good guinea pig for this myself as I haven't built anything since a bit before my license renewed on Sept 22nd. I can dig into my own info and see what certs I have.

**Comment by Kdisimone** [comment]
So here's what I see in my own data....

My Apple Dev Certificate was issued Sept 20, 2019.
Apple License renewed September 22, 2019.
Loop app built on April 2, 2020.
Apple Dev certificate expired Sept 19, 2020.
My Developer License auto-renewed on Sept 22, 2020.

On October 2, 2020, I opened a new loop project in Xcode (but did not build...just signed). Looks like that was when/how a new Apple Dev Certificate was issued.

<img width="1512" alt="Screen Shot 2020-10-06 at 9 45 13 PM" src="https://user-images.githubusercontent.com/12402160/95290649-98c6ae80-0822-11eb-9bb1-c9c846ca9102.png">

I'd bet, under this new paradigm, if I had tried to open Loop app between Sept 22, 2020 and Oct 2, 2020 that it would have failed to open.  

I guess I can edit Loopdocs to have people manually add a new Apple Dev cert at updates (or to at least check date if they are a very frequent updater). Using Xcode preferences would be the easiest way for most people to do this intuitively.

**Comment by Kdisimone** [comment]
The Xcode 11 theory might make sense too...might not necessarily be an ios 14 issue then? Perhaps more likely that we are just seeing the lag time for when they rolled this new way of dealing with things out back then.  Took a year for the situation to start appearing.  Xcode 11 was publicly released on September 20, 2019. This is looking like the timing lines up with that. Sept 20th is probably when we started getting first reports. iOS 14 released on September 16, 2020...so perhaps a red herring coincidence.

**Comment by ps2** [comment]
I don't think this is new behavior. We have certainly seen people report Loop not launching suddenly, and rebuilding fix it for them. I think we just happened to have a lot of people who created development certs around this time last year.

**Comment by ps2** [comment]
It'd be nice if we could build in the cert expire date so Loop knows and can warn when it approaches. I think that's possible, but would take some work.

**Comment by ps2** [comment]
setting EXPANDED_CODE_SIGN_IDENTITY_NAME holds the cert name

In an xcode build script, we could extract the expiry from the cert using this:
security find-certificate -a -p -c ${EXPANDED_CODE_SIGN_IDENTITY_NAME} | openssl x509 -text -noout | grep "Not After"

Only problem is that you can have multiple certs with the same name. I think Xcode is smart enough to use the most recent one for signing. Xcode also includes the signing cert identity in EXPANDED_CODE_SIGN_IDENTITY, but I don't know how to look that up via command line. 

Just saving these notes here for possible future use in a build script that can store the cert expiry in Loop and warn users.

**Comment by Kdisimone** [comment]
> I don't think this is new behavior. We have certainly seen people report Loop not launching suddenly, and rebuilding fix it for them. I think we just happened to have a lot of people who created development certs around this time last year.

We actually haven't seen this particular error much at all. The white screen blip and then loop not launching...yes we see that a fair bit.  But the "Loop app not available" is very rarely seen. The only times I've seen it before was when people accidentally revoked certificates or had used someone else's certificate that they then let lapse. 

This is a rash of people reporting it now suddenly. Definitely an abnormal spike. And not from people who are new. Many have been long time loopers too. So odd. 

Would be great if we could pop a warning up for a rebuild date warning? Could that (the dev cert date) be harvested at build time?

**Comment by Kdisimone** [comment]
How about from provisioning profile? That is always the same expiration date as the dev cert expiration

**Comment by Kdisimone** [comment]
And yes, I can confirm Xcode uses the most current dev cert if two exist. I tested that earlier in the night and it picks the more current.

**Comment by ps2** [comment]
> Would be great if we could pop a warning up for a rebuild date warning? Could that (the dev cert date) be harvested at build time?

Yeah, that's what I was looking into above.  Provisioning profile id is also set as EXPANDED_PROVISIONING_PROFILE.

**Comment by Kdisimone** [comment]
> > Would be great if we could pop a warning up for a rebuild date warning? Could that (the dev cert date) be harvested at build time?
> 
> Yeah, that's what I was looking into above. Provisioning profile id is also set as EXPANDED_PROVISIONING_PROFILE.

Yes, sorry. Crossposted there 🤣

**Comment by ps2** [comment]
I think this works: would need to package it up.

`security cms -D -i ${EXPANDED_PROVISIONING_PROFILE} | plutil -p - | grep ExpirationDate`

**Comment by ps2** [comment]
Not an alert yet, but recorded in the build, and included in the issue report: https://github.com/LoopKit/Loop/commit/4c5b912e2475e5ff83a64db6781c82a8a21bcb56

**Comment by jonfawcett** [comment]
I think we might be confusing signing certificate expirations with provisioning profile expirations. This is different with other distribution methods (ad-hoc, App Store, etc), but with apps built directly to provisioned devices the certificate expiration should only affect the ability to sign and build but not affect already installed apps (at least with auto-renew...not sure if it's different without auto-renew dev account). There is the possibility that Apple has changed this policy recently, but if they have I can't find any record of it online. From testing a bunch of different app builds this week, I think that Xcode is just not generating new provisioning profiles as frequently. So if a provisioning profile is 2 months old, it might rebuild using the same one and you are only going to get 10 months until expiry. I haven't yet figured out what the trigger is now for Xcode to generate a new profile, but you can manually force it. I think we maybe should add this to the loopdocs rebuild instructions. The simple steps:
1. Open terminal and type: rm [space]
2. On the Xcode signing page click the (i) next to Xcode managed profile. This will show the expiry date if you build right now
3. To force the expiration to update, drag the icon from the popup into terminal and hit enter
4. That deletes the profile and will force Xcode to immediately generate a new one that expires 12 months from today
5. build

**Comment by Kdisimone** [comment]
>  a provisioning profile is 2 months old, it might rebuild using the same one and you are only going to get 10 months until expiry. I haven't yet figured out what the trigger is now for Xcode to generate a new profile, but you can manually force it. 

Xcode (now) only generates a new profile if the Apple Developer Certificate has been updated. (Assuming we are using same bundle ID and development team of course). So yes, provisioning profile will (now) have an expiration date that matches the Apple Dev Cert expiration date. 

If you create an updated Apple Dev cert, new profiles will be created because Xcode will provision profile with the most current Apple dev cert. 

I don't see how this is "confusing certs and profiles" in our discussion above. I don't think we have confused them. 

But regardless of exact cause...*something* has changed on apples end and we will need to adapt. There is zero chance we went four years operating with Loopdocs and build process as they've been, and didn't get reports like we've had this last two week. 

The expiration being captured within Loop app will help a ton so people can double check and plan to avoid downtime unexpectedly now. 

Loopdocs will be revised to reflect new need to check dev cert and how to issue new ones. 

We will however now have a new set of users who accidentally revoke their existing certs because they will not follow directions.  No matter how clearly the directions say to leave existing ones in place.

**Comment by Kdisimone** [comment]
And the easier way to do this (as opposed to using terminal and dragging) is to just use Xcode preferences and "manage certificates" to add a new Apple Dev cert. on the machine. Xcode will create new provisioning profile automatically with that new date associated with new Apple dev cert.

**Comment by jonfawcett** [comment]
Your steps of generating a new signing certificate do force a new provisioning profile and is maybe slightly simpler for the average user. But I fear there could be long-term hassles cleaning up keychain and other areas since certificates are not really intended to be created every time you re-build. Since only a new provisioning profile is needed and they don't need a new certificate to create this, I think we should give instructions on how to create the profile rather than create new certificates every build.

Phrased slightly different: we shouldn't encourage bad habits (generating certificates when not needed) just because it is slightly simpler. Especially when we already know anytime people have to start digging into keychain, they usually need a technical person's assistance.

**Comment by Kdisimone** [comment]
@jonfawcett Your way would produce 12 month profiles, but with "less than 12 month remaining certificates". And your way would require deleting four provisioning profiles (there's one for each target).  Both issues make that less than ideal

**Comment by jonfawcett** [comment]
@Kdisimone A signing certificate expiration does not require the app to be rebuilt, so that is an apples to oranges comparison. It doesn’t matter if the cert expires in 1 day if the provisioning profile lasts 12 months. The app does not need rebuilt until the provisioning profile expires (Per my earlier comment about auto-renewal). Making new certs is still providing people a bad habit that is not how Apple intended certificates to be used which has a risk for complicating things immensely later if they have certificate issues.

**Comment by Kdisimone** [comment]
@jonfawcett What I have seen in recent failures does not comport with what you are saying though. So.....while I'd love to agree....

**Comment by jonfawcett** [comment]
I’m still trying to find solid data from people but haven’t seen anyone yet that didn’t fit that description. Are you saying that you’ve helped people with this issue where the profile on the device was not expired (before attempting a rebuild) but the certificate was expired? And if so, there wasn’t another cause such as non-renewed dev account, needed to accept new terms, etc?

**Comment by jonfawcett** [comment]
That would make this change by Apple even more troubling. Maybe just another crackdown...prevent people skipping every other year of renewals.

**Comment by jonfawcett** [comment]
FYI... I forgot to mention earlier but just saw a comment about Spike on Fb. You can simply run rm -rf on the provision folder to clear all profiles at once and force Xcode to recreate them. So clearing them could be as simple as a double click script file that we tell users to do before each build

**Comment by Kdisimone** [comment]
> FYI... I forgot to mention earlier but just saw a comment about Spike on Fb. You can simply run rm -rf on the provision folder to clear all profiles at once and force Xcode to recreate them. So clearing them could be as simple as a double click script file that we tell users to do before each build

That would be a better way. Then it can be a copy/paste single line command. The drag and drop icon method resulted a couple times in profile deleting, but not regenerating until Xcode rebooted...so that method would be a support nightmare as it would be hard for an average user to notice the difference of a success/failed regeneration.

**Comment by jonfawcett** [comment]
This method might require xcode be restarted also. We could make it a script in the loop download that removes the profiles then launches loop in xcode. So the instructions instead of opening Loop in xcode would just be to run the script. The delete command is below if you want to try it

rm ~/Library/MobileDevice/Provisioning\ Profiles/*.mobileprovision

**Comment by jonfawcett** [comment]
I used Automator to script this if anyone wants to try it out. You can download the file from the commit below. @ps2 I didn't want to send a PR without discussing first since it's a binary file. My thinking was that this could be part of the loop repo so everyone has it. This would replace the "open loop in Xcode" from step 14 of build.

1. put the file in your Loop root folder
2. double click the app
3. It first will delete the provisioning profiles on your computer
4. since Xcode usually needs restarted if you delete those, I made it then detect if the download is workspace or project and then open Xcode with the appropriate Loop file.

If you want to see the code or play around with it, drag the icon onto the Automator app in your applications folder. You can make changes and save to update the app

https://github.com/jonfawcett/Loop/commit/ae930706b484fe060c79f02a84653e2dd9fc6556

**Comment by Kdisimone** [comment]
Loopdocs page for Updating Loop has been revised to reflect the new step.

**Comment by dabear** [comment]
It's also possible to get the expiration date dynamically (rather than at build time). I see @ps2 now included some code to take the certificate from the mac during building. If we want this dynamically instead, I can have a go at porting this code to from objective-c to swift:
https://github.com/SpikeApp/Spike/blob/a3763f114f9a282628f874a3d6399c5a6cb43033/Native%20Extension/iOS/NativeExtensioniOS/NativeExtensioniOS/NativeExtensioniOS.m#L516

Let me know, or else I'll just leave it

**Comment by 4gra** [comment]
> It's also possible to get the expiration date dynamically (rather than at build time). I see @ps2 now included 
> some code to take the certificate from the mac during building. If we want this dynamically instead, I can have
> a go at porting this code to from objective-c to swift:
> 
>https://github.com/SpikeApp/Spike/blob/a3763f114f9a282628f874a3d6399c5a6cb43033/Native%20Extension/iOS/NativeExtensioniOS/NativeExtensioniOS/NativeExtensioniOS.m#L516

@dabear This looks extremely valuable to me. Expiry could be a serious business, not everyone can find a Mac quickly to rebuild. Actually I think it warrants a notification/alert if expiry is close, since it's a predictable thing that would obviously stop loop working. I see that this functionality has made it to LoopFollow using a "MobileProvision" library, which might speed up the task.

**Comment by joebroad1** [comment]
Loop app is no longer available. What do j need to do to get it working again.

**Comment by blakekirven** [comment]
Read the documents, it's in there

It's time to rebuild the app

**Comment by joebroad1** [comment]
Thanks.

**Comment by marionbarker** [comment]
First off - thank you for connecting to an existing issue instead of opening a new one.
However, this is all covered in LoopDocs and there you will find pointers to places to get help.
(Typically this location is for reporting problems with the code - not to get help). This issue was started when Xcode stopped automatically supplying new year-long builds every time you rebuilt and that surprised a bunch of people - that is all covered in LoopDocs now.

Yes - you can build from any mac that has the correct operating system and the correct version of Xcode for the version of iOS on the phone on which you plan to build Loop. (Version requirements are covered in LoopDocs).
You will need to have the user name (email address) and password for the Apple Developer's ID.  Best if you use the same one as last time - otherwise you'll have to set up a new app and a new pod (if you are using pods). You can build a free-version but that has to be rebuilt every 7 days (yes - covered in LoopDocs).

Please start here and follow links as needed.
* https://loopkit.github.io/loopdocs/build/updating/

If this is the first time you've built the app yourself, you may need some hand-holding.  There are volunteers on Facebook who can assist.

Please read the how-to search section:
* https://loopkit.github.io/loopdocs/#how-to-search

And the how-to get help section:
* https://loopkit.github.io/loopdocs/#stay-in-the-loop
