### ISSUE TITLE
Flashing "loading"-icon in the carb entry view.

### ISSUE THREAD

**Issue by cfaagaard** [LoopKit/Loop#1408]
**Describe the bug**
In the carb-entry there is a flashing "loading"-icon.
My first impress was that Loop was still calculating "recommened bolus" and waited... and waited...

**To Reproduce**
1. From the main view click on "Carb entry"-icon
2. Enter a carb
3. click continue

To the left of the "Recommened Bolus"-number there is a flashing "loading"-icon. It keeps flashing.
In the screenshot below it is just the left of the number "0.4".
A user could think that loop is still calculating something and waits.....
I think it is because the view "monitors" any change in the bolus-calculation-parameters, in order to warn the user if they change.

**Expected behavior**
I would expect there should be no flashing load-icon.

**Screenshots**
![Simulator Screen Shot - iPhone 11 - 2020-10-10 at 11 05 16](https://user-images.githubusercontent.com/25353502/95651151-89788700-0ae8-11eb-973f-f8cf5480b73b.png)

**Phone**
 - Hardware: Macbook - using the simulator via xcode build
 - OS Version: "14"

**Loop Version**
 - Version Number: 2.3.0.57
 - Repo: dev-branch

**CGM**
 - Device: Simulator

**Pump**
 - Manufacturer: Simulator

**Comment by mylma** [comment]
Agree! The first impression is that Loop is doing something and I should wait. A rotating animation is used to symbolise a progressing process. Also flashing behaviour is distracting. Maybe this is not intentional (perhaps only a simulator related bug?) and the rotating animation should be visible only when the bolus recommendation updates.

**Comment by cfaagaard** [comment]
Fixed
