### ISSUE TITLE
An omnipod lost the connection to the RL completely.

### ISSUE THREAD

**Issue by hpc4fun** [LoopKit/Loop#1476]
**Describe the bug**

Loop/RL lost a pod in action (first time we have seen this since we switched to omnipod
with loop in May 2019) and a new had to be activated. The issue seem similar to a PDM
scream issue with the difference being that the PDM warns the user that the pod is suddenly
dead and must be replaced in order to resume insulin delivery.

Communication to the omnipod died suddenly after 2 days of wear (activated at 2021-01-23 17:16
and last communication to pod was at 2021-01-25 00:19). The last communication to the pod was a
manual suspend while loop was running in openloop mode. Loop did not seem to recognize
that the pod was dead and did not instruct the user to active a new pod in order to
resume insulin delivery.

We confirmed that that loop itself and the RL were able communicate but there was no
sign of communication to the silent (no beeps, no screaming) pod. I tried the usual trick of
moving RL and pod closer and in different position but nothing helped. Eventually I power-booted
the RL and the phone was booted too. No change. Phone and RL were again able to communicate with
each other but alas no sign of communication between the RL and the pod. I also tried
other commands than resume: read pod status, play test sound, read pulse log,...... but again
no sign of communication between RL and the pod. Eventually I gave up and not surprisingly I
also failed to deactivate the pod (this situation is one that I also recall from the PDM days
but I have never seen it with loop before and have been running loop with omnipod since May 2019)
so after giving up loop allowed me to start over with a new pod. I have attached the log and
one notes that the resume is classified as unsafe.

Solution: Pod is dead, loop did not catch the event to a stage where it was able to conclude
that the pod communication is dead and that the pod will have to be substituted.

**Wish1:** Would be fantastic if the user was warned that the pod is indeed dead and communication cannot
continue and guide the user to activate a new pod. I'm not sure if the pod have given any sign of
"illness" that loop could have treated to reach this conclusion or if the RL and the pod have gotten
out of sync somehow and the lack of visible communication is hidden by nonce issue or .... Alternatively,
one could count the number of tries and warn the user upon a reasonable threshold value that
the pod might be dead. I have done pod-pdm captures with my RTL sdr in the past but admitted in the
middle of the night my focus was not to find my antenna and software but to get the problem resolved and
to have the insulin delivery reactivated.

**Wish2:** I noticed that loop could see TWO RL in the list of devices (yes, there were two active RLs in
the house when the issue occurred) and wonder if the other RL could have contributed to communication
noise. I would appreciate if one could specify whitelisting/blacklisting of RLs in loop to force the
phone to disregard all other active RL devices (I see options for confusion here, e.g. what happens
if both are toggled on or if the wrong RL is toggled on and the proper togged off during the lifespan
of a pod). These options for confusion could maybe be prevented with on option for whitelisting devices
(or even hard-coded this in the build of the loop app but not sure where the ID for the RL is to be found
in the code)

The issue report is attached.

**Phone**
 - Hardware: SE 2020
 - OS Version: ios 14.3

LoopVersion
Version: Loop v2.2.4
gitRevision: 26b11d72399b99677423b176d5cf1826dedb8def

CGM
Device: Dexcom G6

Pump
Manufacturer: Omnipod
Model: Eros

**Additional context**

We have had screaming pods on loop (but the number of screaming
pods with loop has been significantly less than what we have observed on the PDM in the past).
At the time when we were still on the old PDM we have had pod stops due to the PDM, i.e.
we have had issues both on the POD side (pod starts to scream) and on the PDM side
(PDM starts to scream) and combined (both pod and PDM agrees to terminate the delivery and
start to scream together - yacc!). All these situations will require a POD shift and one will
have to deactive the pod in these cases and activate a new. In some cases, deactivation isn't isn't possible
and one will simply have to activate a new pod.

This observation where loop/RL completely looses the possibility to communicate to the
POD look like some of PDM errors that I recall where the communication to the active
(AND SILENT) pod was dead and the PDM was the only one that was "screaming". I can dig
out some of the error codes that I have seen in these cases in case that will be useful.

Finally, it should be mentioned that there were two RLs in the house when this event
occured. The phone attached to the failed pod showed both RLs in the menu of devices.

**Comment by hpc4fun** [comment]
Sorry forgot the loop report
[Loop_Report_2021-01-25.md.gz](https://github.com/LoopKit/Loop/files/5897999/Loop_Report_2021-01-25.md.gz)

**Comment by marionbarker** [comment]
I took a quick look - I want to bring Joe Moran into this.  Are you on zulipchat?  That's a better place for this.
It looks like a Deactivate Pod message was sent from Loop to the Pod at 1/25/2021 0:21 (UTC).  
Normally a response comes back from the pod immediately.  
This was not seen by the message log. 
But clearly the Pod got the message because it stopped responding.  
This is typical behavior for a pod that has been deactivated.

Are you sure you did not accidentally deactivate the pod?

2021-01-25 00:21:11 +0000 Omnipod 1F00E870 send 1f00e8701c061c042c9b87770073
  >> this is the Deactivate Pod command
2021-01-25 00:26:50 >> sent from Loop to Pod; 'RequestStatus'
  >> many more messages from Loop to Pod;
2021-01-25 00:58:00
  >> last message in the log file (send from Loop to Pod)

**Comment by marionbarker** [comment]
I started a stream in zulipchat.  If you are a member there, make sure you subscribe to the Omnipod_Users channel.
https://loop.zulipchat.com/#narrow/stream/144615-omnipod_users/topic/Deactivated.20Pod/near/224613106

**Comment by itsmojo** [comment]
From a quick look at the communications log the "Suspend Delivery" (Cancel All) command with confirmation beep was done at 2021-01-25 00:19:41 UTC was successful from the returned response at 2021-01-25 00:19:43 UTC. There was also another successful duplicate Suspend Delivery done immediately after this at 2021-01-25 00:19:43 UTC. I suspect that the UI just didn't update quickly enough on the original suspend attempt leading to a duplicate user attempt.

87 seconds later at 2021-01-25 00:21:11 UTC a Deactivate Pod command was issued with no response visible and no future responses from the pod. All of the no responses seen after the deactivation is probably due to the deactivated pod, but the commands being issued by Loop indicates that Loop still believes that the pod is activated. Since the only way to get this command sent is with the "Remove Pod" pod command, I'm guessing that this was accidentally done, confirmed and then quickly cancelled after the deactivate pod command was sent by Loop, but before the response was seen. This sequence could result in no response being logged for the deactivate pod pod response and Loop believing that the Pod is still active when in fact it has been deactivated.

Loop needs to have beefed up to correctly handle a cancel in the middle of a deactivate pod command that the pod may or may not have received.

**Comment by hpc4fun** [comment]
@marionbarker, @itsmojo - THANK you so much for your feedback. A deactivation cmd
does indeed explain why the ability to communicate was gone. I cannot explain how 
it got deactivated as I don't recall having pressed this. Moreover it would even 
require that I acknowledge this operation which makes it a even bigger mystery to 
me. Having said that I was half asleep when I grabbed the phone so its not impossible
and I trust the log more than I trust myself while sleeping. 

I will join you at zulip and we can discuss what we could do to make it more apparent
to loop and the user that the pod is gone and a new has to be inserted and activated.
