### ISSUE TITLE
Outside Insulin from HealthKit not used when calculating coverage for carbs?

### ISSUE THREAD

**Issue by Hectopus** [LoopKit/Loop#1506]
I’m on  AutoBolus V2.2.4.   IOS 14.4.2
My Pump is getting a little low on insulin and I’m about to board a plane. So in order to be conservative with the reservoir I thought I would Bolus with a syringe and record directly into Apple Health.  Luckily I tested this before actually injecting. 
Health recorded it OK. Loop showed the insulin on the top level display but then when I input the carbs into Loop. It suggested I give myself the full bolus that it already showed I had just gotten.  So this is unexpected to me. I would have thought that loop would count that bolus and active insulin and seen that no more insulin was needed. Instead loop just ignored the insulin bolus from
Health for determining any bolus recommendation.  
Any thoughts or ideas?   

I ended up just deleting the health bolus (which I neVer actually injected) and then going straight through loop as you would normally.

FYI
I have subsequently tried and failed to replicate this issue where Loop shows a bolus from Healthkit but does not use that IOB info towards a bolus calc. This makes me think that my own user error was probably at the root of this.

**Comment by novalegra** [comment]
Hi @Hectopus! I know you're not on dev, but for anyone else reading this, you can now add outside insulin directly in Loop by tapping on the insulin delivery chart. Logging it within the app instead of within HealthKit ensures it will always be used for calculations and that the correct insulin model is associated with the outside dose
