### ISSUE TITLE
Loop watch app does not work for me with dev branch, works fine with master

### ISSUE THREAD

**Issue by hpc4fun** [LoopKit/Loop#1517]
**Describe the bug**
The loop watch app does not work for me with when building the dev branch. It works fine for the master branch.

**To Reproduce**
Build latest loop and try to launch the loop watch app. It flickers shortly trying to launch and then exits.

**Expected behavior**
I expect that the loop watch app works like it does in the latest released version of loop, i.e. that one can launch it and interact with it.

**Loop Version**
 - Version Number: 2.3.0 (57)
 - Repo: Latest dev, cf. LoopKit/LoopWorkspace (453ee6a)
 - IOS 14.7
 - watch os: 7.6

**Comment by blameitonben** [comment]
Have you tried uninstalling the watch app via the Apple Watch app, the. Reinstalling?

I have 3 separate phones and watches running the latest workspace build all with not issues on the watch app.

Attempt an uninstall/reinstall.

Also make sure you’ve signed the watch app prior to building in Xcode.

You may also need to reset your watch to factory and recover it from a backup then rebuild the entire app.

Ben
________________________________
From: hpc4fun ***@***.***>
Sent: Monday, July 26, 2021 3:22:40 AM
To: LoopKit/Loop ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LoopKit/Loop] Loop watch app does not work for me with dev branch, works fine with master (#1517)


Describe the bug
The loop watch app does not work for me with when building the dev branch. It works fine for the master branch.

To Reproduce
Build latest loop and try to launch the loop watch app. It flickers shortly trying to launch and then exits.

Expected behavior
I expect that the loop watch app works like it does in the latest released version of loop, i.e. that one can launch it and interact with it.

Loop Version

  *   Version Number: 2.3.0 (57)
  *   Repo: Latest dev, cf. LoopKit/LoopWorkspace (453ee6a)
  *   IOS 14.7
  *   watch os: 7.6

**Comment by hpc4fun** [comment]
@blameitonben Thank you so much for your feedback. Yes, tried uninstalling and then reinstall and yes I also signed the watch app. Your last hint pointed me to solution. I didn't have to reset to factory settings but I apparently had to reset sync. data and after that a reinstall worked out of the box. I guess there could be some static left-overs when moving back and forth between dev and master that may trigger these issues. Thanks for pointing me to a solution! Will close the issue now.
