### ISSUE TITLE
30 day warning to Loop app expiring

### ISSUE THREAD

**Issue by mkitchingh** [LoopKit/Loop#1527]
Our most common question in the FB forum relates to people having no idea what to do when they get the message "Loop is no longer available". I realize this is troubling, because it means the user hasn't read a lot of documentation, but it still happens, a lot. 
Would it be possible to have a pop-up occur (daily maybe?) starting 30 days before their app expires? Just a thought.

**Comment by marionbarker** [comment]
Pete has already extracted the profile expiration date in branch loop-release/v2.2.5 (being tested as next release) and agreed on zulipchat to add a notification to 2.2.5. (If you are testing v2.2.5, check the Loop Version section when you tap Issue Report - near top of the report).

Tim Street posted in FB in the Looped Group to discuss this.
Here's the link if you want to read the full discussion.  
* https://www.facebook.com/groups/TheLoopedGroup/permalink/2922208887995758/

I summarized the suggestions/comments from that post below. The title of this Issue is "30 day warning" so we have a range of suggestions: 
* first notification:  30 days, 2 weeks, 5 days
* frequency of notification: 
  * increasing frequency depending on how close expiration is
  * once a day
  * every time the app opens


Tim Street:
* When the app gets to 360 days old an announcement pops up saying "Your loop will need to be rebuilt in 5 days" every time the app is opened

Kris Lyon:
* I make an event on my calendar with reminders at a week before, 2 days before and a day before at a scheduled time when I’m normally free

Chad Russell:
* Set a Calendar reminder for 11.5 months

Peter van Rijt:
* . . . text message on Loop main screen, say 2 weeks before expiring, with a link to LoopDocs there won't be panic

Marion Barker in zulipchat:
* Can you notify users once a day that the Loop app will expire on their expiration day starting two weeks ahead with a message to refer to LoopDocs for updating instructions

**Comment by marionbarker** [comment]
This can be closed with release of Loop v2.2.5

**Comment by mkitchingh** [comment]
Thanks!!!!!
