### ISSUE TITLE
Unable to build 2.2.6 from build script

### ISSUE THREAD

**Issue by agoldh20** [LoopKit/Loop#1554]
**Describe the bug**
When trying to build in xcode, I get an error and a build failure.

```/Downloads/BuildLoop/Loop-Master-211004-1908/LoopWorkspace/Loop/Carthage/Checkouts/rileylink_ios/RileyLinkBLEKit/RileyLinkDevice.swift:430:15: initializer for conditional binding must have Optional type, not 'CBService'```

**Screenshots**
![image](https://user-images.githubusercontent.com/31190314/135960956-988802ee-0027-4dd7-9cfc-604f8833b58e.png)

![image](https://user-images.githubusercontent.com/31190314/135961041-b07be28c-b24a-4859-b4de-46ad7d337b70.png)

**Phone**
 - Hardware: iPhone 8
 - OS Version: iOS 14.6

**Loop Version**
 - Version Number: 2.2.6

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod

**Comment by chrigabr** [comment]
I have the same error with iPhone XS and iOS 14.8.

**Comment by marionbarker** [comment]
That's quite odd.  
* The error message you referenced comes from trying to build from a zip-download.
* If you failed to select Loop (Workspace) and build, you'd get messages under Cartfile with Command PhaseScriptExecution failed message.
* Can you post a full screen shot (all of xcode screen)

**Comment by marionbarker** [comment]
Note - this kind of error is better fixed via zulipchat or facebook. It is almost never a problem with the code when the code has been out for a while. Plus - you need to follow the directions for posting for build help.
* https://loopkit.github.io/loopdocs/build/build_errors/#posting-for-help

**Comment by agoldh20** [comment]
Xcode version: 12.5.1
macOS: 11.6

![image](https://user-images.githubusercontent.com/31190314/136032234-9935650e-ce5c-4e22-9e8f-c5b13670b70b.png)

**Comment by agoldh20** [comment]
https://loop.zulipchat.com/#narrow/stream/144111-general/topic/Build.20failure.3A.20initializer.20for.20conditional.20binding

I just found this link so hopefully when my son gets home from school this will fix my issue.  Thanks @marionbarker for pointing me towards zulip!

**Comment by marionbarker** [comment]
If this works, you can close the Issue.  (It will still be on github but filed under Closed instead of Open.) Hope to see you over at zulipchat in the future.

For Workspace build (required for Xcode 13): Be sure to read all of step 14, but here's the direct link to summary graphic and steps needed to complete the build.
* https://loopkit.github.io/loopdocs/build/step14/#wait-for-xcode-to-finish-indexing

For zip download build (still available for Xcode 12): Read this section - you have to modify a file before it will build.  And it is much slower than workspace build method.
* https://loopkit.github.io/loopdocs/build/step14-zip/#from-zip-download-version-of-step-13

**Comment by agoldh20** [comment]
Issue was user error indeed. I saw to choose loop(workspace) in at least 3 places and I still managed to chose loop. Closing issue...thanks for the help!!!!!!
