### ISSUE TITLE
Apple Watch series 7 does not display Loop dev info or Dexcom 6 values.

### ISSUE THREAD

**Issue by Trpl7ca** [LoopKit/Loop#1564]
Watch face does not display Dexcom values, only shows two -- marks.  if dash marks are touched it will show normal Dexcom displays.

The Loop symbol is blank now after rebuilding but was showing glucose value. When glucose value is touched, it brings up normal display but you are not able to enter carbs or bolus. You can enter pre meal and any other overrides. When carb or bolus is touched program returns to watch face. The Loop Dev version builds to the phone normally, but the watch app and the Dexcom app are not working.
I followed the procedure in L and L for version updates, rebuilt several times, restarted phone and watch several times, deleted loop and dev from watch and re installed. Unpaired and repaired watch/
[Loop Report 2021-10-30 14:10:14-07:00.md](https://github.com/LoopKit/Loop/files/7447612/Loop.Report.2021-10-30.14.10.14-07.00.md)

I then went back to my series 5 watch and paired it with my new phone, rebuilt using same file, software versions and both Loop and Dexcom work correctly. I guess you can assume the problem is with the code to the new series watch but I am not a programmer so just guessing.

**To Reproduce**
Built current version of dev to a Apple Watch series 7
Neither Loop or Dexcom will display correctly

**Expected behavior**
Normal displays with the ability to add carbs and bolus.
**Screenshots**
<img width="1401" alt="Screen Shot 2021-10-30 at 2 00 03 PM" src="https://user-images.githubusercontent.com/52380252/139558860-f9f8deec-2505-4cc6-bb0c-fab220410262.png">

**Phone**
 - Hardware: Iphone 13 pro
 - OS Version: IOS 15.1, Monterey 12.0.1, Xcode 13.1

**Loop Version**
 - Version Number: dev 2.3.0
 - Repo: LoopWorkapace dev

**CGM**
 - Device:  Dexcom G6
 - Manager app:  Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**
The screen shot is Xcode debugging info while running loop and attempting to enter carbs from the watch. It would just close the app and return to watch face.

**Comment by Trpl7ca** [comment]
![incoming-7F10D6E6-B396-441B-911E-83295A20E8BA](https://user-images.githubusercontent.com/52380252/139559847-c0a3baa2-bad0-45b5-ae95-63cf1e9fc667.PNG)

**Comment by ryandellolio** [comment]
I believe these two issues are unrelated.  

1) Dexcom "Check app on iPhone" and watch complication error

See this thread on MacRumors regarding Dexcom and the Apple Watch Series 7 complication not functioning:  https://forums.macrumors.com/threads/dexcom-g6-app-crashing-not-working-on-aw-series-7.2317166/ Many others including myself have experienced this.  Dexcom simply replies that the Series 7 is "not compatible," which we all know to be exaggerated by Dexcom support.  Will have to wait on Dexcom to fix this.

2) Loop complication

As for the Loop app complication, I was able to get it functioning fine with a rebuild (required for new watches) and, due to the Dexcom complication problem, am using it as my primary complication for displaying glucose on my watch. My guess is this conversation should be taken to Facebook and off of GitHub and the developers will ask us you close this issue and look for support there.

**Comment by Trpl7ca** [comment]
Thanks for the Dexcom info. I did post to FB no response, rebuilt 3 times with fresh clone following Loop and Learn instructions with no luck so posted here. Thought this was where you posted issues,  sorry if I broke protocol.

**Comment by Trpl7ca** [comment]
@ryandellolio can you were using dev version of Loop?

**Comment by Trpl7ca** [comment]
Can you confirm you are using the dev version of Loop?

**Comment by ryandellolio** [comment]
Loop master

*Ryan Dellolio*

**Comment by Trpl7ca** [comment]
I am using Loop dev and others have reported the same issue. I have my old series watch and new AW 7 paired to same phone. The AW 5 works perfectly with Both Dexcom and Loop and th AW 7 does not.

**Comment by Trpl7ca** [comment]
This was fixed in Crowdin branch but not yet in dev.
