### ISSUE TITLE
Bolus delivered in open loop 

### ISSUE THREAD

**Issue by lhedberg** [LoopKit/Loop#1570]
Describe the bug
I have been in open loop since 11/8/21. On 11/11/21 @1125pm, loop shows a 0.5u bolus was delivered. I did not enter that bolus or accept a bolus recommendation. 
Rebuilt loop 11/11/21 20:43 PST
Loop v2.2.6 
XCode v13
iOS 1

Attach the Issue Report

[Loop Report 2021-11-12 06_42_48-08_00.md.txt](https://github.com/LoopKit/Loop/files/7528427/Loop.Report.2021-11-12.06_42_48-08_00.md.txt)
[Loop Report 2021-11-12 06_42_48-08_00.md](https://github.com/LoopKit/Loop/files/7528428/Loop.Report.2021-11-12.06_42_48-08_00.md)
5

To Reproduce:
Unsure how to reproduce

Screenshots
![image](https://user-images.githubusercontent.com/51185700/141487802-a7c6fbc7-8709-401d-9252-9d5eb2d5372f.png)

Phone
Hardware iPhone Xr 10
iOS 15.1

Loop v2.2.6

CGM
Dexcom G6
Manager App: Dexcom App

Pump
Manufacturer: Omnipod

**Comment by marionbarker** [comment]
I have reviewed your report - thanks for posting it. There is no doubt that a bolus of 0.5 u was requested by Loop and the pod responded by delivering it.

I'm not trying to "blame the victim" here - but is it possible you glanced at Loop on your phone and accidentally tapped on the display of a suggested automatic bolus? These suggestions show up in the Heads-Up Display (HUD) in Open Loop when the phone is in portrait mode and are enacted by tapping on that line. 
* At that of the event, your BG was 150 mg/dl, so it is not unreasonable that an automatic bolus would be suggested on the HUD.

As an experiment, while in Open Loop, if you see a suggestion, tap on it and see if it just gets accepted or if you have to acknowledge the request further (I'm not running your version so I can't test it on my phone.) 

I've put more information below; I've summarized everything above.

# More Details

On Facebook, https://m.facebook.com/groups/LOOPandLEARN/permalink/3006601626262988/
* post that while in open loop, Loop initiated a bolus without the user requesting it
* this happened about 11:15 pm on Nov 11, 2021, PST
* a Loop Report was posted
* all Loop Report times are in GMT, so this would be Nov 12, 2021 around 7:15 am

## What I can tell from the Loop Report:

* no watch is paired
* at the time the report was issued:
  * Open Loop (dosingEnabled: false,)
  * Dosing Strategy is Automatic Bolus (dosingStrategy: LoopCore.DosingStrategy.automaticBolus,)
  * Correction Range is: 90.0 to 95.0 mg/dl
  * insulinSensitivitySchedule: ["timeZone": -28800, "items": [["startTime": 0.0, "value": 75.0]], "unit": "mg/dL"]


Basal Schedule (at the time of the report)
* timeZone: GMT-0800 (fixed)
* basalSchedule: BasalSchedule(entries: [ (these are in seconds since midnight local)
  * 00:00: OmniKit.BasalScheduleEntry(rate: 0.55, startTime: 0.0),
  * 02:00: OmniKit.BasalScheduleEntry(rate: 0.55, startTime: 7200.0),
  * 12:30: OmniKit.BasalScheduleEntry(rate: 0.55, startTime: 45000.0),
  * 20:00: OmniKit.BasalScheduleEntry(rate: 0.5, startTime: 72000.0)])

You are running v2.2.6 of Loop, built using Xcode 13 and the build-select script.

## LoopVersion
* Version: Loop v2.2.6
* profileExpiration: 2022-11-12 04:08:56 +0000
* gitRevision: e81c5afe98d4f306a5ae13369a7d4ac3f3aca0c3
* gitBranch: N/A
* sourceRoot: /Users/shawnhedberg/Downloads/BuildLoop/Loop-Master-211111-1951/LoopWorkspace/Loop
* buildDateString: Thu Nov 11 20:43:14 PST 2021
* xcodeVersion: 13A1030d

About 5 hours after the event, you swapped out this pod for a new one. That appeared to be nominal.
First pod:
* Pod active time (hrs) :   72.2
* Insulin delivered by pod (u) :  101.70
Second pod:
* Nominal start up of pod
* Pod active time (hrs) :   16.9
* Insulin delivered by pod (u) :   18.25


For the time before the event and time after the event, the spacing in messages from Loop to pod with the returned message are normal (every now and then the response isn't prompt, so Loop asks again):
Every 5 minutes:
* Loop Sent: RequestStatus
Response within a few seconds:
* Pod  Sent:  SchBasal running

At the time of the event, 2021-11-12 07:14:16, the expected pattern associated with a bolus was seen:
* Loop Sent: SetBolus of 0.50 u
* Pod  Sent:  SchBasal running; Bolus accepted, 0.50 u not yet delivered

The insulin delivered before this was 77.55 units
The insulin delivered 5 minutes later was 78.10 units.
With a basal rate of 0.55 u/hour, you expect to have either 1 or 0 pulses of 0.05 units in a 5 minute interval.
A change in delivered insulin of 0.55 is consistent with the bolus plus your basal rate.

**Comment by marionbarker** [comment]
I switched to v2.2.6 with my pod change. 
I configured it to be 
* autobolus dosing strategy
* require faceID for manual bolus 
* open loop
* the auto-bolus suggestion shows up in HUD 
* if I tap on the suggestion it is delivered without need for approval or FaceID

**Comment by marionbarker** [comment]
I'm pretty sure this scenario happened the way I suggested.  Please close this issue unless you disagree.

**Comment by lhedberg** [comment]
I agree and thought I responded. Maybe it was in FB. I’ve looked on the
GitHub site on my phone but cannot find where/how to close out the issue.

**Comment by ps2** [comment]
Thanks for the follow up on this, @marionbarker  and @lhedberg. In current dev, you will not be prompted for an automatic bolus correction, so this error should not occur.
