### ISSUE TITLE
Carb Entry Screen Absorption Time Selected First Is Changed After Touching Emoji's

### ISSUE THREAD

**Issue by Hencowitz** [LoopKit/Loop#1616]
**Describe the bug**
There have been multiple times where when we do not choose an emoji for the carb entry screen and just enter in the carbs and then the absorption, and change the absorption to say 5, but then decide to enter in the carbs using an emoji, the chosen absorption for the meal, will then change with the emoji.  This is also true for Loop Master.  The issue is that sometimes you know what the absorption for a large meal will be, and while making dosing decisions and looking at the food, you change up the order of the food or decide to use emoji's instead of just entering nothing (which we do often) and your 5 hour absorption meal is suddenly put to 30 minutes because you used a lollipop to represent the icing on the cake you are going to eat after the steak and potato....
[Export-20220302T025544Z.zip](https://github.com/LoopKit/Loop/files/8166290/Export-20220302T025544Z.zip)

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**
1. Go to 'carb entry'
2. Click on ' enter carbs' skip to enter absorption as if you were not going to enter your food type
3. Decide that you are going to try and emoji your food type and choose emoji's like lollipop
4. Watch your 5 hour absorption change to 30 min

**Expected behavior**
Whatever your initial intentions for absorption are, once you go back and change your mind and enter emoji's or change the order of the emoji's, it will override your previously selected and purposely chosen meal absorption.
**Screenshots**

**Phone**
 - Hardware: [iphone 13 pro, iphone 12 mini, iphone SE]
 - OS Version: [15.1, 14.8, 15.1 ]

**Loop Version**
 - Version Number: [v2.3.0 (57) and Loop Master v2.2.6]
 - Repo: [remote bolus/carbs, and loop master]

**CGM**
 - Device: [ Dexcom G6]
 - Manager app: [e.g. Dexcom App,]

**Pump**
 - Manufacturer: [e.g. omnipod]
 - Model: [eros]
 

**Additional context**
We had a few scary lows with my daughter before realizing that the absorption times we chose were overwritten, because we changed our mind and entered emoji's.  Also, our daughter likes to push the emoji's and if she was doing self care at school, she could put them in the wrong order or do it out of order of input and choose absorption first-since that’s usually our first entry in our house, and accidentally change the absorption before anyone knows.  I understand the purpose of emoji's but once that line is skipped or left blank, and you change the absorption, I don't think it should be able to change it.

**Comment by marionbarker** [comment]
Update for Loop dev.

First graphic shows current behavior (with LoopKit PR 422 applied).

* Left: User enters carbs and continue and default medium time used.
* Middle: User enters carbs and taps on food emoji icon which leads to the view seen on right
* Right: User sees the fast emojis first

![add-carb-issue-01](https://user-images.githubusercontent.com/19607791/184555348-36fc4c03-ef7c-4b46-be25-0e18399e3b82.png)

If user selects a fast emoji, then absorption time changes to fast and remains fast regardless of other emoji selections.

At this point, the only way to change absorption time is to use the picker-wheel.

There has been some [discussion on zulipchat](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/Emoji.20and.20Absorption.20Time/near/293329599) of modifying the code to have the medium emoji displayed initially.  This is mocked up in the following graphic. This demonstrates a behavior that I think is problematic for this interface, regardless of which section of emojis is displayed initially.

* Left: User views medium emojis first (none have been selected)
* Middle: User accidentally taps on a medium emoji instead of scrolling
* Right: User deletes the medium emoji and scrolls to the fast screen and selects the correct emoji

The accidental tap of the emoji has locked the absorption to medium.

![add-carb-issue-02](https://user-images.githubusercontent.com/19607791/184555466-88047416-76be-4e96-878d-9de1c9af95bb.png)

**Comment by marionbarker** [comment]
Using the two graphics from the prior comment.

If the user had first tapped on any one of the three icons in the middle of the first graphic and then tapped on the food emoji, that default icon absorption time would be locked in regardless of how many food emoji are selected.

**Comment by ps2** [comment]
@marionbarker The original description of this ticket fits a bug that was fixed: when the user selects an absorption time manually, selecting a custom emoji should *not* override it. That was fixed. I think separate use errors should be covered in separate tickets.
