### ISSUE TITLE
CGM number stuck

### ISSUE THREAD

**Issue by Klevenhagen** [LoopKit/Loop#1627]
The Dexcom CGM number is frozen at 115 on the Loop main page.  It will not change even after removing and reinstalling CGM.  The Dexcom app is working and reading the correct number.  If you open the CGM in Settings on the Loop App it shows the current proper number.

Anyone had this issue before?

**Comment by Kdisimone** [comment]
Yes, people have had this issue. Please search the posts in Looped group for similar and read comments for solutions. It’s not always the same cause for some issues. 

Im going to close the issue here on GitHub because I know the looped group or Zulipchat will get you a much faster answer. If you aren’t using those two places, please check loopdocs for links to join.
