### ISSUE TITLE
Feature request: Basal Test Mode 

### ISSUE THREAD

**Issue by paddingtonil** [LoopKit/Loop#1630]
It is important to perform periodic basal tests to improve TIR/BG performance. Using Low Glucose Suspend / Basal Test Mode would prevent severe lows during nightly testing.

**Describe the bug**
A clear and concise description of what the bug is. I.e. what you see vs what you expect to see.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Phone**
 - Hardware: [e.g. iPhone XS]
 - OS Version: [e.g. iOS 12.0.1]

**Loop Version**
 - Version Number: [e.g. 1.9.2]
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: [e.g. Dexcom G6]
 - Manager app: [e.g. Dexcom App, Spike]

**Pump**
 - Manufacturer: [e.g. Medtronic]
 - Model: [e.g. 723]
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**

**Comment by elnjensen** [comment]
I think this feature request would be more helpful if you say more about what you’re looking for.  What would this proposed mode do, i.e. how would it behave differently from regular Loop?

**Comment by paddingtonil** [comment]
Basal testing usually takes place at night in open loop. It is important to test the accuracy / efficiency of the basal rate(s). Close loop lows are not expected during normal operation. Hypos may occur when operating in open loop when basal rate(s) are too strong. The idea is to create a special mode that will only kick in if hypo happens in open loop during basal testing.

**Comment by paddingtonil** [comment]
Interesting concept. I, However, suspect nominal basal rate - which put to test - with an override may not present genuine outcome.

**Comment by absmindedprof** [comment]
To be clear - if I were to use an override, I would not alter the "Overall Insulin Needs" value - that remains at 100%. Only the target range (and duration) would be changed. This would have the effect of instructing loop to "tolerate" a much wider range of "eventually" glucose values without intervening (and thereby 'disrupting' the basal test.) 

As for evaluation, any time series of sensor glucose values of greater than 4 hours (following the Scheiner method) or 5 hours (following the Walsh method) with only scheduled basal being delivered would be appropriate for evaluating basal rates.

**Comment by Nightfoxy** [comment]
@absmindedprof Love it. Nice idea!
@paddingtonil This doesn't solve your problem specifically, but you can reliably use the IOB data to verify basal. You should see level, in correction range with near 0 IOB. 

If above and IOB hovers around 0.3 units, its very likely basal needs to go up by 0.05 u/hr.
If below and/or falling with negative IOB around -0.3 units, its likely basal needs to down by 0.05 u/hr. 

Factor in food and compressions, etc. But that's the general idea. Loop's insulin model is close enough to accurate that this should result in solid basal rate verification overnight that works in open and closed loop.

**Comment by woodduckie** [comment]
@absmindedprof: I too like this idea and have promptly created a "basal testing" override. :)

**Comment by UnoMas393** [comment]
> My approach has been to set a wide correction range when testing settings. The lower bound acts as "predictive low glucose suspend" while the upper bound can be set as high as you're willing to tolerate overnight drift.
> 
> My personal approach is to set set the lower bound of the correction range at 80 while keeping my suspend threshold at 70. I set an upper bound around 160-180 as I'm not willing to tolerate an unexpected high overnight. But your preference may be different.
> 
> I could also create a "basal testing" override for this purpose but haven't bothered to yet.

I'd love to share this basal testing tip on Loop and Learn, and give you credit for the idea.

**Comment by absmindedprof** [comment]
Go ahead, and no credit necessary. Just something that works for me. 

Would probably make sense to give a "why" this works along with the tip. To the best of my understanding, the Loop algorithm can be expressed as a series of prioritized conditional "if/then" statements. Adjusting the Target Range (and Suspend Threshold) is how you "tell" Loop when you want it to take action (and, by extension, not take action). 

And Basal Testing is in effect a period of deliberate inaction (no carbs, no insulin other than scheduled/programmed basal, no significant physical exertion, or any other of the 42 factors, etc.) in order to eliminate/reduce the effect of as many variables as possible other than the programmed basal rate. 

Of course, it's important to keep track of pod/canula/reservoir/sensor expiry timing when doing this (e.g. I personally wouldn't use the first day of sensor values for a basal test, and I'd be checking last day values for any sign of erratic sensor readings, and new/old sites can have a confounding effect as well. Sigh.)
