### ISSUE TITLE
Temp. Basal not uploading to NS

### ISSUE THREAD

**Issue by gigich** [LoopKit/Loop#1652]
Iphone 7
iOS 15.4
dev 322064f

Temp. Basal ist not showed correctly in nightscout. When on loop it goes to 0 on NS it is showed like normal scheduled basal rate.
All other data like job, cob, cgm, pump status seems to be ok. It is also going updated for the past (in rendered basal graph), but not on actual value.

![7DBBFFF7-A865-4E9F-8647-D9AB4FEC471B](https://user-images.githubusercontent.com/12045939/160018694-6ede798b-c502-487d-ae48-9751c9b9e194.png)
![D722567C-6303-43AE-9FFA-E48AEDB74844](https://user-images.githubusercontent.com/12045939/160018700-0800911c-48cf-4ee6-90da-f1667e7c7353.png)

**Comment by gestrich** [comment]
There is possibly a related issue 

Bug

* Put app in the background
* Send remote carbs.
* Carbs will not show in Nightscout until app is open.
* Repeated this many times with same result

Looking at this call here: healthStore.enableBackgroundDelivery

I get an error when that is called: 

```Missing com.apple.developer.healthkit.background-delivery entitlement." UserInfo={NSLocalizedDescription=Missing com.apple.developer.healthkit.background-delivery entitlement```

I notice that Healthkit background entitlement is OFF in Loop Project Settings.

Turning on Healthkit Background Updates in Entitlements seems to fix this or at least make it much, much better.

Turn on that checkbox in the screenshot
* Put app in the background.
* Send remote carbs.
* Carbs show in Nightscout immediately.
* Repeated this several times.
* This stopped working for about 5-10 minutes (new carbs not immediately showing in Nightscout)
* It then started working again after that. (Maybe due to throttling limits)

**Comment by Nightfoxy** [comment]
@gigich thanks for writing this up from https://loop.zulipchat.com/#narrow/stream/144182-development/topic/NS.20Loop.20info.20delayed.20-.20Loop.20pill.20and.20temp.20basal.20rates
