### ISSUE TITLE
Medtronic Region Code CM not included

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1701]
**Is your feature request related to a problem? Please describe.**
Some Canadian pumps have a region code of CM instead of CA

**Describe the solution you'd like**
Add CM to the dropdown options (or perhaps change label to CA/CM)

**Describe alternatives you've considered**
A note has been added to LoopDocs in the instructions for selecting the region.

**Additional context**
[Facebook post with the problem statement](https://www.facebook.com/groups/TheLoopedGroup/permalink/3118965798320065/)

**Comment by Raylan17** [comment]
If I reported an issue it was purely an accident.  My son is T1 and I just started learning and was going back and forth between websites while using Xcode and doing simulations last night.  Sorry for the confusion.

Sent from my iPhone

On May 28, 2022, at 7:18 AM, Marion Barker ***@***.***> wrote:

﻿

Is your feature request related to a problem? Please describe.
Some Canadian pumps have a region code of CM instead of CA

Describe the solution you'd like
Add CM to the dropdown options (or perhaps change label to CA/CM)

Describe alternatives you've considered
A note has been added to LoopDocs in the instructions for selecting the region.

Additional context
Facebook post with the problem statement<https://www.facebook.com/groups/TheLoopedGroup/permalink/3118965798320065/>

**Comment by marionbarker** [comment]
I reported a new issue. You must have subscribed to notifications on github which will send you email when anyone adds or comments on an issue. To turn the emails off, go to github and adjust your notification settings.

And welcome to Loop.

**Comment by ps2** [comment]
Added in https://github.com/ps2/rileylink_ios/commit/0e2a49105ef6fafff343989ed390405fbe4797ea
