### ISSUE TITLE
Loop should warn user to update the Dexcom transmitter ID after switching to a new Dexcom Transmitter

### ISSUE THREAD

**Issue by rolandet** [LoopKit/Loop#1729]
**Describe the bug**

I stumbled upon this by accident but I would consider to a moderate health risk since Loop will stop Looping if this should occur. I lost Cell Data and Wifi for about an hour and noticed that my Loop Dev App was not receiving CGM data. This made no sense to me since I know that Loop should be pulling the CGM data from the Dexcom G6 transmitter. It then dawned on me that I had changed the Dexcom Transmitter a couple of weeks back but never updated the Dexcom Transmitter ID in Loop. This totally slipped my mind.  I assume Loop in the mean time was happily pulling the CGM data from Apple Health. I'm sure others have probably run into this since it's very easy to forget to update the Transmitter ID in Loop.

**Attach an Issue Report**

**To Reproduce**
1. Change Dexcom Transmitter without updating Transmitter ID in Loop
2. Turn off Internet access on iPhone (Cell data and Wifi)

**Expected behavior**
Loop should warn the the Transmitter ID needs to be updated when the Dexcom Transmitter is changed. Another nit I have with the workflow for this is that you need to actually delete the CGM Configuration to update the Transmitter ID. Ideally you should be able to edit the existing configuration and update the Transmitter ID.

**Screenshots**

**Phone**
 - Hardware: iPhone 12
 - OS Version: iOS 15.4.1

**Loop Version**
 - Version Number:  Dev build about a month ago
 - Repo: Loop Workspace

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Omnipod
 - Model: DASH
 - Firmware version: 
 
**Additional context**

**Comment by loudestnoise** [comment]
I've always wondered how the Transmitter ID works with DIY Loop. From what I know, DIY Loop "sniffs" the CGM values over Bluetooth, so perhaps the Transmitter ID helps identify the CGM values from it vs other transmitters. Because though, Dexcom G5/G6 Mobile isn't directly connected to DIY Loop I don't think it can know when the transmitter is expired. 

I've been using DIY Loop since 2016 and I still forget to change my Transmitter ID sometimes when I swap to a new transmitter. 

I wonder as a workaround a potential future feature could be to have a countdown timer in DIY Loop after a new Transmitter ID is inputted to ask the user if they are replacing/just replaced with a new transmitter in a situation where a red loop exists & the countdown timer indicates a new transmitter would probably be needed.

It sounds complicated now that I've written it out, but ¯\_(ツ)_/¯ I'm just the dreamer here 😭

**Comment by rolandet** [comment]
You can remove and re-add the CGM from Loop for various reasons so I'm not sure if your suggestion would work in all situations. It does show the transmitter age so perhaps it could use that parameter somehow. I think the easier solution might be to display an alert or notification if Loop isn't receiving data from the Dexcom transmitter for a period of time. This would also cover other communication issues with the Dexcom transmitter.
