### ISSUE TITLE
Bug Report: Medtronic Connection bug when switching to pump with different rates

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1734]
When testing the fix to Issue #1731, discovered a new error - or at least an error message that should be updated.

After testing with a MDT 523 with a basal rate of 0.675 U/hr to demonstrate 3 decimals were displayed, switched to a MDT 515.
The MDT 515 can only deliver in increments of 0.05 U/hr so should show only 2 decimals.

However, I could not connect the MDT 515 to Loop. Note this same pump was previously connected before testing the MDT 523.

The error message was `Pump Error. Max setting exceeded` and I kept trying to increase delivery limits.
Then I thought to modify the basal rate and change it from 0.675 to 0.75 U/hr.
(In order to make this change: I had to add a Simulator pump, change rate, delete simulator pump because therapy settings are not available with no pump attached.)
The 515 connected immediately.

**Comment by ps2** [comment]
This is not a bug as much as it is a lack of a feature to handle this nicely. It would be nice to have a nicer path for handling incompatible settings between pumps, but since this is more of an edge case on a more minimally used pump, it might be prioritized pretty low.  If anyone does want to take a swing at it, I'm happy to help see it through, of course.

**Comment by marionbarker** [comment]
I’ll add it to the docs. Any chance of allowing access to Therapy Settings without a pump attached?

**Comment by marionbarker** [comment]
Closing this - will add to LoopDocs.
