### ISSUE TITLE
multiple temp targets from home screen

### ISSUE THREAD

**Issue by eszcloud** [LoopKit/Loop#177]
Multiple temp targets (say 2-3) would be helpful. I use a temporary high target for some scenarios and a low one for others and imagine that there are multiple target scenarios that people would find useful.

**Comment by tomasboudr** [comment]
a temp low one, is useful for getting closer to 80 pre meal. which is an advanced but good openAPS feature.

**Comment by CrushingT1D** [comment]
Agree with this. Some of us our using exercise mode for eating soon but would love to have both modes avail.

**Comment by elnjensen** [comment]
Agreed as well - just a change from one to two (temp low and temp high) would be very useful, and maybe (?) easier to add than allowing an arbitrary number of them.     The workout ("heart") button at the bottom of the main screen would have to pop into a different screen than it currently does since you'd need to choose both the target and the duration.

**Comment by eszcloud** [comment]
One of the great things about having a pre-set button is that it's simple and minimizes the time that I spend doing something that I do over and over and over again. I like that all I need to do to enact the temp target is push one button and select a duration. Having an extra different screen to then set everything adds flexibility but also increases time spent dealing with it. At that point, it's similar to going into the settings and changing it there. 

How many temp targets would people need to cover *regular* uses on a daily basis that they would want to have quickly accessible? 

I could use 2 temp targets. In my case, I would set one of them to be lower than my usual target range and one of them to be lower than that. For me, that would be ranges of 78 - 80, 90 - 110, and 160 - 180 mg/dL, which covers a broad range of blood sugar values fairly continuously.

The easiest to use would be a fifth button at the bottom of the home screen for a second temp target with a corresponding setting in the settings page to set the temp target range.

**Comment by tomasboudr** [comment]
Call them a workout target (higher than usual aka temp basal zero and don't
overide my choice) and a pre-meal target typically 80.
 I agree 5 options at the bottom would be awesome.

**Comment by CrushingT1D** [comment]
With one choice and having it selected it is obvious that it is selected. If we have more than one it ads complexity since it's more difficult (coding) to get it to display in the BG chart. I am not a big fan of adding more icons across the bottom.

**Comment by tomasboudr** [comment]
We have 5 icons across the top. Five across the bottom is symmetry ;)

**Comment by elnjensen** [comment]
@CrushingT1D I don't quite understand your comment about multiple targets making it harder to display on the BG chart.  Only one target would be active at any given time, and there's already code for displaying the temp "workout" target - so it seems like that could be replicated to display a pre-meal target when it's active.   Setting one target should cancel the other if it's active.  But there may well be some subtlety here I'm missing.

**Comment by itsmojo** [comment]
I believe that there is a need for a more powerful mechanism than just having multiple temp targets from the home screen. I currently have to edit multiple settings in Loop each time I go on a longer hike and then I have to remember to undo them all when I finish — not too elegant. I have been thinking for sometime that Loop could really benefit from having a notion of “Profiles” (like the t:slim has) to better accommodate things like workouts and many other reoccurring conditions. Each Profile would have all the parameters that you might want to vary (i.e., not just Target Range, but also Basal Rates, Carb Ratios & Insulin Sensitivities as needed). You should have the ability to easily copy/rename Profiles as well as a way to easily select/view the active Profile. This could probably best be done by replacing the quite limited “Use Workout Glucose Targets” function on the home screen. This way you can create various Profiles for things like different types of exercise/sports (e.g,. home workout, gym workout, hiking, basketball, etc) and various other situations that you need to reuse (e.g., air travel, sickness, etc)  or switch between (e.g., weekdays/weekends, home/work/school, etc). You should be able to easily view/select them from the home screen (perhaps with a different icon/name showing for each Profile). Adding the notions of Profiles to Loop is a lot more work than just multiple temp targets, but I would guess that it shouldn’t be overly difficult and that it would be a powerful usability improvement that many Loop users will find helpful for many different real life situations.

**Comment by tomasboudr** [comment]
Joe - Thats a much bigger ask that should have its own issue filed. Here
the request is to not only have a temp target for workouts (which we have
and is awesome), but to have another temp target that is for pre-meals. A
lot of OpenAPS folks log into nightscout that they want a temp-target of 80
in front of meal to avoid the carb spike following...their Pi/Edison then
basals towards 80 as opposed to the regular number.

Thus there is the need for HIGH target for workouts (to essentially make it
basal 0) and a low target (to make it basal appropriately) for prior to
meals.

**Comment by itsmojo** [comment]
Yesterday I originally did a posting about this to LoopKit/Loop on Gitter to see what the feedback and interest level was as a followup to a problem someone else was discussing. Unfortunately, I didn't get a single comment on my proposal. Later in the day when I was having a private conversation with Katie Disimone about another matter, I asked her about my proposal to add profiles to Loop. Katie said that it would be a great improvement that a lot of people would welcome. She currently has to use two separate Loop apps on their phone since they have two vastly different profiles for her daughter (school days vs. non school days) and then they switch between the apps!

I was thinking about filing a new issue for my proposal based Katie’s feedback after I got a chance to think about it some more and a chance to get more familiar with the possible code/GUI/documentation implications (I haven’t been programming for almost 20 years now and I’m finding that I’m having a hard time finding my way around with the Xcode/Swift programming paradigm). However, Katie pointed me to Loop#177 as the existing issue for this matter and hoped that I could make progress on it there. So that’s why I added my thoughts on profiles as a more general & elegant solution to #177.

My view is that it probably should be a different issue if we decide to pursue profiles. Temp targets for pre-meals could be a legit thing by itself, but my belief that temp targets for workouts aren’t nearly enough as being able to have alternate profiles that you can switch over to so that you can control more than just the targets (e.g., I also need to adjust my basal rates, carb ratios, and insulin sensitivity). If profiles ever do get implemented for Loop, I am wondering if they should also provide an easy to use interface to use them temporarily as this would the most general solution for an entire array of situations. Profiles will certainly would require some thought as the design would probably have a notable GUI & documentation impact and potentially have to touch a lot of code. It would be good to have some serious discussion about stuff, but right now there doesn’t appear to be very much interest which really surprises me. The only feedback I’ve gotten (besides when the one time when explicitly asked Katie about it) after posting 2 different messages was this email. Please feel free to file an issue for profiles yourself now if you think it’s appropriate as I’m not comfortable with doing it myself at this time. I’m still trying to get the lay of the land in so many different ways with all this stuff.

Thanks for the feedback Tom!

Joe

**Comment by tomasboudr** [comment]
I'm with you Joe, I would like profiles myself (even if just for weekends).
But it should be a separate issue.

**Comment by itsmojo** [comment]
Hi Tom,

Sounds like we are pretty much all in agreement here. However, I am just not comfortable actually creating this new issue myself at this time.

Joe

**Comment by CrushingT1D** [comment]
As a follow up to set a tight scope for this.
1) Add a 5th icon in the bottom icon bar in Loop. The new icon will be placed in the middle (right of bolus, left of workout mode). Icon should indicate "eating soon", but not be confused with either the carb or bolus icons.
2) Eating soon to have the same functionality as Workout Glucose Targets with the exception of time for these. Times set at 30 minutes, 60 minutes or indefinitely.
3) Target range override will needed to be added to the Target Range area of settings for this. If this feels too clunky, we may need to discuss other solutions.

@bharat @ps2

**Comment by ps2** [comment]
Implementation and design are up to whoever is contributing design and code. :)

**Comment by elnjensen** [comment]
A possibily much easier route would be simply to allow editing/override of the temp target value at the time you hit the heart icon. Right now that pop up lets you choose duration - possibly you could also choose target there (e.g. the way the carb dialog lets you hit an icon for preset value, or specify a different value).
