### ISSUE TITLE
Excessive Eros Expiration notices (Pod Beeps)

### ISSUE THREAD

**Issue by jgefaell** [LoopKit/Loop#1823]
**Describe the bug**
Following Eros pod expiration, the pod is issuing 3 consecutive expiration reminders (beep-beep beep-beep, *pause* beep-beep beep-beep), 60 seconds apart every fifteen minutes. Total of 12 expiration reminders every hour.

**Attach an Issue Report**
[Loop Report 2022-11-03 105056-0400.md](https://github.com/LoopKit/Loop/files/9933512/Loop.Report.2022-11-03.105056-0400.md)

**To Reproduce**
Behavior exhibits on Eros Pod expiration. Trigger is unknown and it doesn't happen all the time. Unable to reproduce on demand but this has happened twice to me in the last couple weeks. 

**Expected behavior**
I expect a single expiration reminder

**Screenshots**
N/A

**Phone**
 - Hardware: iPhone Xs Max 
 - OS Version: iOS 16.1

**Loop Version**
 - Version Number: 2.3.0 
 - Repo: Loopkit/loop

 ## Build Details
* appNameAndVersion: T1Pal Dev Loop Green v2.3.0 (2022092703)
* profileExpiration: 2023-09-28 02:34:39 +0000
* gitRevision: 284d9ef
* gitBranch: N/A
* workspaceGitRevision: ca8a374
* workspaceGitBranch: dev

**CGM**
 - Device: Dexcom G6 W/ Anubis
 - Manager app: xDrip4iOS 4.10.6

**Pump**
 - Manufacturer: Insulet
 - Model: Eros
 - Firmware version: 
 Device Details
Lot Number 50260
Sequence Number 240533
PI Version 2.10.0
PM Version 2.10.0

**Additional context**
As reported by multiple users on Facebook at: 
https://www.facebook.com/groups/TheLoopedGroup/posts/3239847262898584/?__cft__[0]=AZXYmp7qRQpWqt1gdj4oaT_H7odvoc0YWqTZjnNe-XXkVs_WNiPrxmcV_clUGDIJDxJUwRGkEGZeOcRFmbEHFzvZbfpDaK1oBO03cxes384rqf4AnVFPte43578ODVu1k23MZau4bIsIDOv2tqLHX2tDjqCea4dnzB2yivQ8s0qGW-kzoctpm2RPFym85vzf9oM&__tn__=%2CO%2CP-R

**Comment by jgefaell** [comment]
This continues to occur not infrequently. Not with every pod but twice since posting this and once again right now.

**Comment by FBurrage** [comment]
Seeing the same issue here, but has started in last 2hrs prior to 72hrs, so between 70 and 72.  Must be second or third consecutive pod at least now, but could be more.  Switched to 2.3.0 (57) on 13/Nov.

Get a beep notification every 15mins, but each 15min set of beeps has 2 further sets (set of 3 in total).  Each of two further sets follows at 2min intervals then stops.

Issue report available, will try to work out how to attach to comment.

**Comment by ps2** [comment]
Thanks for attaching the issue report, it's helpful.

Pod alerts now sound until the associated notification in Loop is acknowledged. Looking at your issue report, you acknowledged the last pod expired alert just 15 or 20 seconds before generating the issue report.  So I'm guessing the beeping stopped after that.

If you continue to have beeping from the pod, a while after you've acknowledged the alert in Loop, please reopen this ticket, capture another issue report and describe what you observed.

**Comment by MooseV2** [comment]
This is regressive behaviour and makes me want to revert back to Loop 2. The beeps aren't helpful. I already know that the pod is expiring (and even if I didn't, only ONE set up beeps is necessary for this). 

The cost of Omnipod is very expensive and I like to use them for 80 hours, ie 72+8 hours. I can time it so that 80 hours elapses about an hour after I wake up, which maximizes the amount of time I can use a pod for. However, this feature makes it impossible to sleep and as far as I can tell doesn't have an option to disable it.

Furthermore, the feature is poorly implemented. Upon hearing the beeps I will open the Loop app and the notification will not appear for several seconds. Sometimes, it does not appear AT ALL, and requires me to force close the app and open it again for the message to popup.

There also isn't an iOS system notification for these alerts, so the only feedback comes from the pod itself.
