### ISSUE TITLE
Feature Request: Allow Loop to correct BG intervally like every hour rather than every 5 minutes

### ISSUE THREAD

**Issue by toygar34** [LoopKit/Loop#1832]
**Is your feature request related to a problem? Please describe:**
 Sometimes, especially after having a juice or candy BG spikes very hard but not all candies or juices have same level of sugar. The increase on BG is being corrected by Loop very aggressively but the power of sugar may end sooner than expected. I would like to adjust the intervention interval manually like every 30 minutes or every hour.

**Describe the solution you'd like :**
An option to manually adjust the correction interval manually. Every 15,30,45,60 minutes for example. By this way we can prevent unintended corrections caused by wrong BG values received via sensors.

**Describe alternatives you've considered :**
Turn off auto bolus and switch to basal only and reduce basal limits.

**Comment by Willbumster** [comment]
Not sure about this idea, it would need to be in a OPEN-LOOP mode to prevent Loop from simply auto-bolusing the correction.
Ron

Sent from my iPhone

On Nov 18, 2022, at 10:45 AM, toygar34 ***@***.***> wrote:

﻿

Is your feature request related to a problem? Please describe:
 Sometimes, especially after having a juice or candy BG spikes very hard but not all candies or juices have same level of sugar. The increase on BG is being corrected by Loop very aggressively but the power of sugar may end sooner than expected. I would like to adjust the intervention interval manually like every 30 minutes or every hour.

Describe the solution you'd like :
An option to manually adjust the correction interval manually. Every 15,30,45,60 minutes for example. By this way we can prevent unintended corrections caused by wrong BG values received via sensors.

Describe alternatives you've considered :
Turn off auto bolus and switch to basal only and reduce basal limits.

**Comment by elnjensen** [comment]
You can achieve something like this goal fairly easily with existing Loop functionality by using overrides.  If you don't  want Loop to give you a correction bolus for the next hour, then create an override with a 1-hour duration, and a target BG range of, say, 100-400 mg/dl. 

You could do the same (separate saved overrides) for different time intervals, and choose whichever seems best in a given situation.

**Comment by ps2** [comment]
This seems related to potential issues around the effects of glucose momentum or retrospective correction. During a sudden unexpected spike in BG, Loop can react quite strongly.  I think some examples would help clarify the particular situation you're hoping to fix here.  I think turning off Loop to only loop every 30 minutes would also prevent Loop from shutting off insulin in a timely manner, if BG suddenly turned around.
