### ISSUE TITLE
Loop predicting negative BG and significantly reducing insulin delivery when BG is high.

### ISSUE THREAD

**Issue by jannackennedy** [LoopKit/Loop#1846]
**Describe the bug**
This has happened several times, usually after using or canceling a custom override. Loop predicts a negative BG when there is little or no IOB, then corrects for that by decreasing temp basal even when BG is high (over 200). When I enter carbs no bolus is recommended so I manually bolus, but loop continues to decrease temp basal and I cannot get out of high BG range.

Today: (after dealing with this for several hours). BG: 185. IOB: 0.7 (not enough to cover the BG). Loop has set insulin delivery at -1.2.

**Attach an Issue Report**
The loop report I created when the issue was worse did not create (it sent me a blank screen that said loading...), attaching a newer loop report now.
[Loop Report 2022-11-27 12:05:22-08:00.md](https://github.com/LoopKit/Loop/files/10099113/Loop.Report.2022-11-27.12.05.22-08.00.md)

**To Reproduce**
I cannot reproduce.

**Expected behavior**
I expect loop to provide insulin based on the correction factors I have entered. I do not expect it to predict an excessively low BG and reduce insulin delivery based upon that.

**Screenshots**
<img width="1243" alt="Screen Shot 2022-11-27 at 11 49 44 AM" src="https://user-images.githubusercontent.com/116413883/204157064-4b3d05e0-ac22-412b-b158-19be53c6bb4a.png">
<img width="1243" alt="Screen Shot 2022-11-27 at 12 15 52 PM" src="https://user-images.githubusercontent.com/116413883/204157663-2673c95f-f927-4492-9e05-fbbbd3842ec6.png">
![IMG_6221](https://user-images.githubusercontent.com/116413883/204157054-3542010c-ec1c-45ec-8b72-bf3851830d49.PNG)

**Phone**
 - Hardware:  iPhone 12
 - OS Version:  iOS 15.7

**Loop Version**
 - Version Number: 2.2.9
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App, Spike

**Pump**
 - Manufacturer: Omnipod
 - Model: Eros
 - Firmware version: do not know where to find this

**Additional context**
N/A

**Comment by Nightfoxy** [comment]
Seems like the fix is to have accurate settings.

Secondarily, maybe an ability to clear or reverse settings changes made by
recent overrides to limit the negative impact of their misuse or
mis-application.

**Comment by jannackennedy** [comment]
Thank you for responding. 

Generally the loop works very well with my current settings. Could you see an error in my settings that would cause this to happen? I am a longtime T1 but a new looper, and I am struggling to understand why this happens on occasion.

**Comment by bkhx** [comment]
>Seems like the fix is to have accurate settings

I think that misses the point.

There are valid reasons for therapy settings to be changed from time to time.  The issue is what should happen with the active carbs at the time of the change.  In particular, what would be a "correct" prediction of the future BG curve?

In my view, a correct prediction would be the curve resulting from iterating over all the currently active carbs, using the current settings for ISF and I:C with the current IOB.  But that's not the result that Loop currently shows.  

Based on the behavior of the graph, it is as if Loop is predicting the future based on the ISF and I:C that were formerly in effect at the time the carbs were entered.  To me that seems wrong, based on my own experience with this issue that is reported by the OP.

It seems to me that at the time the ISF or I:C changes, the amount of active carbs remaining is properly calculated based on the previous therapy settings, but the future of those remaining carbs should be determined by the new therapy settings.

With the current code, the incorrect prediction of severe low survives a force-close of Loop or a reboot of the phone, so we must simply do repeated manual corrections for several hours while the stale carb data ages out of the calculations.

**Comment by jannackennedy** [comment]
Thank you. That makes sense.
