### ISSUE TITLE
Evaluate NS Loop pill timing

### ISSUE THREAD

**Issue by marionbarker** [LoopKit/Loop#1865]
**Describe the bug**
Not entirely sure this is a bug. Opening an issue per @ps2 request to capture status.

**prior discussion**
Please see:
* zulipchat discussion [COB displayed as 0 in Nightscout](https://loop.zulipchat.com/#narrow/stream/144182-development/topic/COB.20displayed.20as.200.20in.20Nightscout)
* Closed issue under cgm-remote-monitor: [Intermittent NS COB display of 0 g](https://github.com/nightscout/cgm-remote-monitor/issues/7765) 

**To Reproduce**

Test Configuration 1:
* Loop phone using Dexcom Share as CGM source; NS site using Dexcom Bridge as CGM source using rPi DASH simulator as pump.
 
Test Configuration 2:
* Loop phone using CGM simulator and uploading CGM values to NS site using rPi DASH simulator as pump.
 
Test Configuration 2:
* Loop (real) phone using G6 with DASH pod
* Uploading CGM values from phone to NS site 

**Expected behavior**
Expect Loop pill should update COB, IOB promptly after entry applied to Looper's phone.

Config 1: the plot appears promptly but Loop pill doesn't update until next cycle; at which time Loop and NS COB/IOB pills update
Config 2: can't get the Loop pill to display, but it does update to show Loop 1 min ago promptly, can view NS COB/IOB pills - they exhibit the delay in updating until next cycle.
Config 3: Loop pill updated promptly when carbs added to Loop phone - same time as plot (confirmed 2x)

Repeat Config 2, but this time observe the LoopCaregiver display.
* Initial values: IOB 1.4, COB 20, matches Looper phone.
* Issue 10 g on Looper phone, accept 0.65 U bolus.
* Plot updates, Loop says 1 minute ago (still can't view Loop pill)  
* Wait for LoopCaregiver app to stop spinning, still says IOB 1.4, COB 20 on LCG.
* Wait for next next simulator CGM value which triggers new upload cycle to NS
   * NS COB/IOB pills update
   * View LCG, as soon as spinning stops, it updates as well
   * All three match Loop phone

**Comment by bewest** [comment]
FWIW, I think this is the desired and expected behavior.  What happens in Config 1 and Config 2 when you enable "upload readings" and disable all Dexcom Share?  Nightscout is fundamentally designed to noticed iterations and updates when glucose updates occur, and everything else is layered on as additional feature/plugin.  The purpose of Loop uploading data to Nightscout is to given a full account of all data going through Loop.  Using Dexcom Share/bridge bypasses this, making it difficult to know if Loop has completed a full cycle.

When Loop updates Nightscout with _all the data available for an iteration for looping_, the test seems to indicate that everything updates correctly.  I commonly recommend enabling "upload readings" and encourage this to be adopted as the standard configuration.  There are a variety of reasons to avoid the bridge feature in Nightscout in favor of observing Loop's inputs and outputs, including this issue.

**Comment by bewest** [comment]
I see what you mean with Config 2 and Config 3.  If both configs were uploading same data at same cadence, I would expect Nightscout's behavior to be the same. Sorry for not catching this earlier.

You can experiment with the timing of loop iterations by selecting open loop, and then entering carbs or otherwise influencing dosing operations (eg with override, or by toggling pre-meal) and then manually selecting the suggestion from the recommendation line.  AFAICT, this manually "forces" one loop/measure/dose/upload cycle and NS is updated instantly without waiting.

**Comment by ps2** [comment]
During each loop, Loop creates two dosing decision records. One recording the state of things prior to automatic dosing, and explaining Loop's reasoning for the automatic dose.  The second one happens *after* the dose has been initiated, and contains a forecast including the effects of the automatic dose, and an updated recommendation that can be used for manual dosing.  The Nightscout uploader plugin in Loop will combine those two records, and upload one `devicestatus` record to Nightscout. If a situation can be reproduced where Loop is not uploading the correct data for a device status records, please capture the details of that.

**Comment by bewest** [comment]
To get the `devicestatus` records, you can use `/api/v1/devicestatus.json` to retrieve them.  When Nightscout's `loop` plugin is enabled, these records drive the pill updates so that the pill matches loop.  Otherwise, NS will use it's own algorithm based on treatment records which won't match Loop's.
