### ISSUE TITLE
Loop -456 Projection After Dec 31 Commit

### ISSUE THREAD

**Issue by shainey** [LoopKit/Loop#1885]
**Describe the bug**
Loop projected an Eventual -456 mg/dl glucose level, and the math didn't make sense for parameters, IOB, COB, etc.  Loop shut off insulin delivery due to this. Please see the screenshots and files for more details. Enter the new Commit on Dec 31, 2022, yesterday morning, and it worked fine before this.

**To Reproduce**
1. Had Custom Preset on for morning workout
2. Changed Custom Preset off and entered carbs for morning coffee.
3. Delivered expected insulin and then displayed the Eventual -456 mg/dl glucose level, shutting off the insulin.

**Expected behavior**
Normal loop behavior.

**Phone**
 - Hardware: iPhone 14 Pro Max
 - OS Version: 16.2

**Loop Version**
 - Version Number: v2.3.0 (57)
 - Repo: Dev

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet Pod 
 - Model: Dash
 - Firmware version: 4.10.0
[Export-20230101T113708Z.zip](https://github.com/LoopKit/Loop/files/10328861/Export-20230101T113708Z.zip)
[Export-20230101T125747Z.zip](https://github.com/LoopKit/Loop/files/10328862/Export-20230101T125747Z.zip)
[Loop Report 2023-01-01 063641-0500.md](https://github.com/LoopKit/Loop/files/10328863/Loop.Report.2023-01-01.063641-0500.md)
[Loop Report 2023-01-01 075731-0500.md](https://github.com/LoopKit/Loop/files/10328864/Loop.Report.2023-01-01.075731-0500.md)
![Screenshot 1](https://user-images.githubusercontent.com/22161266/210172735-4e58e56d-8126-43fb-883f-86069e06d566.png)
![Screenshot 2](https://user-images.githubusercontent.com/22161266/210172736-4f04b0a7-7490-472a-91d1-57359ca3a87e.png)
![Screenshot 3](https://user-images.githubusercontent.com/22161266/210172737-898560da-9019-40e7-a29c-9d31861fb15f.png)
![Screenshot 4](https://user-images.githubusercontent.com/22161266/210172738-f8f8a6c8-72ce-4b1f-98d9-b5f49c60bd7e.png)
![Screenshot 5](https://user-images.githubusercontent.com/22161266/210172739-7d6945d7-cfc0-46db-85d5-48792e528ec9.png)

**Comment by CosiP** [comment]
Not sure if it is the same but something similar happened to us. We had Loop given “correction bolus” with an expected BG below target.To reproduce:Not sure how as we didn’t do anything out of the ordinary. Aviary my sun was sleeping into the morning. Expected behavior. For loop no to give more insulin if expected BG is below target. Phone: IPhone XRiOS version : 16.2Loop Version2.2.9Built December 14 2022Master branchSensor:DEXCOM G6Pump:Omnipod DashI think this is all the info I have,We did not change any settings, so even when his BG was going up, which will require the corrections bolus, I don’t expect this to the point to have a predicted BG of 47. Hope this helps.Sofia.On Jan 1, 2023, at 8:44 AM, Steven Hainey ***@***.***> wrote:﻿
Describe the bug
Loop projected an Eventual -456 mg/dl glucose level, and the math didn't make sense for parameters, IOB, COB, etc.  Loop shut off insulin delivery due to this. Please see the screenshots and files for more details. Enter the new Commit on Dec 31, 2022, yesterday morning, and it worked fine before this.
To Reproduce
Steps to reproduce the behavior:

Had Custom Preset on for morning workout
Changed Custom Preset off and entered carbs for morning coffee.
Delivered expected insulin and then displayed the Eventual -456 mg/dl glucose level, shutting off the insulin.

Expected behavior
Normal loop behavior.
Phone

Hardware: iPhone 14 Pro Max
OS Version: 16.2

Loop Version

Version Number: v2.3.0 (57)
Repo: Dev

CGM

Device: Dexcom G6
Manager app: Dexcom App

Pump

Manufacturer: Insulet Pod
Model: Dash
Firmware version: 4.10.0
Export-20230101T113708Z.zip
Export-20230101T125747Z.zip
Loop Report 2023-01-01 063641-0500.md
Loop Report 2023-01-01 075731-0500.md

**Comment by shainey** [comment]
This happened to me again.  It occurs when changing your Custom Preset and then entering carbs & bolusing within the 5 min cycle.  

When deleting the insulin bolus record, it removes the record but remains within the IOB, forcing me to add a lot of dubby carbs, so it doesn't turn off the insulin delivery.  This isn't good for individuals struggling to develop a workaround to address this issue when it comes up.
