### ISSUE TITLE
Loop failure 

### ISSUE THREAD

**Issue by Kai2108** [LoopKit/Loop#1891]
![4E58E05D-7874-4832-8BE2-C70E2A67DC96](https://user-images.githubusercontent.com/122201384/211197446-1e3f1812-baea-4ff4-8cde-d08a3a7f166a.png)
![1EFF531C-286A-42AA-9677-E40F6006E457](https://user-images.githubusercontent.com/122201384/211197457-f3903314-9cc0-47ef-9d51-ef7f414c0078.png)
![A77291ED-034F-43CA-9294-ADC1F440C383](https://user-images.githubusercontent.com/122201384/211197459-57bff69f-fea3-4fe3-b441-c5c5a94f69e0.png)
Sometimes a loop is not successful, what ist my issue? When I pair a new Omnipod dash it need s round about 10 times to click on retry till the connection is established.

**Attach an Issue Report**
Tap the Loop settings icon on the bottom of the screen, then tap Issue Report and attach it to this ticket.

[Uploading Export-20230108T084514Z.zip…]()

**Phone**
 - Hardware: iPhone XS
 - OS Version: iOS 16.1

**Loop Version**
 - Version Number: 2.3.0(57)
 - Repo: [LoopKit/Loop,

**CGM**
 - Device: Dexcom G6]
 - Manager app: Dexcom App,

**Pump**
 - Omnipod dash

@

**Comment by CougarX6** [comment]
Where is the old pod while you're trying to pair the new one?  Put the old one in the microwave, wrapped in aluminum foil (til you're done pairing the new one), put it in another room or outside in the trash.  You shouldn't have any communication issues then.

**Comment by ps2** [comment]
When you next see this issue, please capture an issue report and attach it here, rather than posting screenshots. I don't think an old pod should cause interference with pairing.

During pairing, the pod uses a very *quiet* radio mode where the signal is very weak, to reduce the chance of inadvertently pairing with the wrong pod.  This means that you need to have the pod close to your phone.  If you are using a phone case, you might need to have the pod even closer.

**Comment by ps2** [comment]
I believe this issue is likely local to the particular phone or procedure being used here. If this appears to be an issue in Loop, please reopen.
