### ISSUE TITLE
Two AutoBoluses in same Loop cycle after G6 comms error

### ISSUE THREAD

**Issue by bedtime4bonzos** [LoopKit/Loop#1919]
Nightscout and Loop show 2 AutoBoluses in the same Loop cycle at [2023-01-31 18:02], within ~10 seconds of each other.  The first is for 0.05U and the second is for 0.1U.  

The log shows:
&nbsp;&nbsp;&nbsp;&nbsp;1) DexcomG6 comms failure "Failed to encrypt the connection, the connection has timed out unexpectedly", 
&nbsp;&nbsp;&nbsp;&nbsp;2) The first bolus is given (without a new BG reading)
&nbsp;&nbsp;&nbsp;&nbsp;3) DexcomG6 connects and gets a reading
&nbsp;&nbsp;&nbsp;&nbsp;4) The second bolus is given (after receiving the new BG reading).

![double](https://user-images.githubusercontent.com/6617751/216238982-003c99ad-6cc1-488d-85d8-1d1efd82989f.jpg)

iPhone 6s, iOS 15.6
Loop 3.0.0 with CustomTypeOne patches
Dexcom G6
Omnipod Eros
Issue occurs in logfile at [2023-01-31 18:02]
[Loop Report 2023-02-01 17_19_46-07_00.md](https://github.com/LoopKit/Loop/files/10565003/Loop.Report.2023-02-01.17_19_46-07_00.md)

**Comment by rossi32s** [comment]
Having same issue,  Often times these back to back auto bolus have a "duration" of "1" with the second one given.

![351754410_10226482754369498_7874759126173016667_n](https://github.com/LoopKit/Loop/assets/108834514/16807fb7-7901-4413-9655-b7ac277d0ddc)

iPhone 12, iOS 16.4
Loop 3.2.1 without patches

**Comment by marionbarker** [comment]
I noticed similar behavior when doing tests with a test phone and a rPi DASH simulator. I frequently had comm dropout with my rPi. (Not sure if it was the app or my pi or my wifi - but I couldn't seem to get though a test of uploading a glucose profile (about 4 hours) without at least one dropout. When comms was restored, I noticed the double entry. Several times it was successive boluses within the same minute (they added up to about the right amount). At least once, it was a bolus (AB) followed by 0 U/hr (TB) reported in the same minute.

I modified my test protocol to use the in-app pod simulator and I no longer have comm drop-outs and I am not seeing double entries. I suspect (but have not proven) that the double entries are caused by Loop running once for the pump reconnection and once for the next CGM value after the pump reconnects.

For Bryan's original post, Loop will cycle until the glucose reading is stale (15 minutes). So that sounds like a similar scenario. I haven't looked in detail at the timing (thanks for posting the log - I plan to review it).

I don't know if this is helpful information and I'm willing to do additional tests if that would be helpful.

**Comment by marionbarker** [comment]
I posted too soon. I did get a repeated save and upload to Nightscout.

As far as NS is concerned:
![Screenshot 2023-06-10 at 5 10 00 PM](https://github.com/LoopKit/Loop/assets/19607791/2916cfec-c5dc-45f7-ac59-23ecedf9bb86)

**Comment by marionbarker** [comment]
I have seen a lot of evidence of this in the testing I have been doing for the Algorithm Experiments.

The test scenario is an upload to Nightscout URL of one CGM value every 300 sec that is used as CGM source for the test phone.
The test phone uploads from Loop to the same Nightscout URL from which I can extract IOB and dosing information.
I have many instances of more than one insulin command within a single CGM time.

Here is one example: 

First graphic is Nightscout Display showing more than one Temp Basal during one CGM cycle.

![Screenshot 2023-06-27 at 7 44 20 PM](https://github.com/LoopKit/Loop/assets/19607791/1782bb2a-c4e1-44c4-8d09-bbe976ed14d7)

Second graphic is of the Treatments for that same time stamp - with 3 values shown at 12:41.

![Screenshot 2023-06-27 at 7 46 08 PM](https://github.com/LoopKit/Loop/assets/19607791/334d0b95-998f-4678-b9ea-aff73d48dbc9)

Third graphic is Apple Health at the same time.

![IMG_ECAE3130140A-1](https://github.com/LoopKit/Loop/assets/19607791/520c4bf5-59ab-4679-b542-296ff6a8a4e1)

**Comment by bedtime4bonzos** [comment]
I also see this sometimes, which is likely the same issue.  Instead of multiple boluses, I see a "Bolus in progress" error and also a successful bolus.
![Screenshot 2023-07-14 100720](https://github.com/LoopKit/Loop/assets/6617751/8dc91022-a698-4738-b741-475d68c58257)
