### ISSUE TITLE
Loop 3 not calculating IOB when switching from Closed to Open Loop?

### ISSUE THREAD

**Issue by tqb43** [LoopKit/Loop#1920]
**Describe the bug**
I noticed that if I switch from Closed Loop to Open Loop, the insulin that was delivered during closed loop is no longer included in any of the IOB. 

I had used Loop for awhile and then had been trying O5. I decided to give Loop 3 (with patches) a go. Last night, after installing I was running everything in open loop with 0 IOB. After a while, my sugar was high so I decided to close the loop and let the system start giving corrections. It rose my basal to 2.5 units for 20 minutes. It was saying my IOB was around 1. I then switched back to open loop as I'm still trying to iron out my settings since it's been awhile. I then noticed that the IOB went back to near 0. The graphs didn't show any of the insulin it had given me. But it was still logged in my event details and on my pump.

**Attach an Issue Report**
Attached, but generated the report about 12 hours after the incident
[Loop Report 2023-02-04 14 48 22-05 00.md](https://github.com/LoopKit/Loop/files/10609525/Loop.Report.2023-02-04.14.48.22-05.00.md)

**To Reproduce**
Steps to reproduce the behavior: Try this:
1. Open loop for awhile. 
2. Close loop and be sure it's giving you extra insulin
3. After like 15-20 minutes "open" loop again. 
4. See if it correctly includes the insulin it delivered in the IOB. (May take a cycle to calculate) 

**Expected behavior**
I expected that Loop would still maintain any IOB it gave me while closed, even if I open it back up - as that's how the app worked in the past. 

**Screenshots**
Attached
![IMG_0124](https://user-images.githubusercontent.com/22806653/216787051-8be39b6b-333e-4254-8a53-fb9dcb6bb918.jpg)
![IMG_0125](https://user-images.githubusercontent.com/22806653/216787053-18537ab6-4a4d-4737-9496-576fcfe986d8.PNG)

**Phone**
 - Hardware: Iphone 14
 - OS Version: [e.g. iOS 12.0.1]

**Loop Version**
 - Version Number: 3.0.0 (101)
 - Repo: [Loop with Patches]

**CGM**
 - Device: G6
 - Manager app: Dexcom

**Pump**
 - Manufacturer: Medtronic 
 - Model: 522
 - Firmware version: 2.4A1.1

**Comment by blameitonben** [comment]
This looks correct, IOB (active) and insulin delivered are two different things. It shows you had a wild drop in you BG during your test in closed loop, which loop would have likely predicted a future low and shut off your basal. There for negating the 1 unit it gave earlier and dropping your total IOB in this case by the time you got to the screen shot you had about 1/10th of that still on board.

The graphs reset at midnight every day, so IOB is the duration over 5/6 hrs but delivered totals resets to 0 at midnight.

Maybe test again not during the graph switch to better understand what’s going on.

I’d also look at your settings as it looks like your basal rate is set very low or to 0 maybe?

Ben


________________________________
From: tqb43 ***@***.***>
Sent: Saturday, February 4, 2023 11:53:35 AM
To: LoopKit/Loop ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [LoopKit/Loop] Loop 3 not calculating IOB when switching from Closed to Open Loop? (Issue #1920)


Describe the bug
I noticed that if I switch from Closed Loop to Open Loop, the insulin that was delivered during closed loop is no longer included in any of the IOB.

I had used Loop for awhile and then had been trying O5. I decided to give Loop 3 (with patches) a go. Last night, after installing I was running everything in open loop with 0 IOB. After a while, my sugar was high so I decided to close the loop and let the system start giving corrections. It rose my basal to 2.5 units for 20 minutes. It was saying my IOB was around 1. I then switched back to open loop as I'm still trying to iron out my settings since it's been awhile. I then noticed that the IOB went back to 0. The graphs didn't show any of the insulin it had given me. But it was still logged in my event details and on my pump.

Attach an Issue Report
Attached, but generated the report about 12 hours after the incident
Loop Report 2023-02-04 14 48 22-05 00.md<https://github.com/LoopKit/Loop/files/10609525/Loop.Report.2023-02-04.14.48.22-05.00.md>

To Reproduce
Steps to reproduce the behavior: Try this:

  1.  Open loop for awhile.
  2.  Close loop and sure it's giving you extra insulin
  3.  After like 15-20 minutes "open" loop again.
  4.  See if it correctly includes the insulin it delivered in the IOB. (May take a cycle to calculate)

Expected behavior
I expected that Loop would still maintain any IOB it gave me while closed, as that's how the app worked in the past.

Screenshots
Attached
[IMG_0124]<https://user-images.githubusercontent.com/22806653/216787051-8be39b6b-333e-4254-8a53-fb9dcb6bb918.jpg>
[IMG_0125]<https://user-images.githubusercontent.com/22806653/216787053-18537ab6-4a4d-4737-9496-576fcfe986d8.PNG>

Phone

  *   Hardware: Iphone 14
  *   OS Version: [e.g. iOS 12.0.1]

Loop Version

  *   Version Number: 3.0.0 (101)
  *   Repo: [Loop with Patches]

CGM

  *   Device: G6
  *   Manager app: Dexcom

Pump

  *   Manufacturer: Medtronic
  *   Model: 522
  *   Firmware version: 2.4A1.1

**Comment by tqb43** [comment]
> 

Hmm maybe, i'll definitely test again. I just know that before I opened loop again it said my IOB was about 1, which made sense with the 2.5 basal raise for 20 minutes. 

My basals are about .5 an hour.

**Comment by blameitonben** [comment]
Is it possible you where negative before you switch because of the strange drop in BG 20-30 minutes earlier?
________________________________

**Comment by tqb43** [comment]
No, I 'm positive I wasn't negative. I was just running my basal rates, then closed the loop for a bit (I was high) And then there was that drop so I switched out of close loop because I wasn't confident in my settings. It was then when I noticed it didn't record the IOB.

**Comment by tqb43** [comment]
I got better before and after photos of the issue. Please note the time in the images. The "before" pictures have blue markings
![IMG_0128](https://user-images.githubusercontent.com/22806653/216804437-5786af8c-9e72-4f49-82d8-a11c0919344d.jpg)
![IMG_0129](https://user-images.githubusercontent.com/22806653/216804438-5cc0565f-ce0f-4870-9b3c-afdc29d00bb2.jpg)
![IMG_0130](https://user-images.githubusercontent.com/22806653/216804439-8ed2c3f8-4545-4f4f-b264-79bc49e4e7e0.jpg)
![IMG_0131](https://user-images.githubusercontent.com/22806653/216804440-d4a49249-9e5b-47dd-9838-1ef22a524faa.jpg)
![IMG_0132](https://user-images.githubusercontent.com/22806653/216804441-8924f29e-46d1-4622-afe0-575d054b12ae.jpg)
![IMG_0133](https://user-images.githubusercontent.com/22806653/216804442-6c34d5b8-d29e-49ae-819d-4c5b49e7b5a9.jpg)
![IMG_0134](https://user-images.githubusercontent.com/22806653/216804443-3b39c446-bf4c-4556-9ea9-b7a34d2f7214.jpg)
 and the "after" pictures have red markings.

**Comment by tqb43** [comment]
I deleted Loop with Patches and installed traditional loop 3. The same issue persists.

the IOB from closed loop retains AB correctly when placed back in open loop but nothing from temp basals.

**Comment by marionbarker** [comment]
This is probably a misinterpretation of the way Temp Basal is accounted for in Loop.

Part of the IOB change you are seeing is because when you go from Closed Loop to Open Loop, the scheduled basal is  immediately restored. (This is new with Loop 3. With Loop 2, the temp basal continued unless you suspended and resumed the pump.)

When temp basal is commanded with closed loop, the rate changes, but dosing comes in slowly (about 17% of recommended dose every 5 minutes with amount being delivered at the end of the basal period for pods). However, because of the way the forecasting is done, the positive IOB leads what will be delivered by 10 minutes. If you then switch to open loop before the temp basal completes, the extra 10 minutes worth of temp basal is removed from IOB to account for the early termination of that temp basal.

I made exactly the same mistake when looking at Manual Temp Basal accounting as seen in Issue 1819: [Manual Temp Basal Chart/Report Error?](https://github.com/LoopKit/Loop/issues/1819) which I subsequently closed.

At the end of that issue conversation, Pete said: "This is how the insulin model in Loop works. Insulin has a 10 minute delay, which applies to negative insulin as well. It's understandably not intuitive to think about "negative" insulin having a delay, but that's how the model works."
