### ISSUE TITLE
Loop 3 Pod Failures

### ISSUE THREAD

**Issue by LukeDev** [LoopKit/Loop#1921]
I’ve upgraded to Loop 3 since it’s launch date. I’ve started to experience a large amount of random pod failures most of which are happening very early in the morning (around 4am). Every time I’m woken up by the intense sound of the Omni Pod failure sound. When the Pods are failing they are consistently failing 2/3’s of the way through their life. I’ve just had another one with this time seeing that it gave me a 0x12 code. If anyone has suggestions I’m all ears! 
![A5989A9D-F8D7-400C-99CD-062B5E17696B](https://user-images.githubusercontent.com/3454876/216957213-74610a8e-89b1-4b6a-98a1-6cd39feb80ad.jpeg)

**Comment by bogusflyby** [comment]
I have had the exact same problem with my Eros pods. I don't have that many to be loosing that many pods or insulin so I went back to the 2.9 version until something gets straightened out

**Comment by snickerdoodleparent** [comment]
From https://github.com/openaps/openomni/wiki/Fault-event-codes 
0x12 Reset due to Low Voltage Detect - More likely on third day of use due to low batteries and/or static electricity

Was it an Eros pod?

Do you use a gel pod cover? We have a reusable kind. We get static failures otherwise on the trampoline, during gym class (probably due to static charge with a certain type of sneaker) and some times from the bedding.
