### ISSUE TITLE
Loop 3.0 crashing consistently

### ISSUE THREAD

**Issue by Jemzor** [LoopKit/Loop#1922]
When I am running Loop 3, it regularly crashes. This started occurring from the outset following installation, from the onboarding process through to daily usage.

Timeframe between crashes could be as little as approx 20 seconds.

IPhone 14
Loop 3.0.0 (2)
IOS 16.3
Eros + Rileylink

To replicate, open Loop app and wait - either idle or whilst navigating Loop.

Recent Issue log extract detailed below - after re-entering Loop post crash.

Attached image after re-entering Loop post crash.

Loading...

Use the Share button above save this diagnostic report to aid investigating your problem. Issues can be filed at https://github.com/LoopKit/Loop/issues.

Generated: 2023-02-08 21:06:06 +0000

## Build Details
* appNameAndVersion: Loop v3.0.0 (2)
* profileExpiration: 2024-02-02 23:32:56 +0000
* gitRevision: 743b8d7
* gitBranch: N/A
* workspaceGitRevision: d70602d
* workspaceGitBranch: main
* sourceRoot: /Users/runner/work/LoopWorkspace/LoopWorkspace/Loop
* buildDateString: Fri Feb  3 00:02:08 UTC 2023
* xcodeVersion: 14B47b

## FeatureFlags
* cgmManagerCategorizeManualGlucoseRangeEnabled: false
* criticalAlertsEnabled: false
* entryDeletionEnabled: true
* fiaspInsulinModelEnabled: true
* lyumjevInsulinModelEnabled: true
* afrezzaInsulinModelEnabled: true
* includeServicesInSettingsEnabled: true
* mockTherapySettingsEnabled: false
* nonlinearCarbModelEnabled: true
* observeHealthKitCarbSamplesFromOtherApps: false
* observeHealthKitDoseSamplesFromOtherApps: true
* observeHealthKitGlucoseSamplesFromOtherApps: true
* predictedGlucoseChartClampEnabled: false
* remoteOverridesEnabled: true
* scenariosEnabled: false
* sensitivityOverridesEnabled: true
* showEventualBloodGlucoseOnWatchEnabled: true
* simulatedCoreDataEnabled: false
* siriEnabled: true
* automaticBolusEnabled: true
* manualDoseEntryEnabled: true
* allowDebugFeatures: false
* simpleBolusCalculatorEnabled: false
* usePositiveMomentumAndRCForManualBoluses: true
* dynamicCarbAbsorptionEnabled: true
* adultChildInsulinModelSelectionEnabled: false

## Alerts
**Empty Reservoir**

* identifier: Omnipod:pumpFault.Fault Event Code 0x18: Reservoir empty or exceeded maximum pulse delivery
* issued: 2023-02-05 09:48:44 +0000
* acknowledged: 2023-02-05 09:48:46 +0000
* retracted: n/a
* trigger: immediate
* interruptionLevel: timeSensitive
* foregroundContent: {"title":"Empty Reservoir","acknowledgeActionButtonLabel":"OK","body":"Insulin delivery stopped. Change Pod now."}
* backgroundContent: {"title":"Empty Reservoir","acknowledgeActionButtonLabel":"OK","body":"Insulin delivery stopped. Change Pod now."}
* sound: n/a
* metadata: n/a

**Loop Failure**

![B20FA9AF-245B-4305-A7A6-49177613DE0B](https://user-images.githubusercontent.com/52126870/217651256-6175d8dc-b7b4-4fc6-b334-6a4558ab0f1e.png)

**Comment by Jemzor** [comment]
Apologies but having spent half an hour trying to figure out how to upload the crash report file through GitHub, I have come unstuck as I cannot find an upload command. Please advise.

**Comment by ps2** [comment]
You may need to share to your computer, and then attach. The mobile github page doesn't like to let you attach non-image files other than zipped archives.

**Comment by Jemzor** [comment]
[Loop fault reports.zip](https://github.com/LoopKit/Loop/files/10710365/Loop.fault.reports.zip)

See attached 3No files. Please note there have been two different types of crashes:
1. The frequent crashes described earlier where it kicks me out of Loop and onto the homescreen. This could happen at any point, including when priming a pump.
2. Less frequent crashes - where it notifies me within the app that a crash has happened

**Comment by ps2** [comment]
I see iOS killing Loop in your crash logs.  There is an attempt at fixing this in progress.  If you would be up for building and installing the `hk-auth-crash-fix` branch of LoopWorkspace, I'd love to know if this fixes your issue.  See https://loopkit.github.io/loopdocs/version/loopworkspace/?h=branch#clone-loopworkspace as a guide if you're not familiar with building a specific branch.

**Comment by scottf51** [comment]
Just wondering if we understand the  trigger for this bug ? I was about to upgrade from Dev late last year to 3.0 , but if there are HealthKit issues I may hold off. I didn’t see large scale reports of this on the groups Sent from my iPhoneOn 14 Feb 2023, at 13:48, Pete Schwamb ***@***.***> wrote:﻿
I see iOS killing Loop in your crash logs.  There is an attempt at fixing this in progress.  If you would be up for building and installing the hk-auth-crash-fix branch of LoopWorkspace, I'd love to know if this fixes your issue.  See https://loopkit.github.io/loopdocs/version/loopworkspace/?h=branch#clone-loopworkspace as a guide if you're not familiar with building a specific branch.

**Comment by ps2** [comment]
There is a long standing issue where we see Apple Health delivering thousands of delete records to Loop, causing freezing in Loop, crashes, and sluggishness or freezing in the Apple Health app. I recently was able to reproduce that situation thanks to a user who was experiencing the issue sharing a lot of debug logs with me.  It looks like the situation happens when we start an anchored health query when we don't have an existing anchor to start from. I'm not exactly sure what situations are causing Loop to lose its query anchor, but it's probably a situation we should be able to handle. The change being tested in the `hk-auth-crash-fix` branch is mainly a change to batch process these deletes, rather than trying to consume them all at once, which is choking Loop and Health.

**Comment by scottf51** [comment]
After turning it off I had to reboot as the Apple health service crashed so hard it could not recover , it apparently didn’t like being fed 1000s of entries a sec …Sent from my iPhoneOn 14 Feb 2023, at 14:44, Pete Schwamb ***@***.***> wrote:﻿
There is a long standing issue where we see Apple Health delivering thousands of delete records to Loop, causing freezing in Loop, crashes, and sluggishness or freezing in the Apple Health app. I recently was able to reproduce that situation thanks to a user who was experiencing the issue sharing a lot of debug logs with me.  It looks like the situation happens when we start an anchored health query when we don't have an existing anchor to start from. I'm not exactly sure what situations are causing Loop to lose its query anchor, but it's probably a situation we should be able to handle. The change being tested in the hk-auth-crash-fix branch is mainly a change to batch process these deletes, rather than trying to consume them all at once, which is choking Loop and Health.

**Comment by ps2** [comment]
It may be that Loop is contributing to the issue in Apple Health when Dexcom One reports many values, as without the `hk-auth-crash-fix` changes, it will ask Apple Health for *all* the updates since it last got anything. Apple Health attempting to read all those into memory at once, and send them to Loop all at once is what was causing the memory issues, and hangs.

**Comment by scottf51** [comment]
Sure , I guess the weird thing is I could clear everything (fully clear Apple health and reinstall Dexcom one ) and then use Dexcom one for a couple of weeks and then it would just do the same . Dexcom 6 didn’t , I assumed in some way Dexcom one was not understanding or remembering the ack from apple health  and thinking it needed to send everything every time. Over a period of days that number it sends seemed to get higher and higher until it hit a point where apple health couldn’t cope, at that point you couldn’t even view health data. Loop may well make they worse as you said, but seems there is not reason to send it from Dexcom one in the first place , it might think it’s backfilling , but it’s backfilling data that already made it as far as I can see , just all data since you installed . Sent from my iPhoneOn 14 Feb 2023, at 15:00, Pete Schwamb ***@***.***> wrote:﻿
It might be that Dexcom One reporting many values in a fast manner is fine (it is likely not making one single large storage request), but in combination with Loop trying to eat them all at once, that causes issues.

**Comment by Jemzor** [comment]
> I see iOS killing Loop in your crash logs. There is an attempt at fixing this in progress. If you would be up for building and installing the `hk-auth-crash-fix` branch of LoopWorkspace, I'd love to know if this fixes your issue. See https://loopkit.github.io/loopdocs/version/loopworkspace/?h=branch#clone-loopworkspace as a guide if you're not familiar with building a specific branch.

Are there any instructions for building this branch using browser? Otherwise this will be very difficult on the eyes using VM.

**Comment by darkcharl** [comment]
FWIW I have a very similar setup and the `hk-auth-crash-fix` appears to address the previous crashes. We also use Eros + Dexcom G6 and just built 3.0 using this branch.

**Comment by marionbarker** [comment]
The hk-auth-crash-fix is merged into dev branch. 

It can be built with browser build. 

https://loopkit.github.io/loopdocs/gh-actions/gh-update/#github-build-for-dev

**Comment by Jemzor** [comment]
Thanks Marion.

Just to update this end, having just moved to the DASH, I am having the same issue with this problem as I was having with Eros.

**Comment by darkcharl** [comment]
I'm about to switch over to Dash in a few minutes, I'll keep you posted if the hotfix works there as well.

**Comment by darkcharl** [comment]
Works like a charm!

**Comment by Jemzor** [comment]
Running 3.1.0. No crashes so far 👍
