### ISSUE TITLE
Issues with 3.2.1 Build

### ISSUE THREAD

**Issue by MattBennettLoop** [LoopKit/Loop#1971]
Just built loop for the first time this morning, Everything seemed to go fine and I have it installed on my phone and running with pump simulator. I did get this email from apple about the build and want to make sure all is ok. I don't plan on using Siri with loop so maybe not a big deal?
![image](https://user-images.githubusercontent.com/129136309/228363554-e990c565-2ee8-4544-b105-049f51d64fa1.png)

**Comment by aolde** [comment]
I had the same error and the issue was that the app had been marked as available for macOS (hence the error message). 

Make sure the following checkbox is unchecked:

<img width="890" alt="image" src="https://user-images.githubusercontent.com/142856/229057109-b57d20ff-44f3-4962-aaea-cf598e4a7789.png">
