### ISSUE TITLE
Removing Omnipod has no confirmation

### ISSUE THREAD

**Issue by circus-real** [LoopKit/Loop#1977]
When a user wants to replace a pod, they first need to remove the previous one.
There is no confirmation for doing this and it is possible that it could be done accidentally or maliciously.

To fix this, ID confirmation (e.g. Touch ID) could be implemented in the same way as when bolusing manually.

**Comment by Trpl7ca** [comment]
After deactivating a pod, I will ofter leave it on for a while so that any recent insulin will be absorbed.  Sometimes taking off the pod causes slight bleeding and maybe loss of delivered insulin.  I just put the new one in a different place. It seems like selecting replace pod followed by the large red button Deactivate is a pretty good warning. Just my opinion
