### ISSUE TITLE
Conflict between override and pre meal preset range

### ISSUE THREAD

**Issue by SjpStanley** [LoopKit/Loop#1987]
**Describe the bug**
Setting an override with  new target range  when meal pre-set range is already set results in both normal and override ranges being displayed.  If you set override first then set the meal preset range then it cancels the override which I assume is intended behaviour.

**Attach an Issue Report**
Struggling to upload from phone, will do from PC later.

**To Reproduce**
1.  Define pre-meal range
2. Set an exercise type override with higher target range.
3. Activate pre-meal preset
4. Activate above exercise override
5. Display is as per screenshot.

**Expected behavior**
would only expect to see future range set as per override.

**Screenshots**
Attached.

**Phone**
 - Hardware: iphone13 pro
 - OS Version: 16.3.1

**Loop Version**
 - Version Number: 3.2.1
 - Repo: [LoopKit/Loop, Katie, etc]

**CGM**
 - Device: libre2
 - Manager app: xDrip4iO5

**Pump**
 - Manufacturer: Omnipod
 - Model: Dash
 - Firmware version: [e.g. 2.3A 1.1 0B 0B]

**Additional context**
![E3BD73F9-A836-47D0-8AF2-05F6CE84F736](https://user-images.githubusercontent.com/42674521/234390900-a6a3ea08-9161-4bd2-ae3d-6bea0f747065.png)

**Comment by FokkeZB** [comment]
We are running into this as well. When I enable Pre-Mail, it disables any Override, but when I (re)enable an Override after enabling Pre-Mail, they do are both active.

We often use an Override while we are at our cabin, so I'd actually like Pre-Mail to not disable the Override. It's fine for its Target Range to override that of the Override while active, but the other settings of the Override to still be effective, and after the hour or entering a meal, its Target Range again as well.

**Comment by marionbarker** [comment]
I think this issue has not been resolved.

**Comment by live4sw** [comment]
I just wanted to mention that I noticed this issue as well lately. I had activated pre-meal before a large snack, eaten, and then realized I would be taking a long walk in 30 minutes and set a temp override to target 150 bg (my typical pre-exercise override), thinking it would shut off the pre-meal setting. 30 minutes as I walked out the door, I realized I still had a lot of active insulin because the pre-meal setting was still working. Fortunately I noticed and had some additional carbs before I left. I don't think it's logical behavior for it to be possible for both settings to be enabled, particularly when doing the inverse shuts off the temp override when pre-meal is selected.
