### ISSUE TITLE
critical pod errors

### ISSUE THREAD

**Issue by sepret932** [LoopKit/Loop#1994]
I've been looping for around a month and a half now, and I've had 4-6 pods fail (including the one from this morning). They usually fail with a little less than a day left. Here's the report:
[Loop Report 2023-05-08 17_19_47+09_30.md](https://github.com/LoopKit/Loop/files/11419190/Loop.Report.2023-05-08.17_19_47%2B09_30.md)
Is there any solution for this? Thanks!

**Comment by NickyJoel** [comment]
I’ve noticed this is the same error I get too, the 0xcb fault. There is a separate thread for this specific error, please also post your report there. 

Some suggestions were to have a target range instead of a set number as it is suspected it is a battery issue as loop sends so many more commands but for me it’s basically every other pod and usually four hours before I hit the 72hours. There are more suggestions in the thread.

**Comment by marionbarker** [comment]
I parsed the Loop Report from @sepret932 and I agree with @NickyJoel.

You have a very tight range (5.6 to 5.6 mmol/L) starting at 7 am that runs for the rest of the day. If you open up the range to a wider target, it might decrease the number of messages enough to get better results.

Please close this issue.
