### ISSUE TITLE
Carb entry, food type number of characters limit 

### ISSUE THREAD

**Issue by paddingtonil** [LoopKit/Loop#2048]
Build ca36d07 limits the number of characters that can be entered into the food type field. 
![IMG_2093](https://github.com/LoopKit/Loop/assets/54187576/f6c209df-362a-4eff-b9e5-da556a88c098)

**Comment by marionbarker** [comment]
I tested tonight. I could type in 20 alpha numeric characters or 10 food emojis for food type on the add carb entry screen. 

When adding a new Favorite food, I was able to enter a name with 51 characters before I got bored. I had to turn the phone to landscape to see the full field. The food type row has the same 10 emoji, 20 alphanumeric limit. 

I know an older version allowed more food type characters (because my 3-year old granddaughter entered a gazillion emoji on a test device.). This may be a planned modification rather than a bug. 

Are there users who need more characters in the field? If so, is adding that to favorite foods name sufficient?
