### ISSUE TITLE
Omnipod Dash Pod Failure to Start

### ISSUE THREAD

**Issue by aidan-gibson** [LoopKit/Loop#2116]
**Describe the bug**
I had three pod errors when trying to start session (two said "incorrect response" and the pod started beeping, the other paired but didn't insert). I've never had this happen before, I'm attempting to get the three replaced here https://insulet.my.site.com/PodderCentral/s/support-request but it's asking for a reference number. What should I put in? Is this somewhere in Loop's logs?

**Issue Report**
[Loop Report 2024-01-11 15:59:46-08:00.md](https://github.com/LoopKit/Loop/files/13909710/Loop.Report.2024-01-11.15.59.46-08.00.md)

**Phone**
 - Hardware: iPhone 14 Pro Max
 - OS Version: 17.2.1

**Loop Version**
 - Version Number: 3.3.0
 - Repo: LoopWorkspace dev branch

**CGM**
 - Device: Dexcom G7
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Insulet
 - Model: Omnipod Dash

**Comment by marionbarker** [comment]
I examined the Loop Report. The failure was at a lower level than is reported in message logs.

1. I see a nominal deactivation at 2024-01-11 12:09:30 (UTC) of one pod that completed 72 hours of operation.
2. The next message exchange is a request to pair at 2024-01-11 12:28:35 (UTC) which then proceeds normally including an insertion. That pod had been active 11.5 hours at the time you issued the log report (at 2024-01-11 23:59:31 UTC).

I do not see any sign (in this log) of the intermediate pods.
There is also no record a pod that paired and primed but then stopped communicating.

If Loop does not detect a pod, there is no message exchange. This would be the same as with a PDM if it failed to find a pod.

The fact that a pod started to beep is a sign that you filled it with sufficient insulin to "wake" up the pod. It is not caused by any communication from Loop (or the PDM). The pod will continue to beep until it completes the pair, prime and insertion steps.

There is no reference code to report.

**Comment by aidan-gibson** [comment]
Darn. Thank you for checking!
