### ISSUE TITLE
Too much insulin?

### ISSUE THREAD

**Issue by pbackstrom** [LoopKit/Loop#2122]
I had a quick and very severe low today, around 6:05.  It seemed too bad to be caused by a) just the 4+units I got from boluses and certainly than the 2+units shown on board at the time.  I wondered if the boluses were too much although I think I was on 150% temp.

I am wondering if you might be able to check to see that I wasn't given more insulin than I should have had.  Another possibility is that the pod injected more than it was told to do, which of course Loop wouldn't have known about.  It just felt like a ton of insulin was in my system, and I gobbled at least 10 glucose tablets without a huge rise (usually 1 or 2 tablets is enough)

v3.2.3(4) on iPhone 11, Dexcom G6, Omnipod Dash.  Both algorithm experiments on.
[Export-20240128T025228Z.zip](https://github.com/LoopKit/Loop/files/14075070/Export-20240128T025228Z.zip)
![IMG_1778](https://github.com/LoopKit/Loop/assets/53927407/a07f744b-98d0-48c1-a437-970ce35797f9)
![IMG_1779](https://github.com/LoopKit/Loop/assets/53927407/31bbdbde-dc96-47db-baec-ec539bf339a0)
![IMG_1781](https://github.com/LoopKit/Loop/assets/53927407/baaf42f6-2bcc-4e29-ac2d-4053236d7e4a)
![IMG_1780](https://github.com/LoopKit/Loop/assets/53927407/f6093f0c-144e-42d9-ac1a-6ad4fa46e665)

**Comment by marionbarker** [comment]
I will review your files.

**Comment by marionbarker** [comment]
Did I understand you to say you were running a 150% insulin needs override? That can be more aggressive than you may think because you are that increases what Loop treats as your scheduled basal (which affects reported IOB) and lowers the ISF so that corrections are stronger (1.5 times as much insulin) as you would get without the override.

If you can upload a Loop Report - it makes part of the analysis easier. (Loop, Settings, Support, Issue Report).

**Comment by pbackstrom** [comment]
It wouldn’t let me upload the .rd file.  Let me know what to do, thanks.

**Comment by marionbarker** [comment]
Can we switch to PM on zulipchat - sending you a message.
