### ISSUE TITLE
how i can calibrate Libre2 from loop

### ISSUE THREAD

**Issue by boshetyn** [LoopKit/Loop#2132]
3.2.3 version loop
CGM source - libre

how i can calibrate Libre2 from loop?

**Comment by bashjs** [comment]
There is an option (a "Feature") in the [LibreTransmitter submodule](https://github.com/dabear/LibreTransmitter/blob/main/Features.swift#L22) that enables factory calibration editing.

There are two ways how to enable Libre calibrations in Loop:

a) Enabling factory calibrations
- You have to fork the [`customizations`](https://github.com/bashjs/customization/blob/dev/libre_manual_calibration/libre_manual_calibration.patch) and [`lnl_scripts`](https://github.com/bashjs/lnl-scripts/commit/1aa19534098496b5661756d68fd0e974bf76f9e1) repositories and add your custom submodule customization
- Either include your customization via `build_loop.yml` (if you do browser builds) or build Loop via XCode with the modified LibreTransmitter submodule.

b) Add xDrip4iOS as a CGM source via loop-and-learn community [customizations](https://www.loopandlearn.org/custom-code/#add-cgm-browser)

**Comment by Sahar313** [comment]
Hello. Can you please teach me step by step how to do it? I really need this feature and I have no idea about coding in github. I tried and searched for hours but couldn't figure it out. I'm sorry for the inconvenience and thanks. 

> There is an option (a "Feature") in the [LibreTransmitter submodule](https://github.com/dabear/LibreTransmitter/blob/main/Features.swift#L22) that enables factory calibration editing.
> 
> There are two ways how to enable Libre calibrations in Loop:
> 
> a) Enabling factory calibrations editing
> 
> * You have to fork the [`customizations`](https://github.com/bashjs/customization/blob/dev/libre_manual_calibration/libre_manual_calibration.patch) and [`lnl_scripts`](https://github.com/bashjs/lnl-scripts/commit/1aa19534098496b5661756d68fd0e974bf76f9e1) repositories and add your custom submodule customization (these are the examples of the forks I made)
> * Either include your customization via `build_loop.yml` (if you do browser builds) or build Loop via XCode with the modified LibreTransmitter submodule.
> 
> b) Add xDrip4iOS as a CGM source via loop-and-learn community [customizations](https://www.loopandlearn.org/custom-code/#add-cgm-browser)
> 
> Since Libre support is not in the `main` branch yet, I'd suggest adding the modification "xDrip4iOS as a CGM". The latter will provide a better calibration experience as well.

**Comment by kkazle** [comment]
Who are you?Kaylee’s phone💯💯💯On Jan 10, 2025, at 10:36 AM, Sahar313 ***@***.***> wrote:﻿
Hello. Can you please teach me step by step how to do it? I really need this feature and I have no idea about coding in github. I tried and searched for hours but couldn't figure it out. I'm sorry for the inconvenience and thanks.

There is an option (a "Feature") in the LibreTransmitter submodule that enables factory calibration editing.
There are two ways how to enable Libre calibrations in Loop:
a) Enabling factory calibrations editing

You have to fork the customizations and lnl_scripts repositories and add your custom submodule customization (these are the examples of the forks I made)
Either include your customization via build_loop.yml (if you do browser builds) or build Loop via XCode with the modified LibreTransmitter submodule.

b) Add xDrip4iOS as a CGM source via loop-and-learn community customizations
Since Libre support is not in the main branch yet, I'd suggest adding the modification "xDrip4iOS as a CGM". The latter will provide a better calibration experience as well.
