### ISSUE TITLE
Incorrect glucose prediction with change to daylight saving time

### ISSUE THREAD

**Issue by thebookins** [LoopKit/Loop#220]
This morning I noticed that Loop was incorrectly predicting a very negative eventual glucose (see pic below). This was after a breakfast bolus of 4.7 U for 67 g of carb at a carb ratio of 14 g/U. As can be seen from the image, active carbs and insulin are matched and should not result in an eventual glucose of less than -6 mmol/L (-108 mg/dL)!
![image](https://cloud.githubusercontent.com/assets/12263040/19182911/8b16825a-8cc1-11e6-95a2-ee468ef13a02.png)

So I had a look at the Issue Report and it turns out that in DeviceDataManager the timeZone is "GMT+1100 (fixed)", which is correct, but in CarbStore we have the following:
```
 carbRatioSchedule: ["items": [["startTime": 0.0, "value": 27], ["startTime": 21600.0, "value": 14], ["startTime": 34200.0, "value": 23], ["startTime": 43200.0, "value": 23], ["startTime": 54000.0, "value": 26], ["startTime": 63000.0, "value": 26]], "timeZone": 36000, "unit": "g"]
```
The timeZone field for the carbRatioSchedule is 36000, which translates to +10. The consequence of this is that (I imagine) the code that calculates the eventual BG looks up the carb ratio 1 hour earlier, which in our case returns a value of 27, not 14. (The carb ratio from midnight to 6 am is never used as our son is asleep, so it has not been adjusted for some time.) Using this data, Loop concludes that IOB is too high for  the active carb and hence the low prediction.

In Sydney we moved to daylight savings time last weekend. It appears that this change does not propagate through all of the elements of Loop. Incidentally, this evening I used Loop to change the time on the pump (through the RileyLink interface). This seems to have reset all of the timeZone fields, which now read 39600 (a timezone of +11 in seconds).

**Comment by ps2** [comment]
For the sake of coherency, Loop makes all of its scheduled decisions in sync with the pump's view of the clock.  This is so that basal schedules and carb schedules are in sync. 

I think this is behaving as designed.  One thing that might help with this is to make your carb ratio in the early morning at least be something closer to what you actually would expect if your son were to eat carbs earlier.

Thanks for reporting this in such a thorough way! I think what you've deduced is correct.

**Comment by thebookins** [comment]
Thanks @ps2. After filing the issue I wondered whether this was the design intent. The complicating factor here is that my son changed the time on the pump for daylight savings time without us knowing. Is the intended behaviour always to change time through Loop? And if so, would it be worth checking the pump time periodically and alerting if it deviates from the iPhone time by some amount?

**Comment by ps2** [comment]
Yes, changing through the app is definitely preferred.  The reason we don't check and alert is that when traveling through different timezones it's often desired keep the pump on your original timezone for at least some period of time, as it takes time for your body cycles to change.  And for short trips of a day or two, you might not want change it at all.

**Comment by ps2** [comment]
For anyone else encountering this ticket, here's a good resource regarding Loop and timezones/time changes. https://github.com/LoopKit/Loop/wiki/Time-Zone-Support

**Comment by thebookins** [comment]
Agreed. However, since we know UTC time and the pump's time zone through the phone, we could still test that the pump's time is consistent even though the app's timezone could be different. Not a huge priority but perhaps a useful check in case a user inadvertently changes the time through the pump.

**Comment by CrushingT1D** [comment]
I had an extensive conversation and debug session with Nate on this a couple weeks ago. Here in australia at least one of the mobile providers changed their clock several times overnight during spring forward. This screwed things up later. No idea if your problem was related but if your timestamps on reservoir jumps back and dorth issues ensue. Since i dont trust the mobile providers to do proper clock changes i set my ios settings for manual instead of auto update.
