### ISSUE TITLE
Allow bolus below Target Range via user setting

### ISSUE THREAD

**Issue by CrushingT1D** [LoopKit/Loop#223]
Many (dozens, as found in history of Gitter channel) of users have expressed a desire to have the Loop bolus wizard pop up with a suggested bolus even if their current BG is below the bottom of the Target Range. Users indicate their desire to bolus in preparation for an upcoming meal, even if their BG is below that target as long as they are not "low". Different users have different values to what they consider to be "low".

The concept is to add an an optional setting that allows the user to enter BG value to indicate their preference. Single field entry for BG (in preferred units as determined by which unit value is used in BG in Apple Health) 
- If the lower of currently or any future predicted BG is at or below entered value, then do not suggest a bolus
- If the lower of currently or any future predicted BG is above the entered value, then attempt to recommend a bolus and display to the user if one is in fact suggested
- If no value is given by the user, then use the bottom of the Target Range (as it works today).

As to not add additional entries to an already long list under Settings, this could live under the Maximum bolus setting.

If the community supports this feature design, I will code up and submit a PR.

**Comment by ps2** [comment]
It does seem that what people consider 'low' is often lower than the bottom their target range.  I've been thinking about what that means.  The bottom of our target range is also higher than we would treat for. 

What is the reason for this?  Should the bottom of the target range be the value we'd consider treating for a low?

**Comment by beached** [comment]
I am of the mind that the number shouldn't be below 3.9mmol/L/70mg/dl without hacking the code.

**Comment by beached** [comment]
Also, why not under target range settings?  Like workout but with a different lable?  It's where I would look for it

**Comment by loudestnoise** [comment]
I support this idea Mr. Crushing T1D.

**Comment by beached** [comment]
Sensor calibration error, blood test error and tue calibration factors being out.  So my range is 5.2 to 5.8 to keep it around 5.5.  But if i dip below as far as 4mmol oh well.  Target is the goal but im safe to about 4mmol

**Comment by scottleibrand** [comment]
@ps2 with oref0 we use a target range of 100-100. The only benefit to a wider range would be to minimize the number of temp basals set. We would rather maximize time in range by getting the algorithm to temp aggressively as soon as it sees any indication of predicted BG going low or high. If the Loop target range were only used for setting temps, and the minimum allowed BG for recommending boluses were separate, I suspect Loop users would find something similar: that they can maximize time in range by setting a very narrow target range.

**Comment by beached** [comment]
@scottleibrand how does oref0 deal with sensor error?  Is it based on more than 1 value?

**Comment by scottleibrand** [comment]
Our primary calculations are based on just the most recent value. However, deltas are calculated comparing the current value to three different options: the five minute ago value, the average of the values from about 15 minutes ago, and the average of the values from about 30 minutes ago.  We use the minimum of those three Delta when determining how to modify the dosage calculated from the current value + IOB * ISF. So, for example, if the BG starts falling, we will react very quickly to that and will begin low temping (or canceling high temps) immediately. On the other hand, if BG starts to rise, don't take that fully into account until it shows up in the 30 minute average.  The net result of this is that we will vary the temp basals more when BG data is highly variable, but are overall very good at preventing any overreactions for more than a few minutes from such variable data. And we bias towards being conservative against any high temps that might become problematic  if we lose connectivity and they are allowed to run for the full 30 minutes.

**Comment by ps2** [comment]
I would support a change that always pops up the bolus interface, but adds more information to that screen so that the user can decide what to do.

To make an informed decision, the following pieces of information would be very useful.

* IOB
* If a low (below target range) is predicted, what is the min bg, and at what time. This should be displayed in a highlighted fashion, to be noticed as a warning.
* Bolus amount calculated to bring eventualBG back into range.

I think this is simpler from both a coding standpoint and from a user burden standpoint.

**Comment by beached** [comment]
One thing to keep in mind too is that the pump already will do a subtraction of insulin for a bolus that falls below target range but isn't low.

**Comment by CrushingT1D** [comment]
@ps2 I believe that the range used by Loop is not high/low marks. I believe the way Loop works is that it tries to adjust your BG to the center point of your range IF you are out of the range. However, if you are inside this range then Loop will NOT try to adjust you to the middle anymore. I believe this was done by design as to not constantly be adding battery drain and excessive very small temp basals on the system. 

Due to this, I personally use a tight range with a 10-20 point mg/dl gap such as 90-100, but not use something like 100/100. 

An alternate idea I have discussed offline would be to allow the user to enter a target point rather than the average of the range. Then the range could remain as is and bolus decisions could be based upon that value. We could use some sort of rounding or averages to figure out how much standard deviation from the target BG is optimal for both user and battery life.

**Comment by beached** [comment]
@CrushingT1D Not just battery but memory.  Lots of little adjustments create a load of history records. 

But I agree, and a non-diabetic does not have a rigid flat line of glucose and that should not be the goal.  I like the idea of a target scalar and a setting for the tolerance from that value.  The only caveat is that the target - tolerance > the log bg mark(e.g target 5.5mmol/L with a tolerance of +-0.5mmol/L would not go below the low mark of 4mmol/L)  Not sure of the correct way to deal with this though

**Comment by CrushingT1D** [comment]
Hoping others will chime in on my last alternative idea in comparison to the initial suggestion and Pete's. I am not convinced that Pete's suggestion is easier to implement since it will require a new screen with messaging, content, visualizations and design, but if the group prefers that method usability wise I am happy to consider it.

**Comment by ps2** [comment]
@CrushingT1D Yes, for temp basals Loop uses the mid point of your range.   For boluses it corrects to the top of the range. 

The original focus of this ticket was to allow boluses when below range.  I think we can do that without changing fundamental aspects of how Loop does its calculations, or adding new configuration. 

The modifications I proposed do not involve a new screen, or visualizations.  Just additional text on the bolus entry screen, showing IOB, and info about the low (if one is currently happening or predicted to happen).

**Comment by CrushingT1D** [comment]
ok, let's see what others prefer. For me and my abilities it will be more work to do it this way, but happy to go with the flow.

**Comment by walker0** [comment]
I value the suggestion that @CrushingT1D  has made regarding a new way of determining range and targets and I would be interested to see it implemented and the effectiveness of it. 

However at this point I believe a nice big red warning message on the Bolus screen when predicted is below range (with a switch in settings to enable bolus below range) would be a good short term item to implement.

**Comment by jlucasvt** [comment]
I have aided a number of active users to modify the DoseMath.swift to provide a bolus recommendation when they are Below BG Target.  The issue typically pops up within a day or two of closed loop therapy.  Users voice a concern that they are not getting a bolus recommendation after Carb Entry.

**[My Below Target Modification is Here](https://github.com/jlucasvt/Loop/blob/master-0.13/Loop/Managers/DoseMath.swift#L162-L165)**  

I try to come at this from the perspective of YDMV (thanks @loudnate for that perspective).  I know that my chosen setting for this of 70 mg/dl may not be what others choose for either safety or treatment choice.  I also know that my chosen target of 95 - 100 is also my choice.  The key is having a choice. 

By not having this choice users are almost always confused why Loop is not providing a bolus recommendation.

I think adding an override setpoint in the Target Range settings (like Workout Target) to allow "Bolus Wizard Range" would be very helpful.  Until then I will continue to modify my 1 line of code and comment out the var that is unused...

![img_6132](https://cloud.githubusercontent.com/assets/19819388/19273280/f16bf29e-8f99-11e6-8c60-13c631f28d34.jpg)

**Comment by ps2** [comment]
Sounds like maybe I haven't communicated what I'm proposing well enough. With what I'm proposing, Loop *will* propose a bolus if you are currently below range, or will go below of range, but your eventual bg is above range.

I see the addition of another setting that the user has to set up as a source of *more* questions.  What I'm proposing keeps the existing idea of a single target range, but answers the following questions for new users:

* Why didn't bolus interface come up? - This will no longer be a question, as it always will come up.
* Why is it not suggesting a bolus? - This will be less frequent, as we *will* suggest a bolus when there is a predicted low, as long as the eventual BG is predicted to be above range. And the user will be alerted that there may be a low, which I think is important.
* Why is the suggested bolus 0? - There will be cases where the eventual BG is predicted to be below range.  In this case, I don't think Loop should suggest a bolus. If you encounter this and think that Loop should be suggesting a bolus, I think it's likely that there are probably other parameters that need to be tuned.

This solves the user expectation of the bolus wizard always coming up after entering carbs, provides good bolus amount suggestions when below range and adding carbs (with a warning), and gives the user an explanation for those cases where Loop shouldn't recommend a bolus amount.

Hopefully that clarifies it more.  I think it addresses the original concerns and questions that users have.

Tweaking Loop for a more nuanced view / treatment methodology using multiple bg ranges is an interesting idea, but I think it's orthogonal to the main questions that users have, and would be better worked on as an experiment, since I think it opens up a lot more questions than it answers.

**Comment by ps2** [comment]
Since this is an issue I need solved for myself as well (and those who care for Riley), and I don't think it's a huge change, I can tackle it.  I am certainly not expecting you, @CrushingT1D, to implement my requests; I'm just proposing alternates for the sake of discussion, and will follow my proposal up with some code. :)

And an actual PR that people can try out will probably clear up any ambiguity about what I'm talking about as well.

**Comment by jlucasvt** [comment]
@ps2  Thank you for your clarification. I believe this would resolve my issues with the current system.  By "eventual BG" you mean the last predicted BG value in the future.   I think this would cover 99% of my use case, especially with being able to vary my target for the day ranges as I already do.  It solves the biggest issue of all which is "Why didn't the bolus interface come up?".

**Comment by CrushingT1D** [comment]
How would this solution deal with a BG that is predicted below range but eventual is in range. Example user who has range of 90-130. They are currently 91, but if they bolus we predict they will drop to 68 before eventually finishing at 125? Same question if they are 75, going to drop to 53 before eventually finishing at 110?

This question is why i was assuming some visualization may be needed if we are auto popping the wizard all the time.

**Comment by CrushingT1D** [comment]
I the the safest solution may be to implement both a user setting (don't allow bolus if i am at or expected to go below ___) and added info on the bolus screen all the time it does pop up. It could be split into two PRs.

**Comment by ps2** [comment]
For both your examples, if BG is predicted to go below range, but end up in range, there would be no bolus required, so the UI would show 0 recommended, and show a warning about the predicted low. "Low BG of 68 predicted in x minutes".

**Comment by ps2** [comment]
Yes, I think playing with alternate dosing strategies is a bigger, separate deal. :)  And they're not mutually exclusive (they're orthogonal! ;).  We can solve the main issue with a small change to behavior and give the user more information. 

Using a different target could be tried out independently, and should, I think there are some other questions it raises, like do you use it for both temp basals and boluses?  Can you set a 'schedule' of targets? Etc...

**Comment by johnmales** [comment]
I agree with the approach that @ps2 has suggested, which is similar to what I suspect most will expect when dealing with some form of bolus wizard. The currently confusing behaviour of the app is not suggesting a bolus when one would "normally" be given, and not bringing up the bolus wizard. 

The common scenario is blood glucose below target range but still "acceptable" with carbs being ingested. Under this circumstance insulin is likely to be required and the bolus wizard should suggest insulin based on the eventual blood glucose.

The other common scenario is where the blood glucose is already "low", and I expect most will wait until blood glucose is "acceptable" before bolusing, however "low" and "acceptable" are defined.

**Comment by elnjensen** [comment]
I think the solution proposed by @ps2 would work well for me.  Info about IOB and predicted BGs would definitely be helpful there.   Another thought would be to also explicitly show the negative correction as the pump bolus wizard does - I sometimes find myself trying to puzzle out exactly how the suggested bolus was determined.   To some extent that's a separate issue, but related to the overall theme of having more info right in front of you when bolusing. 

Thanks, @CrushingT1D for bringing up this issue.

**Comment by ps2** [comment]
This is what I'm working on right now:
<img width="375" alt="main_storyboard_ _edited" src="https://cloud.githubusercontent.com/assets/14649/19296655/e1f77afe-9002-11e6-8645-e32d939a2b24.png">

**Comment by dm61** [comment]
I think the approach proposed by @ps2 and illustrated by the screen above would work really well. Including IOB on the Bolus screen is also a great idea. One minor issue would be the case when the lowest predicted bg is now, i.e. at time zero. In that case, the message would look a bit awkward, e.g. "Low BG of 48 predicted in 0 minutes...." but that's fine - I do not think this would confuse anyone or require a special-case announcement.

**Comment by eszcloud** [comment]
In @ps2 's example above, I think it would be helpful to have a few more fields:  recommendation based on carbs and recommendation based on correction of eventual bg.

**Comment by eszcloud** [comment]
I like @CrushingT1D 's idea to have that info all the time in the bolus screen regardless of prediction and to be particularly in the spirit of YDMV. 

Having Loop do as much of the bolus arithmetic as possible is helpful. Even if the user will override it, it makes decisions more informed. 

One place that comes to mind immediately is that if a blood sugar is high and I correct, I'll get extremely low predictions based on the bolus because I take into account decreased insulin sensitivity for high blood sugars. (This may be a place to enhance Loop's prediction algorithm as I don't think that this is in there yet.) If during that window when I see really low predictions I eat something, I still want to bolus for the carbs and having the arithmetic done for me would be very helpful even if Loop recommends a 0 u bolus as it eliminates having to pull out a calculator to precisely calculate the dose for 1 u to x g CHO. Giving information as @ps2 suggested makes this easier.

**Comment by CrushingT1D** [comment]
My example did have a recommended bolus that was taken into account.
" They are currently 91, but **if they bolus** we predict they will drop to 68 before eventually finishing at 125?"

If they did not bolus in this example they would spike to 200+

**Comment by CrushingT1D** [comment]
Sounds like most folks are support @ps2 's solution. Let me know if you'd like any help.

**Comment by eszcloud** [comment]
To calculate the correction, would you use current bg or eventual bg? I know of people who use each, and both would be useful.

**Comment by eszcloud** [comment]
@ps2 What are you envisioning would be in the bolus screen when carbs haven't been entered? Would it provide the calculations for a correction (both + and - depending on whether blood sugar is above or below target)?

**Comment by ps2** [comment]
@eszcloud As it does now, it will provide a recommendation for carbs if your eventual BG is above range.  Otherwise, it will recommend no insulin.

**Comment by trixing** [comment]
I like ps2 suggestion.

My Animas Ping (soon to be replaced by the Medtronic) has a very similar screen on the bolus wizard with all the details.  It also shows for reference though the calculated bolus based on carbs taken so you can verify the math (it's actually on 2 screens as it is a lot of information), e.g.:

IOB: 0.7u

BG (manually entered): 50
Target: 120
ISF: 140
Insulin based on bg: -0.5u

Carbs (manually entered):  30g
I/C: 15g
Insulin based on carbs: 2u

Recommended dose: 2u - 0.5u - 0.7u = 0.8u

Would be nice to have all the detail on the Loop app as well to give some level of confidence.  Especially important it seems when transitioning between systems.

**Comment by ps2** [comment]
Minimum BG Guard has been implemented: #365
