### ISSUE TITLE
Updating loop from 3.2 to 3.4 

### ISSUE THREAD

**Issue by loopsucksballs** [LoopKit/Loop#2240]
Please help again.  I've been trying to update Loop to no avail and now it's expired.  Given my frustrations with Loop updates over the past years my username is Loopsucksballs.  I'm trying to update from version 3.2 to 3.4 and did the steps to add "loop widget extension" but apparently that was not enough.

**Comment by figureskatemom** [comment]
@loopsucksballs Please check your fb private messages.

**Comment by loopsucksballs** [comment]
Thank you.  I tried the corrections and still receive the same error message.  I did not post this in my fb reply but the odd thing is the main program was run 4 days ago successfully in github but I never ran the program.  Also after failing miserably last week Loop started working on my phone for ? reasons.  However, Loop just crashed on my phone this morning so now I just tried again to run the program in Github.

**Comment by marionbarker** [comment]
You do not seem to have done the step to handle the new Identifier found in Loop 3.4.x:
* https://loopkit.github.io/loopdocs/browser/bb-update/#update-from-32x-to-34

I say this because your Build Error Message is:
```
Provisioning profile "match AppStore com.***.loopkit.Loop.LoopWidgetExtension" doesn't match the entitlements file's value for the com.apple.security.application-groups entitlement. Profile qualification is using entitlement definitions that may be out of date. Connect to network to update. (in target 'Loop Widget Extension' from project 'Loop')
```

You may be misinterpreting the successful Build Loop notation seen 5 days ago. Note - that took just over a minute and if you look at it, it says there was no update needed to your workspace (already up to date), so the build was skipped.

Your last successful build of Loop was 3 months ago.

**Comment by marionbarker** [comment]
Please close this Issue. Issues should be used for problems with the code the developers need to evaluate.
Your problem is you need build help. Please use the appropriate channel of your choice. (And it sound like that is Facebook).

* https://loopkit.github.io/loopdocs/intro/loopdocs-how-to/#how-to-ask-for-help

**Comment by loopsucksballs** [comment]
Thank you Marion.  I had done that step already a few times for the new identifier and still receive the same error message.  I apologize if this is not the correct forum for asking these types of questions.  I have tried Facebook as well and just wanted a solution.  Loop is very important to me and am not the best at navigating through Github

**Comment by marionbarker** [comment]
I don’t mind helping you via this thread. Just tap close so it takes this issue off the developer’s list. Closed issues are still there, nothing is deleted. We can keep chatting. 

Please take a screen shot of your Loop Widget Extension Identifier similar to this one in the docs and post it here. If you realize you missed a step when doing this, feel free to follow up with Create Certs and then Build Loop. 

![image](https://github.com/user-attachments/assets/1afcc9cb-344a-44d8-963c-268204178da6)

**Comment by loopsucksballs** [comment]
Thank you for understanding.  This has been a very difficult weekend for me and I know you have better things to do so thank you for any assistance. 

![image](https://github.com/user-attachments/assets/f3d156b9-194b-4a70-9740-51ffb5800d77)
![Loop group](https://github.com/user-attachments/assets/4b5545aa-508e-4c77-964d-d02e6c56fea7)

![image](https://github.com/user-attachments/assets/3806f15a-08e3-4111-bb3a-ff254fca0a5d)

**Comment by marionbarker** [comment]
Those identifiers all have the wrong App Group selected. You created a new Loop App Group instead of using the one that exists. The name doesn't matter - what does matter is the string on the right hand side. The one you created does not have a period between the "com" and your team ID.  Try selecting the indicated app group.

![select_correct_app_group](https://github.com/user-attachments/assets/42a4ab4f-35e7-4314-bb46-f7d9f65f71fb)

Do it for all 4 identifiers:
* https://loopkit.github.io/loopdocs/browser/prepare-app/#add-app-group-to-identifiers

**Comment by loopsucksballs** [comment]
Marion, you truly are a life saver.  It worked!!!!!!!!!!!!!!!!!!!!  I cannot thank you enough.
