### ISSUE TITLE
Predictive alerts

### ISSUE THREAD

**Issue by ddaniels1** [LoopKit/Loop#265]
@ps2 I am committed to getting this going.  I have made contact with a programmer who is wiling to help.  

The idea is simple.  Take the algorithm that already exists in Loop for the prediction trend line and apply it to a dynamic alert.  The problem with a static low glucose alert is the following:

1.   if you set it at 80 mg/dl and you happen to have 5 units of iob at the time with a double down arrow prediction, by the time carbs kick in you will be severely hypoglycemic.  

2.  Alternatively one could set an alarm at 100 mg/dl to mitigate this, but the alarm would be going off in many situation where one crosses slowly below 100 mg/dl and is predicted to level out perfectly at 90 mg/dl.  In this case the alarm is superfluous.  

Therefore, we design a built in alert into loop that is configurable as to the threshold that triggers the alert (i.e. 70,80 mg/dl, ect) and the time into the future the alert will trigger (20, 30 minutes, ect).  Then the alert will sound when for example one is predicted to be < 80 mg/dl 30 minutes into the future.  Until we have a dual hormone system, those of us with young kids could really use this as their drops can be fast and furious.  I might even see this as a way to prospectively manage tricky meals like Pizza.  One could overbolus up front, then use this system to smooth the fall with a little desert and all is well!

Others please comment with ideas as far as this concept goes.

**Comment by ddaniels1** [comment]
Another part of the alarm would be to offer the amount of carb needed as a suggestion.  This would be easy to calculate based on projected insulin on board (IOB) and Insulin to carb ratio at the time the threshold is calculated to be crossed.

**Comment by CrushingT1D** [comment]
In general I have always liked the idea of a correction notification. If Loop does not feel it can act on it's own quick enough then a notification that says "Bolus recommended" or "Carb correction recommended" would be beneficial. I don't think the alert needs to or should specify how much for either. I agree in this case the user would have settings where they could choose timeframe (for lows), snooze time (for how often the alert comes up if you ignore it) and minimum suggested bolus (ie, only alert me if bolus suggested is over 1 unit).

In general, I have thought that https://github.com/LoopKit/xDripG5 can be enhanced to cover more of what the DexcomG5 app does. Specifically around BG related notification customization and possibly as a standalone app (no DexcomG5 needed). My goal would be to have more control over how or when I get alerted. I considered that a separate app, but certainly some of the functionality could be pulled into Loop (since the current version is already part of LoopKit).

**Comment by ddaniels1** [comment]
The advantage potentially of keeping it natively within loop is the ability to utilize the prediction line based on all of the data elements driving that which are collected in loop.  Once could also utilize these data to drive a specific suggestion.  In the most qualitative sense, perhaps "double down arrow" 20 minutes from an alert threshold would suggest to one that they should take a larger carb correction.  We might also think about attempting to be more quantitative so as not to over correct.  For example:
1.  Oliva is 120 mg/dl, predicted in 20 minutes to be < 80 mg/dl.  Utilizing an equation of the form IOB(at the time we will cross threhold) * IC ratio 8 * 0.75 (to account for decay in insulin activity at this point in the cycle), we develop a carb suggestion that can be taken in the present to affect the future. 

![image](https://cloud.githubusercontent.com/assets/18389123/20462259/e0fb85b2-aecc-11e6-9851-14ae4e6c273a.png)


2.  The result of this experiment.  One could also imagine an easy correction that would get one back to the middle of the target range.  In thinking about it might also be useful to subtract the 0 temp basal from the projected iob at the time of threshold in order to better calculate the carb needed to bounce back.  Will be less than if the loop had not been enacted. 

![image](https://cloud.githubusercontent.com/assets/18389123/20462281/879dcb64-aecd-11e6-907f-71b3e05d9949.png)

**Comment by ddaniels1** [comment]
Here is my first Storyboard!  I propose putting the plugin as an option on the settings page.  Could be configurable with several options.  Would pop up an alert on the phone and the watch of course.  Based on the data entered on this screen could even suggest a number of: skittles, bunny crackers, oz of juice to give the T1D to avoid the low and get them trending up slightly.

![image](https://cloud.githubusercontent.com/assets/18389123/20465212/ef30d124-af0c-11e6-9db6-5810a82c03c3.png)

**Comment by ddaniels1** [comment]
My first Storyboard!  This is an example of the user configurable plugin that I think should live as a selectable page from the Settings menu.  Just some initial ideas of what could be configurable, this would allow the user to get a discrete carb suggestion based on their routine of treating lows.  Now it doesn't have to be a low ever! If a low is only theoretical, once can be more aggressive with insulin, with the comfort that they will get an alert if things don't go as planned as far as absorption or insulin activity/site or any of the other variables we never know go sideways.  

![image](https://cloud.githubusercontent.com/assets/18389123/20465267/2e6f09fe-af0e-11e6-9c3b-68ac740c82b9.png)

**Comment by ps2** [comment]
My advice would be to start simple: just alert when carbs are predicted to be needed, based on 2 config items: bg threshold, and how far into the future to look.

**Comment by danibjor** [comment]
I would love to see something like this. We actually talked about it yesterday at home, the option to opt in for local notifications _before_ hitting a low. Just getting a simple notification if you're about to crash would be good enough, but a dynamic alert with a hint saying eat x y now to prevent going low in z minutes would be awesome.

**Comment by danibjor** [comment]
On days like these, it would be much helpful to get a reminder to eat something before crashing - even tough the TB is set to zero and pump will eventually cut insulin when BG is low enough

![16357924_10156118023739988_1827456858_o](https://cloud.githubusercontent.com/assets/2149381/22295382/fba0ee7e-e316-11e6-80b6-9d16cd9beb00.jpg)

**Comment by beached** [comment]
Using carb instead of a large drop in basal also prevents the bounce back afterwards.  This becomes a bigger issue when this happens just prior to a meal and there isn't much in the way of active insulin.

**Comment by rsilvers129** [comment]
I would love to see a "N carbs required" notification and alarm when suspending basal is not enough.

**Comment by Kdisimone** [comment]
changed the title to be more descriptive of the topic

**Comment by rfmurphy81** [comment]
Has anyone been able to give this one some attention? 

I've been wanting a way to have the Loop app give a notification when it predicts BG crosses a user-defined threshold within another user-defined time period based on the prediction line. For example, it would be helpful for me to know whether I'm expected to cross my suspend threshold value (or another value) so I can determine whether to make the decision to carb correct. 

While it'd be nice to provide a suggested amount of carbs, I agree with @ps2 about keeping it simple at first to ensure we can get _something_ out the door versus nothing at all.

**Comment by mgunns** [comment]
I think this feature would be useful as well.

**Comment by Nightfoxy** [comment]
xdrip provides predictive alerts with a set time threshold, like Pete is suggesting.  Maybe we can glean some ideas from there?
My wife and I use xDrip+ and predictive low alerts on our phones. Its great because it even alerts if BG readings stop coming in. It assumes the same trend it saw before and alerts at the time threshold we set. Its a good reminder to check BGs, especially if it was trending down quickly and then Dexcom decided to stop giving numbers.

To avoid over-correcting, maybe the IOB coverage calculation by @ddaniels1 could subtract an hour of IOB, assuming a temp basal rate of 0 until corrected? Maybe its too complicated or confusing? Just throwing my thoughts out there to help spur ideas. This is calculation I do when giving my daughter corrections at night.

**Comment by NightScoutForSeb** [comment]
I use sugarmate for custom predictive alerts. And then there is IFTT with Nightscout, which I have not tried yet. Just my 2 cents: I see this as a lower priority feature of Loop since there are other bg predictive apps like sugarmate currently available, but it would be awesome to have it all together!!!


Sent from Yahoo Mail for iPhone


On Tuesday, October 1, 2019, 1:51 PM, rfmurphy81 <notifications@github.com> wrote:


Has anyone been able to give this one some attention?

I've been wanting a way to have the Loop app give a notification when it predicts BG crosses a user-defined threshold within another user-defined time period based on the prediction line. For example, it would be helpful for me to know whether I'm expected to cross my suspend threshold value (or another value) so I can determine whether to make the decision to carb correct.

While it'd be nice to provide a suggested amount of carbs, I agree with @ps2 about keeping it simple at first to ensure we can get something out the door versus nothing at all.
