### ISSUE TITLE
Add some test data scenarios to make the simulator more useful

### ISSUE THREAD

**Issue by bharat** [LoopKit/Loop#278]
There doesn't appear to be an easy way to get data into the app when it's running on the simulator, resulting in reduced development velocity. Create a way to import test data such that we can experiment with different scenarios.

Creating this issue as a way to collaborate on development on this effort.

**Comment by bharat** [comment]
I've added a function to LoopDataManager that injects bogus values into the GlucoseStores. It's tricky to get this right, though, and obviously this is a very dangerous thing to have running in production.

We can detect if we're running in the simulator:
http://stackoverflow.com/questions/24869481/detect-if-app-is-being-built-for-device-or-simulator-in-swift

We can then clear out all the old GlucoseStore values (which requires a change to GlucoseStore itself), and model some new ones. But in order to make this really useful, we'd probably need to create a new UI which lets us choose from several different scenarios. Since scenarios age, I'm guessing that the approach would be:

1. enable new UI if we're in the simulator
2. new UI lets you choose a scenario
3. scenario clears out old data and loads scenario data

how does that sound?

**Comment by eszcloud** [comment]
Check out http://perceptus.org/about/glucodyn.

**Comment by bharat** [comment]
glucodyn looks very cool! but it's unclear if we can use it in this context.

This might be interesting, though:
https://github.com/mseemann/healthkit-sample-generator

going to download and play with it.

**Comment by ps2** [comment]
My personal dev setup is to use my own phone, pointing to dexcom share, and using a spare pump and RL.  I could see this being useful for those who don't have this kind of setup.

**Comment by bharat** [comment]
As a proof of concept, I've created https://github.com/bharat/HealthScenarios which currently only has a single scenario that includes blood glucose and carbs. I created it as a separate project because it feels a little dangerous to have this functionality as part of the main app.

This gets me closer to having a working setup in the simulator, but in order to get further I'm going to have to get some kind of fake pump integrated with Loop so that I can get insulin data into the system. Not 100% sure how to do that yet, but will continue to poke at it.

**Comment by trixing** [comment]
How I could imagine this working is to pull data from nightscout (Glucose, Meal, Bolus, Basal) to start the app with the right kind of history "following" the primary app.  That way you could also tinker with different prediction algorithms by going back in time to test how it would change decisions in various circumstances.

Technically that should be rather easy to pull data from NS.

The biggest problem would probably be to replace the RileyLinkManager with something still functional enough and recording Bolus/Basal events in some kind of temporary storage.

**Comment by loudnate** [comment]
I had a fixture data directory checked in for a while containing static JSON data that I used for UI development. The hydration logic still exists in the test target. 

My personal feeling is that algorithm development and scenario testing will be 10x harder to run in the Loop codebase vs doing something in Python/Ruby/Swift via CLI. Since Nightscout is a common data collection platform across multiple client delivery systems, it seems like algorithm testing should happen in close coordination with Nightscout.

Similarly I think generation is powerful but is a project that can be used in broader scenarios than just Loop.

What Loop needs should be simple, local, and decoupled from Nightscout, focused on testing charting and UI.
The insertion point should live in a class to replace the DataManager while implementing a common protocol, not trying to integrate with it. It would also allow for unit testing of the clients of DDM: status view controller, Nightscout data manager, and watch data manager.

**Comment by trixing** [comment]
The problem with development and scenario testing right now is that the logic is all over the place (GlucoseMath, DoseMath, InsulinMath, LoopDataManager, etc.) so writing a drop in replacement (e.g. oref0 would be interesting) is terribly difficult, especially with the burden Framework development does.

It would be really nice to factor out all the math into a javascript module (least common denominator language) to easily plug-in and test multiple implementations and e.g. be also able to visualize these differences in nightscout.

**Comment by marionbarker** [comment]
I believe this can be closed.  Loop now has simulators for CGM and pump.
