### ISSUE TITLE
Show a visual indicator when the pump is suspended

### ISSUE THREAD

**Issue by bharat** [LoopKit/Loop#285]
I sometimes forget to un-suspend my pump. Loop lets me know that it has failed to loop in a while, but it takes me a few moments to figure out why. A visual indicator would help alert me faster.

**Comment by j4cbo** [comment]
+1 to this. I've gotten more and more used to (a) not looking at Loop except through the watch, and (b) ignoring my pump's hourly beep.

Today, this happened:
- Suspend pump before shower
- Immediately after shower, change Dexcom sensor
- Forget to unsuspend pump
- Wait 2 hours, getting "Loop has not completed..." notifications, but ignoring them because I knew the Dexcom sensor was still warming up
- Fingerstick calibration: why am I 300?! ... oh. Because I never unsuspended.

I'd really love push notifications every five minutes after the pump has been suspended for 30+ minutes, like what Dexcom does when it wants a new BG value.

**Comment by scottleibrand** [comment]
Another option, if y’all want it, is to unsuspend the pump if there’s no temp basal running. So when you suspend, you just make sure you have enough time left on the running temp basal to cover the shower or whatever, and then if you forget to resume afterward then Loop can do so for you. We’ve got quite a few OpenAPS users using that (optional) feature quite happily.

**Comment by ps2** [comment]
We do have a visual indication of pump suspend now.
