### ISSUE TITLE
Add option to use Dexcom Share server outside US

### ISSUE THREAD

**Issue by peterlynton** [LoopKit/Loop#416]
Add option in Dexcom Share settings to use existing US server our non US server (US:share1.dexcom.com, non US:shareous1.dexcom.com)

I have tried manually editing Loop>Loop>Managers>KeychainManager+Loop.swift to update DexcomShareURL.
This gives the error 'The operation couldn't be completed. (ShareClient.ShareError error 1.) loginError("SSO_AuthenticatePassword invalid"), but keeps the account details.

**Comment by dabear** [comment]
Hi. Workaround: 
This would require an updated dexcom-share-client framework. 
You can manually change this by forking the framework from here: https://github.com/mddub/dexcom-share-client-swift
You would have to edit ShareClient/ShareClient.swift and replace the two references to dexcomServerUS with dexcomServerNonUS, and then in Loop directory update the carthage file from
`github "mddub/dexcom-share-client-swift" ~> 0.2.1` to `github "yourgithubuser/dexcom-share-client-swift" "master"`
issue a `cartage update dexom-share-client` and then recompile Loop.  See also my project here, if you want to use nightscout instead of dexcom share for fetching glucose data: https://github.com/dabear/NightscoutShareServer

**Comment by dabear** [comment]
This is now possible in Loop as of https://github.com/LoopKit/Loop/commit/d814d8847532b6b66768c2d1a00531797de84e94

![image](https://user-images.githubusercontent.com/442324/27803011-95887c18-6027-11e7-9a77-b044071aa59b.png)

This can probably be closed now @upsetter ?

**Comment by ps2** [comment]
We usually wait until a feature is in a release branch to close the ticket, but then yes, I believe this can be closed!

**Comment by Kdisimone** [comment]
Added in https://github.com/LoopKit/Loop/pull/535
