### ISSUE TITLE
Bolus recommendation and remaining temp basal

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#432]
For safety reasons, Loop subtracts insulin not yet delivered, but scheduled as part of a temp basal from the bolus recommendation.  This is to cover the case where pump connectivity is lost after a bolus.

In most cases it would be a better outcome to cancel the temp basal and bolus for the remainder up front.  Handling the variety of errors that can happen during this multi-step procedure is complex, however, and may increase the failure rate of bolusing.

I'm not coding this up right now; this is merely for tracking/discussion.

**Comment by rsuvalle** [comment]
Has this changed between 1.2 and 1.3 Master Branch builds? Perhaps that's my issue (Loop recommending smaller or zero unit corrections)?

**Comment by ps2** [comment]
No, this was the behavior in 1.2 as well.

**Comment by jmatheson** [comment]
Did it first appear in 1.2?

**Comment by joshcorwin** [comment]
I follow this logic perfectly. For our 6 year old, especially at breakfast, he needs bolus up front. Other than manually overriding and bolusing any suggestions to get the suggestion amount accurate for his needs? Tricky for babysitter, etc.

**Comment by ps2** [comment]
Another option instead of canceling the temp basal and bolusing everything up front would be to have a uniform "partial application" strategy that applies to both temp basals and boluses.  We do partial application of doses via temp-basal over a half hour, which gives us time to correct if bgs drop faster than expected.  With bolusing, we don't do the same, so we have less options as time goes on.  The watch does currently pre-fill a partial bolus.  The phone bolus interface does not pre-fill anything, but lets you copy the full amount.

**Comment by naromero77** [comment]
@joshcorwin I think that I have this same problem as well. It is tricky for my wife and the baby sitters to handle because it requires more interaction with Loop.

For my son, this most often happens when we are bolusing and are below the bottom of the correction range (100-120) but above the suspension threshold (70) and there is a large temp basal in progress. When I am around for meals, I will just come back in 10-15 minutes and see what the pending insulin is. I once gave the *entire* pending insulin, but this caused my son's BG to drop too quickly. Now, I just give half of the pending insulin. I have a max basal rate set to 6X the average basal rate. (We have been using Loop for a while now and I think his parameters are reasonably well-turned. I also set this high max basal rate to mitigate this under-bolusing meal during a large pending insulin effect).

@ps2 I don't quite follow this "partial application" strategy. Could you provide more details?

**Comment by ps2** [comment]
I'm going to close this. It's a detail in the larger discussion of whether Loop should be more consistent about partial application between automatic and manual doses.
