### ISSUE TITLE
Unit display on new glucose graph on lock screen

### ISSUE THREAD

**Issue by beached** [LoopKit/Loop#433]
Testing dev https://github.com/LoopKit/Loop/commit/22c42cebc743390cc5d80b70cd7d7c13aee96ba8 and the new glucose graph on the lock screen is using mg/dl unit even though I have selected mmol/L

![image](https://cloud.githubusercontent.com/assets/855156/24627173/dbb5256c-1881-11e7-9426-4ea0312afe82.png)

**Comment by ps2** [comment]
Have you restarted Loop?  I remember in the past we've had issues detecting the changeover.

**Comment by beached** [comment]
I stopped it and disabled BT before updating and yes I just did it again

**Comment by beached** [comment]
The graph in the Loop app is correct

**Comment by ps2** [comment]
tagging @bharat

**Comment by bharat** [comment]
yup, that's wrong. initial reaction is that the problem lies here:
https://github.com/LoopKit/Loop/blob/dev/Loop%20Status%20Extension/StatusViewController.swift#L53

will look into it.

**Comment by bharat** [comment]
actually, that's probably not it - that should just set the value regardless of units. there's likely some other deeper place in the charts code where we apply units to get the absolute value back out again. either way, will dig into it.

@beached - would it be possible for you to share the StatusExtensionContext data that you have in the "Share Issue Report" section of Loop settings when this problem is occurring? it'd be useful to see what data is being shared from Loop to the extension.

**Comment by Kdisimone** [comment]
Asked around and confirmed.  This issue appears to be resolved.  Units are displaying in mmol  https://github.com/LoopKit/Loop/commit/1b8ede27cf6f1a2fe747cd694b2e84b8739853cc
