### ISSUE TITLE
G5 problems with iphone 5s and 5 ios 10.3 and 10.3.1 - loop v 1.3.0 dev and master

### ISSUE THREAD

**Issue by francescaneri** [LoopKit/Loop#436]
Hello,
Use g5 and with the latest updates is not working properly. with the latest update fails to take the G5 data then loop does not work. while I managed to make it work with version 1.2.0 of the loop using it as if it were a G4.
thanks @ps2 
Matteo

**Comment by walker0** [comment]
@francescaneri try restarting the phone, then open the loop app and then open the dexcom g5 app. It should all start working within ~20mins.

**Comment by bashem** [comment]
I'm getting similar issues with iPhone 6s
I've turned off G5 Sensor and am relying on Internet BG numbers. No longer freezing. 

Trying to figure out how to troubleshoot -- any ideas?

**Comment by bashem** [comment]
with 1.3.2dev I was unable to turn off G5 to fall back to cloud numbers.
I believe the app wake-up is not being triggered with the G5 (to be confirmed).
I hard coded rileyLinkManager.timerTickEnabled = true and I haven't had this reappear.


```
        /// Controls the management of the RileyLink timer tick, which is a reliably-changing BLE
        /// characteristic which can cause the app to wake. For most users, the G5 Transmitter and
        /// G4 Receiver are reliable as hearbeats, but users who find their resources extremely constrained
        /// due to greedy apps or older devices may choose to always enable the timer by always setting `true`
        rileyLinkManager.timerTickEnabled = !(cgmManager?.providesBLEHeartbeat == true)
        if !rileyLinkManager.timerTickEnabled {
            //JBC 20170414 debug g5 glucose too old issue
            rileyLinkManager.timerTickEnabled = true
        }
    }
```

**Comment by ps2** [comment]
Turning on the RL timer may force loop to fetch BG from the cloud and get you a green loop, but it will not work offline, and will also use up phone battery more quickly since it is waking every minute, instead of every five minutes. Ideally you will want to figure out why your G5 bluetooth data is not getting to Loop. Double check the transmitter id, restart the phone, and then wait for a few cycles. I do sometimes see it miss the first reading, but it should pick up after one or two readings.

If you have triple checked the transmitter id, and have rebooted your phone, and waited over 20 minutes with no readings showing up in Loop (be patient, and don't restart loop again!), then please add a comment to this ticket with the following four items:

 * Phone model
 * iOS version
 * dexcom app version
 * transmitter firmware version

**Comment by kdsi44** [comment]
Iphone 6s Plus 
iOS 10.3.1
Dexcom G5 app version 1.7.1
Transmitter Version 1.0.4.10

**Comment by ps2** [comment]
Also, reports of successful usage of recent G5 transmitter versions on iOS 10.3 would be useful as well.

**Comment by ps2** [comment]
Here's one report of successful 10.3 + G5:

iPhone 7
iOS 10.3.1
Dexcom G5 App version 1.7.1
Transmitter version 1.0.0.17

**Comment by loudestnoise** [comment]
I'm successfully using 

* iPhone 7 Plus
* iOS 10.3
* Dexcom G5 app version 1.7.1
* Transmitter version 1.0.4.10

**Comment by ps2** [comment]
I just upgraded our Loop phone to 10.3.1 and Loop started picking up G5 data immediately.

* MLXJ2LL/A iPhone SE 16GB 
* iOS 10.3.1
* Dexcom G5 App version 1.7.1
* Transmitter version 1.0.4.10

**Comment by bashem** [comment]
iPhone 6s
iOS 10.3.1
Dexcom G5 app version 1.7.1
Transmitter version 1.0.0.17
Loop 1.3.2DEV
- I experienced intermittent failures with BG too old errors after warmup.
Have had rileyLinkManager.timerTickEnabled = true since Friday Apr 14 2017

![2017-04-20 08 49 56](https://cloud.githubusercontent.com/assets/20480462/25243069/a047359c-25b0-11e7-9f64-aa463a09fa74.png)

**Comment by LynneRB** [comment]
I sometimes have trouble with BG data too old, but most of the time is fine.
iPhone 6s
iOS 10.3.1
Dexcom G5 app version 1.7.1
Transmitter version 1.0.0.17
Loop v1.3.1 Master

**Comment by elnjensen** [comment]
iPhone SE
iOS 10.3.1
Dexcom G5 app version 1.7.1
Transmitter firmware 1.0.4.10
Loop v1.3.1

I've been running mostly successfully, but since updating to iOS 10.3.1 and G5 app 1.7.1 (and getting a new iPhone SE), I've been seeing periods where the G5 app stops receiving data and just shows "signal lost".   Rebooting the phone always fixes this (but just restarting the Dexcom app or toggling Bluetooth does not).

**Comment by walker0** [comment]
I have tried both an iPhone 6 and a 5S both with 10.3 and 10.3.1 with both working successfully.

Dexcom app version 1.6
Transmitter Firmware 1.0.4.10

**Comment by swiftWindsurfer** [comment]
Methods (as mentioned above and on Gitter) that worked before to get Loop to take G5 data again stopped working for us.  We first started seeing this issue within the last week, while running Loop 1.0 and iOS 10.3 and it continued after upgrading.  Setting rileyLinkManager.timerTickEnabled = true, as bashem did, is where we're at now - as it's kept Loop happy and green since implemented (around 24hrs so far).

iPhone 5s
iOS 10.3.1
Dexcom G5 App version 1.7.1
Transmitter version 1.0.0.17
Loop 1.3.2DEV

**Comment by shanselman** [comment]
iPhone 6s+
iOS 10.3.1
Dexcom G5 app version 1.7.1
Transmitter firmware 1.0.4.10
Loop v1.3.1

I can't get Loop to reliably loop without the rileylinktimer. It'll miss every 3rd or 4th BT, and I never see the little cloud icon where it falls back. Changing to use the timer gets me 90% there with a "connecting" hang maybe once a day. The phone is always in my pocket.

Given that Transmitter 1.0.4.10 has backfill support for 3 hours of values, we should update Loop to use that. That would give us reliable graphs with no graphs that would still work on a plane.

Happy to help pair on that.

**Comment by francescaneri** [comment]
iPhone 5s - iPhone 5
ios 10.3.1
Dexcom versione G5 app.1.7.1
Trasmettitore firmware subg_rfspy 0.9
Loop v.1.3.2 dev

I found that it works, but if you used openAPS by leaving open loop, when you turn openAPS off, and loop closures you have problems. You can not keep the application open. I hope I was clear.

**Comment by walker0** [comment]
@francescaneri I have seen similar issues with wifi on the 5S, it seems to be that wifi ends up interfering with the deacon app and then loop doesn't loop. I resorted to only using cellular data on the 5S.  It doesn't seem to be an issue on the 6 that I'm using now.

**Comment by francescaneri** [comment]
@walker0 thanks for the information ;)

**Comment by francescaneri** [comment]
with master 1.5.0 the problem was solved.
