### ISSUE TITLE
Dangerous Error in projections and suggested bolus

### ISSUE THREAD

**Issue by eyim** [LoopKit/Loop#458]
Around noon today, Loop suddenly start making a massive upward projection for eventual bg and started high temping him.  The projections made no sense as the had 0 iob and 0 cob at the time.  A little while later, he tried to bolus himself for lunch and it suggested the max 25 units of insulin for 30 carbs when it should have recommend about 3 units as his I:C ratio is roughly 1 to 10.  He called me and told me something was wrong and we took Loop out of the closed Loop mode.

Attached are screen shots of what Loop looked like much later in the evening.  Loop was projecting him to go to 1,750 mg/dL even though he had 0 carbs on board.  It was also incorrectly showing active insulin as -1.69 when in reality he had about 1.5 units on board.

Looks like there were faulty reading on reservoir values that were future dated or something.  Attached are the error logs as well.  This is concerning because it recommended a dangerous bolus and would have been high temping him forever.
[looperrorpicture.zip](https://github.com/LoopKit/Loop/files/965906/looperrorpicture.zip)
[errorlog.txt](https://github.com/LoopKit/Loop/files/965911/errorlog.txt)

**Comment by walker0** [comment]
Can you check what the absorption time was for the various carb entries.

**Comment by ddaniels1** [comment]
Check the basal rates on loop.  Did you change them recently? iF you missed a decimal place this can happen, has happened to us.

**Comment by ddaniels1** [comment]
Or if times are out of sync with pump basal.  I just looked at your log, basal rates look reasonable but double check. also check pump time, could generate same kind of error for similar reasons of expected basal being off sync with actual delivery.

**Comment by ps2** [comment]
In v1.3.2 there are two fixes that should each independently cover this. The first is that we were not validating some CRCs on messages, which would allow bad data to be received on occasion (though the chance was small due to 4b6b encoding).   The second is that treatment decisions are no longer based off the last forecast point, and instead are limited to looking out to the duration of insulin action.  This prevents far-future carbs or other sorts of long forecast errors to affect the treatment decision.
