### ISSUE TITLE
MDT Future bg and reservoir entries observed in Loop

### ISSUE THREAD

**Issue by ps2** [LoopKit/Loop#520]
@jslev9, @danibjor, please attach logs showing history fetching.  @danibjor bg fetching would also be useful since you're on enlite.

**Comment by jslev9** [comment]
I have one errant entry in my insulin delivery screen that doesn't want to go away and has been at the top of the list for a few hours. It's not messing up the IOA, so Loop is still properly functioning, but my total daily units are wrong and the time of the entry is making the Loop graphs hard to read because they've trying to show 17 hours of data. Any suggestions on how I can get that one mis-timed entry to go away? I've tried closing the Loop and Dexcom apps and also tried to fetch recent history via the RileyLink screen.

![image](https://user-images.githubusercontent.com/25287702/28081491-70bbbaf0-663d-11e7-930a-c5bb540aa590.png)
![image-2](https://user-images.githubusercontent.com/25287702/28081494-726450e2-663d-11e7-9f37-476beb5c939c.png)

**Comment by jslev9** [comment]
[Loop log.txt](https://github.com/LoopKit/Loop/files/1139767/Loop.log.txt)

**Comment by ps2** [comment]
Thanks, could you also connect your phone via usb, and run in debug in xcode and capture the result of fetching history manually?

**Comment by jslev9** [comment]
If you can walk me through the process, I'd be glad to.

**Comment by ps2** [comment]
Connect your phone as you would while installing a new version of loop.  And press the build and run button (looks like a play button). The output window is to the right and on the bottom inside the xcode window.  Copy and paste that output into a file and upload it here.

**Comment by jslev9** [comment]
![screen shot 2017-07-11 at 2 16 07 pm](https://user-images.githubusercontent.com/25287702/28083498-8ab6e73a-6643-11e7-8d4e-1deb99d8aad5.png)

Not sure what I'm missing...

**Comment by jslev9** [comment]
...but the issue has now resolved itself and is no longer showing on the phone.

**Comment by ps2** [comment]
That lower right hand window (the one with the "All Output" selector at the bottom) should show debug output. Sometimes it doesn't connect.  If you stop and re-run it should show output there.

**Comment by jslev9** [comment]
It still isn't showing anything (I tried it twice more).
