### ISSUE TITLE
Suggested Addition: (settings) ---> When Loop stops working I .... 

### ISSUE THREAD

**Issue by chadharper0131** [LoopKit/Loop#598]
**A.)** For things like: [Fetch Recent History], [Fetch Recent Glucose], [Get Pump Model], [Send Button Press], [Read Pump Status], [Read Basal Schedule], I assume Loop automatically updates each of these when loop starts up. ?? 
What info, specifically, does loop need to have to run in closed loop mode and have a "green loop"??   >> the last 15 mins, 3 most recent readings, of CGM data, right? what else? <<

Could we add a green dot next to each of those buttons indicating that the information is current and working?
Could we add a new [button] ---> that runs a script or a programming loop which would automatically update all the information, show a |progress bar %| and display the status & a confirmation msg - for each function or variable that's being tested/ refreshed/ checked/ examined/ whatever... (kinda do an All-In-One "refresh")? 

+ is it possible to check whether or not loop is sucessfully pulling CGM data from the Dexcom Share servers? Is it possible to have Loop use that data exclusively, rather than also pulling the data directly from the G5 transmitter? _(ive only ever seen the little cloud icon once before, (right after i updated to 1.5 actually.) but ive never seen it again._ 

-------------------------------------------------------
**--> Whenever i have an error of any kind, i always follow generally the same process to resolve.** 
**1.)** Look at the status of my Rileylink - Connected? Signal Strength - good?
**2.)** I 'Tune' or 'Re-tune ' Rileylink Radio Freq. 
**3.)** I refresh all the data starting with: [Button Press], then [Read Pump Status], then [Read Basal Status], then [Write Glucose History Timestamp], with the Last 2 being [Fetch Recent Glucose], and last [Fetch Recent History].~~~~~~ _(i use button press first, just to confirm that pump to rileylink coms are "actually" working correctly. I make sure Recent Glucose and then Recent History are the last two, because for Loop to become and stay green, those two have to be up to date and accurate (so my history is as "fresh" as possible and no other New Events could have happened during the time ive been running my diagnotic repair process._  
**4.)** Once i do ALL the steps above- i go back to the Main Screen and check to see if my loop has changed back to green, showing more current BG data, or showing *"Recommended Basal Rate of XYZ" ~~~~~_(updated BG data, but not green loop yet - signals to me that if i wait 5-10mins, it should turn back to green.) (If basal recommendations are showing - loop almost always, like 99% of the time, turns green again within 5 mins, max: 10 mins._ 
**5.)** _If all that hasnt fixed the problem, which 80-90% of time, it does... If Not, then I restart everything, starting with the Dexcom-G5 App, Turning Off/& back ON my Bluetooth, Restarting the Loop App + all the initial steps i listed above. Then if it still isnt working, ill do a FULL Restart on both the RileyLink & my IPhone + everything else._ 
-----------------------------------------------------------

**Comment by Kdisimone** [comment]
@chadharper0131 

1.  Loop does roll through startup steps automatically.  It obtains BG, pump history, etc at start-up.  Yes.  The Loop will stay grey until those are done.

2. Loop needs recent pump history, reservoir volume reading, current BG, and configurations in the user settings in order to have a green Loop.

3.  Many of the RL command buttons are feature requests from users and are not required to be pressed in order to get Loop working.  They are there for informational purposes...as a courtesy.  Unfortunately, too many people think they are also "fix-it" buttons (which they are not).  Like, Fetch Recent Glucose, Write Glucose History Timestamp, Get Pump Model, Send Button Press, Read Pump status, and Read basal schedule...all just there for user information.  Pushing those buttons doesn't get Loop any closer to a green Loop.

4.  MySentry Pair, Change Time, and Tune Radio Frequency (although that one does happen on it's own periodically...so not necessarily a troubleshooting help like many people claim) are buttons that actually do need to be pressed.  Tune Radio Frequency and Fetch Pump History are only useful for jump starting a green loop after pump comms failed for other reasons (low pump battery or missed rf comms or RL too far away)...but Loop also has code to do those same commands automatically on timers or when failures occur...so really just MySentry Pair and Change Time are the buttons that won't happen automatically that might need to be pressed.

5.  Since so few of the buttons NEED to be pressed...setting green dots next to them would be pointless and makes people think that they need to press those buttons.  The docs do describe that those buttons are for user-convenience only.  Just not everyone reads the docs.

![configuration_-_loop_docs](https://user-images.githubusercontent.com/12402160/31202526-da805a28-a917-11e7-86ad-24ba9bcf149b.jpg)

6. Yes, knowing whether Loop is pulling from Dexcom share servers is already possible.  A small cloud appears next to the CGM reading when pulling from servers.  You can force that mode if you'd like to by deleting the G5 transmitter ID.  Normal action is that Loop will fall back to the servers when local readings fail.  Not sure why you'd want to force it to always use servers. 

![loop_display_-_loop_docs](https://user-images.githubusercontent.com/12402160/31202605-20120a96-a918-11e7-8def-00c0be77375f.jpg)

 7. The troubleshooting section has recently been updated to help people focus in on identifying first if they have a CGM issue, pump issue or RL/BT issue.  By looking at the timestamps on the HUD, it is easy to see when items have gone longer than five minutes.  Plus, you can click on the Loop circle itself to get the exact error message.  I'd suggest taking a look at the new troubleshooting section and using the error messages that the Loop circle provides to maybe streamline your troubleshooting steps.
