### ISSUE TITLE
Suggestion: When predicting going below zero, put "low" instead of "-399"

### ISSUE THREAD

**Issue by rsuvalle** [LoopKit/Loop#611]
The prediction of negative numbers, like "-399" has scared my daughter off of Loop and I've heard many other people say that when they see these types of negative numbers, they feel uncomfortable and panicky. It would be great that if the prediction is below 40 or below 0, or some other number, that Loop just says, "Low" like many meters and the Dexcom do. If that's not possible, perhaps it just shows some dashes in place of the number. I know this probably messes with the graphs, but it would be great if we could find a way to make that work. Thanks!

**Comment by chadharper0131** [comment]
rsuvalle - i know these numbers can seem scary, but they are just projected numbers- IF, Loop takes no further action. If and when loop starts to low-temp , the next projections should be more in line with what will actually happen. + In terms of safety, its important for people to see if they might have done something wrong, like given too large of a bolus on accident - and seeing the "true" projection number, gives people the opportunity to at least be more aware of the possibility of needed to take additional safety action, like eating additional carbs, etc...

**Comment by chadharper0131** [comment]
so using "---" or "low" might make us feel better, it, in my opinion, does us a disservice by not providing as much information as possible, which is a large part of the goal, in my opinion. To have as much information as possible in a format that is as easy to understand as possible, so that we can make the best decisions based on all the facts at our disposal. :o)

**Comment by afcady** [comment]
It's scary because the actual curve is simply wrong.  There must a progressing inability for glucose uptake as blood sugar goes down, so that uptake approaches zero as the available glucose approaches zero.  So even if you die from hypoglycemia you will have some positive number of molecules of sugar in your blood.  The cells can't take every last molecule out of the blood.  So the curve isn't accounting for this relationship which must necessarily exist (as a basic principle of chemistry).

**Comment by beached** [comment]
nice thing about these numbers is that if you take your divide it by your ISF, it is an indication of how many carbs you need to eat
