### ISSUE TITLE
Possible issue with Loop on iPhone X with latest Xcode.

### ISSUE THREAD

**Issue by rsilvers129** [LoopKit/Loop#623]
I built from Master.

Not sure this is working correctly.

if I am 139 and dropping, why does it have my basal at +11 units an hour?
Says I will be 4400 mg/dl.

I saw some weird things last night also. Like I would hit the dose button and it would suggest 14 units for no apparent reason.

![23432632_10156775937943662_257726113_o](https://user-images.githubusercontent.com/4177461/32507275-103b878e-c3b5-11e7-8d12-d0d11e9d553b.jpg)
![img_0185](https://user-images.githubusercontent.com/4177461/32507277-10a5441c-c3b5-11e7-8079-55a7d13e3f5c.PNG)
![img_0186](https://user-images.githubusercontent.com/4177461/32507278-10b0184c-c3b5-11e7-8798-636ebfdaf06b.PNG)

**Comment by rsilvers129** [comment]
[LoopIssue.pdf](https://github.com/LoopKit/Loop/files/1450948/LoopIssue.pdf)

**Comment by ps2** [comment]
Looks like you have changed the time on your pump, and not used the Loop app.  I think that Loop thinks your pump is in a different utc offset, as you have what look like future treatments.

**Comment by rsilvers129** [comment]
I didn't change my pump time with the recent time change. 

Is Loop able to see what time the pump it set to? If so, could it warn the user if the pump time is not correct?

**Comment by ps2** [comment]
What is your local time and offset, what time is your pump set to, and what offset does Loop think it's in?

**Comment by rsilvers129** [comment]
I am near Boston and it is 12:59pm now. My pump was set one hour later, so it thought it was 1:59 pm.

**Comment by rsilvers129** [comment]
I didn't know that Loop has a way to change time. I didn't touch that setting on Sunday for DST. I didn't travel anywhere. I also didn't change my pump time setting, so my pump was an hour ahead of the iPhone.

**Comment by ps2** [comment]
If Loop has never changed the time on the pump, it will not record the pump's offset. When Loop starts and does not have an offset for the pump stored, it will use the phone's current offset.  I think this explains your issue.  The fix is to implement code that will ensure the pump's offset is stored.

Users who have set the time at least once would not have this issue, so I think that's what we haven't seen many cases.  Until we have a software fix, the workaround is to make sure you've set the time on your pump at least once.

**Comment by rsilvers129** [comment]
I have not had any more issues after doing Riley->set_time

**Comment by Kdisimone** [comment]
Resolved
