### ISSUE TITLE
Show health of G5 Transmitter

### ISSUE THREAD

**Issue by Kryptonit3** [LoopKit/Loop#636]
Is it possible to show the health / voltage / age of the G5 transmitter in a menu somewhere?

**Comment by elnjensen** [comment]
@Kryptonit3  You can find it in the Dexcom app; Settings -> Transmitter will show you the date it was activated, though you have to do some mental arithmetic to figure out when the expiration date (three months after the activation date) is.  Voltage/health isn't really an issue for standard use of the G5 transmitter, since the three-month expiry is pre-programmed and is well before the batteries actually run out.

**Comment by Kryptonit3** [comment]
@elnjensen I am new to using Dexcom app, used to be on xDrip+ on android. Will Dexcom app let you know the transmitter is expired after the 3 month limit and no longer provide readings? Mine was activated on 9/14/17 which isn't exactly 3 months but close enough to be a possible reason on why my transmitter stopped working this morning. Replacing sensor soon to see if the transmitter will work with a new sensor, or will find out if it has just stopped working due to the Dexcom limit.

**Comment by Kryptonit3** [comment]
** which is 86 Days.

**Comment by elnjensen** [comment]
It is stored in the transmitter.  As you approach the end of transmitter life, you should get warning messages through the app at roughly 2 weeks and one week before expiring.  If it's past its expiration, it won't let you start a sensor session.
