### ISSUE TITLE
Auto Basals

### ISSUE THREAD

**Issue by ddaniels1** [LoopKit/Loop#644]
We have noticed a sure sign that Olivia is more sensitive is that she has significant negative IOB and she is below target.  Resetting basals is important and makes loop work better for sure.    Wondering about the feasibility of setting basal schedules from loop.  In essence all basals would be a temp basal driven according to the basal schedule in loop, the pump would of course have a default "safe" basal in case of loop error.  That is step 1.  Step 2 is to reduce the default basal in loop lets say by 25% if there is > x negative IOB and below target or still dropping.  Could think about another way to do that for increase resistance as well.

1.  What do people think about this idea? How do we manage on the increased resistance side of the equation?
2.  Any programmers interested in working on this?

**Comment by scottleibrand** [comment]
Have you looked at OpenAPS’ autosens? How would this compare to that algorithm?

There has been some discussion about porting autosens to Loop, but I don’t think anyone has started work on it.

**Comment by francescaneri** [comment]
in reference to this I'm using nightscout autotune and I'm finding it interesting to modify the basal. it would be interesting to integrate it into a loop. what do you think about @scottleibrand @dm61

**Comment by ps2** [comment]
@francescaneri we’ve been looking into parameter estimation tools for loop as well. Any estimation tool that is integrated with Loop would want to use the HealthKit data as it’s source. For estimation tools that use NS data, it probably makes sense to integrate there.

**Comment by francescaneri** [comment]
![29231add-3fee-4ba3-917a-e45db6c48b2e](https://user-images.githubusercontent.com/9915825/37291509-12cdd774-260f-11e8-86b7-95ff41bb58b0.jpeg)

Example of autotune in nightscout

**Comment by ddaniels1** [comment]
Where is the Nightscout auto tune form?
		

		DD
	





On Mon, Mar 12, 2018 at 7:28 AM -0700, "Matteo Neri" <notifications@github.com> wrote:












in reference to this I'm using nightscout autotune and I'm finding it interesting to modify the basal. it would be interesting to integrate it into a loop. what do you think about @scottleibrand @dm61

**Comment by trixing** [comment]
I assume this branch https://github.com/nightscout/cgm-remote-monitor/tree/autotune
The changes it suggests for me are usually pretty small (maybe 5-10%).  I'm not sure if that's working as intended.

If relying on that is actually a good idea as autotune is targeted towards the oref1 algorithm whereas Loop has it's own algorithm.  I'd rather see Loop do some offline optimization.

I kind of suspect that https://github.com/LoopKit/LoopKit/commit/8e72bc32886424afadd74259aba47e4bad27d646 was committed in preparation of this.

**Comment by scottleibrand** [comment]
We don't yet recommend relying on the NS autotune branch for treatment recommendations: it hasn't been merged to dev yet because it's giving different results on different browser types, and no one has yet dug in to debug.

The autotune algorithm works the same regardless of whether the insulin you received was from OpenAPS, Loop, or manual boluses.  There are lots of Loop, AndroidAPS, some non-loopers, and even some MDIers who are useing it successfully via the instructions at http://openaps.readthedocs.io/en/latest/docs/Customize-Iterate/autotune.html

In addition to Autotune (which iteratively and gradually tunes average basals and ratios using weeks worth of data), OpenAPS uses autosens (which I mentioned above) to adjust in real time to overall sensitivity and resistance levels, as shown by whether the median non-meal deviation (insulin counteraction effect) for the last 8 or 24 hours is positive or negative (and by how much).  I have seen some discussion recently of porting autosens to Loop, and would recommend doing something like that first before doing any in-the-loop parameter estimation over longer timescales (like Autotune does), both since Autotune is already available for Loop users to run manually, and because an Autotune equivalent would probably require more work than autosens.

**Comment by francescaneri** [comment]
personally I'm using it with excellent results.

**Comment by trixing** [comment]
Is there a way to run autotune without a baseline of values, but have it find the "best" values for the data window?

**Comment by francescaneri** [comment]
you can understand if the basal is actually correct and if isf and Carb Ratio are correct

**Comment by scottleibrand** [comment]
@trixing I’ve done that by taking someone’s NS URL and autotuning from default settings with wide min and max (0.5 to 2.0). It can usually converge on reasonable settings based off a couple weeks of data (or less if I run it multiple times over the same data).

**Comment by dm61** [comment]
@scottleibrand over what period of time do you think "auto-sensitivity" should work? Based on some side work in an experimental Loop, looks like it might be useful to track sensitivity over a period shorter than 24 hours, perhaps as short as 6-8 hours, but that brings up another trickier question: how exactly should we allocate "discrepancy" (difference between modeled and real bg delta) to various causes: insulin sensitivity, carb sensitivity, basal, or simply over/under-estimated carbs or exercise. In OpenAPS I  think you sort observed discrepancies into different bins depending on modeled insulin or carb impact at the time?

**Comment by scottleibrand** [comment]
What we currently do in oref0 is to run autosens twice, once with the last 96 non-meal deviations (which is 8 hours overnight, or "all day" with meals), and once with all the data from the last 24h, and then take the more sensitive of the two calculations.  That allows us to quickly react to sensitivity (within a few hours the 8h median shifts enough to start being less aggressive) without overreacting and detecting resistance if there are some positive deviations from unannounced meals we didn't exclude or something like that.  We exclude all deviations while COB is non-zero, plus all positive deviations from COB>0 until the deviations drop to zero, plus some additional heuristics for unannounced meals (which we've been tweaking in different versions of oref0 to balance UAM detection from missing massive resistance due to steroids or whatever).

**Comment by dm61** [comment]
In my experiments, excluding all deviations (or discrepancies, as Loop calls them) while COB is non-zero leaves too few data to work with during daytime, which may be fine if we are averaging over many days, but not so great for detecting within-day drifts in sensitivity which I think do exist. Looks like you are solving that by running 8 hours window overnight only, but based on my n=1 experience even that may not work that great with nights after dinners that often take long time to digest.  I've been looking into other approaches to allocating discrepancies based on continuously computed weights.

**Comment by scottleibrand** [comment]
By using the last ~96 non-zero-COB discrepancies (plus the positive discrepancies from when COB hits zero until the discrepancies drop to zero), it'd end up looking at the last few hours before breakfast, plus any gaps in between meals.  In my experience, it's impossible to differentiate sensitivity from poor carb counts around meal times, so it's better to use autotune to (more slowly) adjust CR over weeks, and adjust sensitivity based on fasting discrepancies.  The one other thing we do is to add in negative deviations whenever the user runs a high temp target, so that we get a jump start on post-exercise sensitivity, and can also respond to the user setting a high target for manually observed sensitivity.

**Comment by francescaneri** [comment]
I always thought that they wanted more sensitivity during the day. since I use only one sensibility my performance is much more stable. even the basal most are 2-3 more the algorithm can work. this article seems to me important for basic settings according to age.
https://tidepool.org/lets-talk-about-your-insulin-pump-data/
