### ISSUE TITLE
Set basal profile in only one place (either Loop or pump)

### ISSUE THREAD

**Issue by elnjensen** [LoopKit/Loop#652]
In the current implementation of Loop (as of version 1.5.1 in late December 2017), it is necessary to set basal rates both in the pump and in the settings for Loop.  When the eventual predicted BG is above or below the target range, Loop uses the in-app basal schedule settings to calculate a high or low temp basal.  In this case, the actual pump basal setting for the current time period is moot, because Loop is setting a temp.  However, if the eventual predicted BG is in range (and a low isn't predicted in the intervening time), then Loop will cancel any temp, letting the pump basal rate take over.  In this case, the pump basal settings do matter.

Thus, the basal settings must be correct both in the pump and in the Loop app for Loop for function correctly all the time.  This is both inconvenient (requiring the user to enter initial settings or any desired changes in two places) and potentially prone to error (if settings are inadvertently set differently in the two places).  Thus, it would be better if it were possible for the user to only have to set basal settings in one place.

Obviously, there are (broadly speaking) two ways to do this: have the pump settings be the authoritative settings that control Loop, or have the Loop app settings take precedence.  There are pros and cons to each, both in terms of ease of use and in terms of software implementation. I'll try to lay out my thoughts on this, and I welcome comments, corrections, and/or other possible implementations.

1.  Pump settings take precedence.  In this model, whatever the user enters into the pump is the final word on basal settings.  The app would need to poll the pump periodically to know the basal schedule.  This could be done at fixed intervals, and there could potentially also be a way for a user to manually initiate such a pull from the pump to update Loop's knowledge of the basal schedule (e.g. right after the user updates basals in the pump).  Taking this model to its logical conclusion might mean removing the current interface in the Loop app for the user to edit basals, in order to avoid confusion.  (They could still be displayed there, but just not be editable, to make it clear that they need to be edited on the pump.)

2.  Loop settings take precedence.  In this model, whatever basal schedule the user enters into Loop is the final word on basal settings.  The app would need to *always* set temp basals on the pump, even if the predicted BG is in range, to ensure that a different basal setting on the pump wouldn't take over if no temp basal is set.  (In other words, the app wouldn't trust the pump settings to be the same as the Loop settings.)  It would still be recommended best practice to update the settings on the pump in order to provide a safe fall-back position when Loop isn't running, but this would be a backup plan rather than being essential for correct operation of the loop.

Pros and cons of these, as I see them:

1.  Pump settings take precedence:
    - Pros:
        - A safe fallback is guaranteed.  Since the user is always settings basals in the pump, they will always be the correct settings whether or not Loop is running.
        - Possibly improved battery life.  If the eventual BG is in range, Loop could cancel (or not set) temp basals, resulting in somewhat fewer pump communications.
        - Possibly more robust comms from shorter history.  Related to the previous item, fewer temps set means fewer events in the pump history, meaning less time spent fetching recent history and thus less potential for a failed history fetch.

    - Cons:
        - Harder to change basal schedules.  Editing basals on the pump is considerably less convenient on the pump than in Loop, particularly if the number of basal segments is changed.  On the pump, if you add or delete a basal segment, then all subsequent segments have to be changed.

The pros and cons of the other option are mostly the converse of the above, but for completeness (and with a few additions), here they are.  In cases that mirror the above, I've stated the issue more briefly below. 

2.  Loop settings take precedence:
    - Pros:
        - Easy editing of basal schedules.
        - More consistent with Loop's approach to settings overall.  Settings like carb ratios and insulin sensitivities have counterparts on the pump, but currently the pump values are ignored by Loop, and are only used in case the user has to fall back to manual operation of the pump and using the Bolus Wizard.  Having basals be set only in the pump would shift completely to a model where none of the numerical pump settings matter except as safety buffers (max bolus, max basal rate, fallback basal schedule).  The user would still be required to set a few things in the pump initially, e.g. temp basal type as absolute rather than percent, MySentry pairing for x23 pumps.

    - Cons:
        - No guarantee of safe fallback for basal schedule.
        - Possibly shorter battery life.
        - Possibly less robust comms from longer history.

In enumerating pros and cons above, I have purposely not included ease of implementation because if one scenario is clearly better than the other, arguably we should implement it even if it's more difficult.  (As long as it's not crazily difficult.  And yes, I *am* willing to help with implementation, so by saying this I'm not intending just to shift this work onto someone else.  :wink: )  That said, it seems to me that implementing option 2 (Loop settings take precedence) is simpler than implementing option 1.  All it would require is modifying the two lines of code that control what happens when the eventual BG matches the target.  Currently those lines cancel the current temp (if one is running) or don't set a temp (if none is running already).  They would just need to set a temp at the scheduled rate.  Implementing option 1 is certainly possible, but would require a bit more coding, including some decisions about how frequently to fetch the pump basal schedule, how to translate that into the form understood by Loop, and whether or not to remove the basal-setting interface from Loop (and if not, how the values entered there would be used and how this would be described in the UI).  Note that it is *not* possible (as far as I know) for Loop to modify the basal schedule in the pump, so the hybrid option of using the Loop interface for editing basals and then having Loop enter those into the pump's settings (other than as temps) is not possible.  

If basal profiles were set solely from Loop, this could be a first step toward an additional enhancement of adding easy switching of different profiles (including basal schedules but also sensitivities, carb ratios, etc.), though this would require implementing a mechanism for saving and restoring settings.  This has been a frequently-requested feature (e.g. issues #114, #331, #463, #644; discussed in #177 though the main issue there is separate; somewhat related to #226; could possibly be used as an enhanced activity mode a la #593, though it would be through a fixed profile of settings rather than the simple scaling of current settings suggested there).

Going the other direction (setting on pump, pushing those settings to Loop) relates to #30 and #227.

**Comment by PatriqB** [comment]
I follow your arguments all the way. And my intention with the comments below are not to argue in favor of any direction.

What I'd like to point out is that conditions for all of the reasoning with pros and cons, takes the use of Medtronic pumps as the standard. It seems to me, and I also hope it will turn out plausible, that soon it will be possible to Loop with Omnipods. Now, Omnipods to my understanding has basal rates transferred at initiation. Settings are stored in the remote and transferred to the pod each time a new pod is taken in use. Also basal rates can be changed at any time. This means that these pumps are conditioned in another fashion. And if you ask me it would make good sense to take this into account already now. Who knows what type of pumps will be made compatible later on as well.

Taking these pumps into account, to me, tilts the arguments in one direction more than the other. I'm not familiar with the operation of other pumps, since I only ever used Omnipod. Maybe there are other inputs that could be raised if one takes into account that even more makes could be included as compatible over time. 

I'd also like to use the opportunity to point out something I pondered when there have been discussions regarding a spare pump and things that can/will go wrong with the Medtronic pumps. With the Omnipods you have as many spare pumps as you like :)

Also, I'm hoping that Loop will be able to replace the remote for Omnipod completely. Meaning I don't have to carry it around any more, and just have it at hand for emergencies. Initializing new pods with Loop, confirming low remaining levels, short time until change of pod etc with the phone and the app only. 

I actually waited many years for the Omnipod to become available in Norway and preferred pens and manual injections to infusion set with tubing. I suspect I was the first ordinary user that started up on Omnipod when it became available. I just can't see the active life I'm leading with the other types of pumps, or the benefits of being able to stay for hours on the pool with my kids etc.
Ok - last part here had nothing to do with the discussion at hand. I'm just so pleased with this solution :)

**Comment by scottleibrand** [comment]
I think it might be worth exploring whether it actually is possible to set (Medtronic) pump basals remotely. I suspect that is one of the things the Carelink USB stick was originally designed to do, given the language in the PC Connect menu on non-loopable pumps. Perhaps we should ask some endos or CDEs if Carelink Pro has this capability, and if so, run a mmeowlink data dump to see what opcodes Carelink Pro uses when setting a pump’s basal profile.

**Comment by elnjensen** [comment]
@scottleibrand   Interesting idea.  Is there reason to believe that Carelink Pro has significant undocumented features?  There's no indication of anything like that in any of the [Carelink Pro manuals](https://www.medtronicdiabetes.com/download-library/carelink).  This doesn't mean that the command doesn't exist in the RF protocol for communicating with the pumps, but I don't see any hints about it being part of Carelink Pro.

**Comment by scottleibrand** [comment]
Ah, bummer. Didn’t realize the manuals were freely available. Perhaps @bewest or @ps2 would have a better idea of whether there is likely and opcode for writing basal schedules. I think Ben went through all of them at one point (discovering the “set contrast to zero” opcode by accident), but not sure if he identified whether any might be usable for setting basal schedules.

**Comment by dabear** [comment]
A list of available commands is available here: https://github.com/openaps/decocare#user-content-mm-send-commpy--h

I don't see any way of changing basals permanently on the pump. However:
1) Apparently you can change between basal programs
2) It is possible to send "press this button" to the pump, this could be used to emulate a users actions for changing basals permantly, but this seems like a way to big hack, especially as you cannot gurantee the user interfering with the pump while commands are being sent.

**Comment by elnjensen** [comment]
@dabear   I think the second link above is the list of types of history events found in a pump history fetch, but I agree that the first link tells us the currently-known pump commands.

**Comment by dm61** [comment]
@elnjensen thanks for opening the issue, and for the detailed arguments. IMO, the advantages of "2. Loop settings take precedence" outweigh the disadvantages. The most serious disadvantage seems to be the effect on robustness of comms due to longer history. In an attempt to measure the impact on history length, I've counted the number of times my Loop set or canceled temps over the last 30 days: turns out that on average it set temps 186 times per day, and canceled temps 20 times per day, So, setting temps all the time would result in approximately 10% longer history, which seems acceptable to me. Of course, it's hard to tell how much these counts may vary from user to user, the penalty could be worse. The counts also depend on the correction range (which is 5 mg/dL wide in my case). 

As a user, although I'd prefer the flexibility of setting everything in Loop, I'd still like to have an option to just populate the Loop basal rates (as well as ISF, and CR) from the pump, on command. I imagine this would be particularly useful for new users, to quickly setup the parameters as a starting point. Loop could then occasionally check if the pump parameters are the same as the Loop's parameters, and (discretely) display warnings if differences are found.

**Comment by Kdisimone** [comment]
I hate the pump screen option.  I'm almost kicked in the face at night if I have to touch my kid's pump while she is asleep.  Inevitably there is a lot of twisting and awkward angles to get to her pump buttons.  Changing Loop settings is far easier.

I've been using the neutral temp basal setting customization to minimize the disconnect between pump and Loop settings (when they do exist because of reasons mentioned in my opener).  That has helped a lot.

**Comment by elnjensen** [comment]
Thanks for weighing in, @Kdisimone .  Unfortunately I haven't had any time to work on this, nor does it look likely before summer.  I welcome additional comments and hope to work on this at some point, but life is just a bit too busy right now.

**Comment by elnjensen** [comment]
@apabari  Thanks for noticing this - I do think this is largely addressed by the new PumpManager protocol and interface in Loop 1.9, so I'll close it.
