### ISSUE TITLE
Separate Minimum Threshold for bolusing

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#654]
I've been experimenting with raising our Suspend Threshold.  Previously we have kept it at 55 because my kid gets really quizzical about how to handle Loop when it doesn't recommend a bolus after a carb entry.

Well, we've now raised the suspend threshold to 70 and 75 for long periods of time and really liked the way the Loop is setting temp basals better.  BUT...that is too high of a threshold for bolusing (for us).

Anna is really good about making other decisions when BGs are between 55-70 and she wants to eat.  Normally she will handle this situation by simply eating sooner (no prebolus) or even taking a little bit of the recommended bolus out.  

But, right now...the Loop isn't showing what the recommended bolus is when BG is below suspend threshold.  I looked around the code and there appears to be some code that intends to still show the recommended bolus, but not fill in the amount?  Even just seeing the amount would be helpful, she could choose to manually type in the deliver amount herself.

I'm sure there are several viable options for addressing what our issue is...but in my head I've been thinking about a separate minimum BG from suspend threshold.  Something like a Carb Bolus minimum BG threshold.

Thanks!  I appreciate any thoughts on this.

**Comment by ELUTE** [comment]
+1 on this. Would love them to be separate values.

**Comment by dm61** [comment]
This issue is slightly more involved than just separating a bolus threshold from the Suspend Threshold. Loop 1.5 is using Suspend Threshold for all dosing (both bolus and temps): a correction dose is calculated so that the BG forecast does not drop below correction target, which equals Suspend Threshold for the first half of DIA and then ascends to the mid point of the correction range at DIA, as shown here:
![dosingloop1 5](https://user-images.githubusercontent.com/12002177/34596233-5418f446-f19b-11e7-8f1f-18a57bd10fcf.png)
So, even if there was a separate, lower bolus threshold, Loop would still suggest 0 bolus if initial BG were below Suspend Threshold. 

To address this issue, I am thinking that we could modify the correction target to include an Initial Threshold below Suspend Threshold for an initial fraction of DIA, as shown here: 
![dosingloopexperiment](https://user-images.githubusercontent.com/12002177/34596298-d4fc5224-f19b-11e7-8a3e-a7ca44c8f54b.png)
I've implemented this in an [experimental version of Loop](https://github.com/dm61/Loop/tree/initial_dosing_threshold), which includes two main changes: 

1. Allow dosing above an Initial Threshold below Suspend Threshold. A difference of 10 mg/dL is hard coded in two locations in the experimental code, feel free to adjust this as you wish. Warning: if your Loop works in mmol/L, you may need to adjust the hard coded difference between the two thresholds. 
2. Modify the correction target as illustrated above, with Initial Threshold extending over the first 10% of DIA. If Loop still appears to be too conservative when bolusing below Suspend Threshold, you may extend this to 15% or perhaps 20%.  

I've been running this experimental version for 3 days now, and it seems to work as intended, I like to keep Suspend Threshold somewhat higher, and still get a meaningful bolus recommendation when bg is below Suspend Threshold.  Any comments are appreciated.

**Comment by Kdisimone** [comment]
we've been using a customization on Line 426 in dosemath.swift and it's been working really well for us.  They haven't still been zero bolus recommendations.  The boluses are in-line with what the carb absorption, carb ratios, etc. would have me expect.  

`suspendThreshold: HKQuantity(unit: HKUnit.milligramsPerDeciliter(), doubleValue: 60),`

**Comment by dm61** [comment]
@Kdisimone will check this some more, but I think changing that line is equivalent to just overriding Suspend Threshold for boluses to a lower value. This does offer bolus below the original Suspend Threshold, but will also recommend a higher bolus based on that lower Suspend Threshold value for any other BG, which in part compromises safety offered by Suspend Threshold.

**Comment by Kdisimone** [comment]
I'd love for you to take a look at it @dm61, thanks.  We'd run a bunch of test carb entries through it compared it to what we would expect/want (before we put the change in place) and were really happy with the bolus recommendations we were getting.  Been working well in real use too.

**Comment by dm61** [comment]
@Kdisimone overriding Suspend Threshold in line 426 will result in a more aggressive bolus for long carb absorption meals. After such bolus, Loop's bg forecast will dip below the original Suspend Threshold. In response, Loop will follow-up with some low-temping, since Suspend Threshold for temps remains the original higher value. That's fine, and might even be desirable in many cases, but it's just slightly more risky. In my version, Loop will still give good bolus recommendations if bg happens to already be below Suspend Threshold, but will never issue a bolus that will drive bg forecast below the original Suspend Threshold value.

**Comment by dm61** [comment]
@Kdisimone following your approach, I've cleaned up my [experimental Loop version](https://github.com/dm61/Loop/tree/initial_dosing_threshold):  in the `recommendBolus` function, I've added a new `initialThreshold` set to 60 (just as you did), while also keeping the original `suspendThreshold`, see [Lines 447-448](https://github.com/dm61/Loop/blob/9b7b261e53b0b39e48737502a7f81796020ee14b/Loop/Managers/DoseMath.swift#L447-L448). The new `initialThreshold` applies only to boluses, and only during an initial portion of td=DIA (as illustrated by the diagrams I posted earlier), that initial interval now set to 15% of td. The logic is that Loop should recommend bolus when bg is below suspend threshold, but only if sufficient carbs have been entered so that the predicted bg goes above suspend threshold within some reasonable time (15% equals 54 minutes, if td = 6 hours).  Otherwise, the entire Loop 1.5 dosing machinery remains the same, so I think this might be a good way to address the issue.

**Comment by karma667** [comment]
I’m thrilled there’s work on this. As new users we’ve been frustrated with bolusing when she’s close to suspend which is often the case in the AM. 

To test can we just sync dev, or totally separate branch? Thanks!

**Comment by chadharper0131** [comment]
@Kdisimone - Are you still doin' any "Loop Doc" page updates/maint. ???   i think it would be +1 useful to have Mr. @dm61 -[fancy shmancy diagrams :o) ] & some of the suspend threshhold information that was mentioned/discussed above, added to the doc, if its not already. I just took and quick peek & didnt notice any info about "Suspend Threshold" in there, so it might be a good addition... Thanks. Whatcha think? Anyone disagree? --->

**Comment by Kdisimone** [comment]
@chadharper0131 yes I still do loopdocs updates. I don’t think that the loopdocs however should cover things in development (as opposed to merged into master branch). GitHub issues is a better place to get dev discussions captured.  Once the final decision is made about how to (and whether to) make any code changes, then I’ll update the loopdocs to reflect the new settings. 

We do have a section about suspend threshold setting in the setup of the loop app section. Take a look at it and let me know what you were looking for that might not be there. Thanks!!

https://loopkit.github.io/loopdocs/setup/loop-settings/settings/#suspend-threshold

**Comment by ddaniels1** [comment]
Hi All, please check this out.  My first attempt at any real coding, still a work in progress but I think I may have made bolus threshold configurable in Settings. Building off @dm61 code.  @ps2 and @Kdisimone can you take a look?  Still has some things to work on, testing this today.  

https://github.com/ddaniels1/Loop/tree/Bolus_Threshold_Configurable

**Comment by ddaniels1** [comment]
@dm61 take a look.  It works on test set up, but I can not get the variable I am calling "Bolus Threshold" to stick in the settings page. Perhaps I am missing something simple, others mentioned similar issues on gitter.  I wonder if there is something I need to do in loopkit?

**Comment by ddaniels1** [comment]
OK all, here is my attempt.  Please test this branch carefully. I am very novice at coding and this is my first effort, but we have been testing for a week and it looks to be doing the job.  Note the variable "Bolus Threshold" is now configurable in settings.  The algo is based on @dm61 's work above with slight adjustments. From t=0 to 15% of DIA loop will suggest a bolus that keeps forecast >bolus threshold.  AT 15%-50% of DIA that keeps forecast above suspend threshold. And at 50%-100% targets forecast to the mid point between min and max correction range. 

Please give me feeback!

https://github.com/ddaniels1/Loop/tree/Configurable-Bolus-Threshold

**Comment by dm61** [comment]
@ddaniels1 I've just tried your branch. Looks like it is working as intended, good work. The Bolus Threshold setting is retained between Loop launches, nice. One minor comment: the explanation under Suspend Threshold should be updated to read: "When current or forecasted glucose is below the suspend threshold, Loop will always recommend a temporary basal rate of 0 units per hour." 

We may want to include some limits for the settings: a minimum allowed setting of 65 mg/dL (or equivalent in mmol/L) for suspend threshold, and a minimum of 55 mg/dL (or equivalent in mmol/L) allowed setting for bolus threshold. If we set such limits (which I think we should), we should also require that bolus threshold be less than or equal to suspend threshold (otherwise the settings do not make sense).

**Comment by ddaniels1** [comment]
Agree with all. I noticed the message about suspend threshold and was planning to fix. I also agree about setting limits. This hadn’t been done before for suspend threshold but for safety I think that it makes sense. Will Work on it. I am very novice at coding and not great with swift but I will try. Any idea how to deal with mmol users?

DD
________________________________

**Comment by ddaniels1** [comment]
This has been submitted now as a PR

**Comment by jwedding** [comment]
+1 to this.

**Comment by mkitchingh** [comment]
+1 for me. This is how we operate without loop. If my daughter is at 70 and about to eat something like pasta, we will bolus at mealtime and knock off a half unit or so.

**Comment by silvimichelle** [comment]
+1 for me! I'd like to be able to see the recommended bolus and decide for myself what to deliver (or not). Thanks!

**Comment by wmomand** [comment]
+1 would love to see this in the production version of the app

**Comment by mel2095** [comment]
+1

**Comment by flippinkitty** [comment]
This is much needed.

**Comment by Chemikaze** [comment]
I'm guessing since this is an open issue, @Kdisimone suggestions wasn't added to Loop v2.0?  
> we've been using a customization on Line 426 in dosemath.swift and it's been working really well for us. They haven't still been zero bolus recommendations. The boluses are in-line with what the carb absorption, carb ratios, etc. would have me expect.
> 
> `suspendThreshold: HKQuantity(unit: HKUnit.milligramsPerDeciliter(), doubleValue: 60),`

Another suggestion:
The Omnipod PDM will show the calculated dose based on carb input, but also the recommended based on BG (if tested).  Can that calculation be added to the bolus screen?  It at least removes the manual calculation requirement.

Personally, I'm a fan of the former but at least this is something.

**Comment by JELCRAWFORD** [comment]
Would also like to see this and am willing to do a code change - if someone can confirm though - this is clearly written for those using milligrams - for those of us using mmols, I assume that the correct syntax would be:  suspendThreshold: HKQuantity(unit: HKUnit.millimolePerLiter(), doubleValue: 60),

Thx in advance.

**Comment by marionbarker** [comment]
I was using this with conventional Loop. But it is not a good idea (as written) with the microboluses / automatic-bolus branches which are currently being studied. Anyone using this customization that wants to test one of those branches, please restore that line to default before testing.

**Comment by JELCRAWFORD** [comment]
ahh.. yes, I remember now seeing your comment Marion - thanks for the heads up as we are testing those branches.

**Comment by Fuzz23162** [comment]
Running on auto bolus testing branch and am questioning whether it would be possible to implement a feature for the suspend threshold that would allows us to have different time periods for the value assigned much like ISF currently has. We have two situations that occur often that this would be useful for...

My dd is very active in sports and on nights she has games will experience a rapid drop in the early morning hours due to the delayed impact of the exercise. It does not occur every single time, so it is not a situation that I want to run an override overnight. 

It would also be a helpful feature as many have discussed surrounding boluses. We often have the situation prior to lunch at school where things aren't ideal for a variety of reasons and I know that her basal needs to remain on. She will dose for lunch and Loop will turn basal off assuming there is enough IOB and will not turn back on soon enough to stop an impending rise. It would be more useful if I could lower her suspend threshold for a set time period (and day of the week would be even more wishful thinking) then to have to have her open loop. Her opening loop assumes that she/I are paying close enough attention to close it when appropriate. Her closing loop when needed can be a big issue for us as there are ongoing communication issues with the WiFi at school. There are areas within the building that do not always transmit cellular or WiFi signals (concrete fortress) so I am not able to reach her short of sending someone to find her (which after school is not an option).

**Comment by NightScoutForSeb** [comment]
+1 We have threshold set to 68, but I would love it to be set to 70, but for food bolus have it set to 65.
