### ISSUE TITLE
New sensor error

### ISSUE THREAD

**Issue by msrcgm** [LoopKit/Loop#672]
What does this mean and how do we cure it?

![26219202_10211323680743428_330939074148793251_n](https://user-images.githubusercontent.com/7939853/35421607-f6ba1816-01f8-11e8-837d-b4d3330cbb31.jpg)

**Comment by Kdisimone** [comment]
Any errors or warnings in dexcom app?  Low transmitter?  Unknown trend?

**Comment by Kdisimone** [comment]
If you track/enable error codes in NS, you may get more info possibly

http://www.nightscout.info/wiki/faqs-2/error-codes/what-does-this-error-code-mean

**Comment by Kdisimone** [comment]
More info on error code setup. http://www.nightscout.info/wiki/welcome/website-features/0-9-features

**Comment by ps2** [comment]
This usually happens when the dexcom app is requesting a calibration.

**Comment by thebookins** [comment]
If we think that the glucose is still 'reliable' (a reasonable assumption, since dex continues to display it) we can resolve by adding a new calibration state enum corresponding to code 14, and including it [here](https://github.com/LoopKit/xDripG5/blob/fe93d4759b9cba9f106cffb53fe3b383e0b9a6db/xDripG5/CalibrationState.swift#L43).

**Comment by Kdisimone** [comment]
closed, address with https://github.com/LoopKit/CGMBLEKit/pull/82
