### ISSUE TITLE
IOB miscalculation

### ISSUE THREAD

**Issue by francesc0-cgm** [LoopKit/Loop#798]
Using “unofficial katie branch”. Tonight something strange happened. Bg was stable at 70s and loop stopped basals for a couple of hours. However iob seems wrong. On loop iob nubers are the same of NS pills.  

![781536be-7ef4-48ea-b452-f78b28eb15bc](https://user-images.githubusercontent.com/10731469/45014804-10acc400-b020-11e8-9ae1-ca3bf62ae765.jpeg)
![4cd02f44-dea2-47c1-a178-de081b33c564](https://user-images.githubusercontent.com/10731469/45014805-11455a80-b020-11e8-975a-3e74c9d6dfa0.jpeg)
![40b1bbca-ecad-4da2-a3bf-246fe9002d13](https://user-images.githubusercontent.com/10731469/45014806-11455a80-b020-11e8-833e-91a5d96c01e6.jpeg)
![412051aa-89d5-4e93-9071-052b467c58db](https://user-images.githubusercontent.com/10731469/45014807-11455a80-b020-11e8-9b06-b22e7ab9f9ad.jpeg)

After more than two hours of 0 basals (basal is 0.25 per hour) with a very short period of 0.05 in the middle iob should have been about -0.45 but it was completely off and of course my son started to raise maybe for a dawn phenomenon at 5.30 am, worsened by lack of miscalculated negative iob.

**Comment by Kdisimone** [comment]
The conclusion that the IOB is "incorrect" doesn't have any Loop data showing with it exactly to show.  These are all snapshots from NS's basal rendering (which can be incorrect or delayed, as I have experienced before).  In order to ascertain what basals were set or suspended, and therefore whether or not IOB was or was not properly being calculated, we would need to see Loop app's data (health kit and Loop actions).  Unfortunately, there just isn't the needed data here to work with.  I'll close this out for now, but if you see the same behavior again, please grab Loop info as well.  Issue report, screenshots, and health app data would help fill-out the information needed.
