### ISSUE TITLE
Retrospective correction disabled 

### ISSUE THREAD

**Issue by gurtajd** [LoopKit/Loop#814]
[Loop Report 2018-09-20 102559-0700.zip](https://github.com/LoopKit/Loop/files/2402427/Loop.Report.2018-09-20.102559-0700.zip)

**Comment by dm61** [comment]
@gurtajd not sure why you selected G4 as your CGM source? Try selecting G5 instead (but do not enter ID if prompted to do so). Also, have you set the pump clock from Loop? If not, you should do so: go to Pump Settings, tap on the RileyLink, scroll down and tap on the Change Time. If, after these changes, the inactive retrospective correction problem still persists,, try power-cycling and rebooting everything once again.

**Comment by gurtajd** [comment]
Ok made all the changes and an hour later still saying the same thing :(

**Comment by dm61** [comment]
@gurtajd could you please post another issue report after the changes you made, I'd like to see if some weird issues around your pump dates have been resolved after you set your pump clock from Loop. Also, just to clarify: other than inactive retrospective correction, is your Loop running fine?

**Comment by gurtajd** [comment]
[Loop Report 2018-09-22 095620-0700.zip](https://github.com/LoopKit/Loop/files/2408070/Loop.Report.2018-09-22.095620-0700.zip)

**Comment by gurtajd** [comment]
I think loop is otherwise working fine I’d like it to be more agressive in bringing levels down I think a fix for this would help with that🤞🏽

**Comment by dm61** [comment]
@gurtajd something is wrong in your setup, but I am not sure what. In your issue report,  there are lines such as `isPumpDataStale: true` (should be `false`) and `lastAddedPumpEvents: 0001-01-01 00:00:00 +0000` (should be current date). The not-up-to-date date shows up in several locations in your report. I thought this would be fixed by setting the pump clock from Loop, but apparently this did not help. For some reason, Loop seems to be unable to correctly update your pump status even thought it seems to be able to issue bolus and basal commands.  

Two more questions: (1) did you notice any errors reported by Loop during the pump setup process? (2) just in case there is something obvious I am missing, could you please post a screenshot of your Loop main screen. 

Unfortunately, I have to say I do not understand the nature of the problem in your system setup, sorry about that. Maybe someone else could take a look at your issue reports. You may also want to consult with someone else who using Spike/Miao with Katie's Loop 1.9.2, and check if there are having the same problem, or is this something specific to your setup.

**Comment by Kdisimone** [comment]
@gurtajd have you resolved your issues?  Do you need additional help for this issue or can I mark this as resolved?

**Comment by gurtajd** [comment]
Hi yes Katie I’ve resolved it...i had some old loop data on health app and I did not set a suspend threshold. When I did that retro correction started immediately :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Kdisimone** [comment]
Thanks
