### ISSUE TITLE
Loop double doses for meal when mix of large first and later small carbs are entered.

### ISSUE THREAD

**Issue by sdawson2003** [LoopKit/Loop#843]
**Describe the bug**
We have seen this twice, possibly three times, since going to 1.9.3.  Never before 1.9.3.  Have been using Loop 3 months.  When splitting carb entry and bolus over several carb entries, sometimes the second bolus is large, even if the carbs are not.  (Sometimes daughter is not sure she will eat entire breakfast or lunch, and holds back some carbs, then enters them when she eats the remaining carbs.). See two attached screenshots.  NOTE:  The carbs are not double entered.  We know to avoid that!

**Attach an Issue Report**
Do not have one.

**To Reproduce**
Not sure.  It doesn't happen every time, has only happened a twice, maybe three times in the three weeks we have been running 1.9.3.  The third time pump was removed and suspended mid-bolus so the Nightscout data was funny.  I didn't include that screenshot or data.

**Expected behavior**
The second bolus should be commensurate with the carbs entered.  Instead, it appears to take all COB into account and deliver a second (large) bolus.  I thought it might have to do with "future" carbs, those that are entered with a future active time (like 15 minutes in the future).  But one of the screenshots is like that and one isn't.

**Screenshots**
These screenshots are taken from Nightscout treatment report.  Carb ratio is typically 1:9 or 1:10.  

In one screenshot, you can see 36G entered, then 3.5U delivered.  A short time later, 10G and 1.0U.  Then 10G more, and 4.1U!

In the second, a correction of 3.7 is given before lunch, to account for the 42G that were put in with an active time 15 minutes into the future.  A short time later, 15G are entered, and another 4.2U is delivered.

<img width="850" alt="screen shot 2018-10-28 at 2 52 23 pm" src="https://user-images.githubusercontent.com/17674787/47620590-0b20a700-dac2-11e8-8822-080812bc02b9.png">
<img width="851" alt="screen shot 2018-10-28 at 2 53 02 pm" src="https://user-images.githubusercontent.com/17674787/47620591-0c51d400-dac2-11e8-8fac-ea097931777b.png">

**Phone**
 - Hardware: iPhone 8
 - OS Version: IOS 12.0.1

**Loop Version**
 - Version Number: 1.9.3
 - Repo: Loop Master

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 522
 - Firmware version: 2.4A

**Additional context**

**Comment by Kdisimone** [comment]
Do you have anything from Loop which would indicate the bolus was actually given?  Issue Report?  Screenshots of Loop's main screen and/or reservoir volumes from that time?  How about health app insulin delivery records from the time you think this occurred?

The reason being, Nightscout's displays are not always reliable representations of what is going on  in Loop. For example, when time changes during a bolus...it will LOOK like there was multiple boluses given, when really it's a glitch of the medtronic pump and no extra insulin was actually given.  NS will mistakenly show those errant pump events...but Loop will have the correct insulin delivery because it uses actual reservoir volume reads vs. just pump events.  See here for more info https://github.com/LoopKit/Loop/issues/414



 I'd recommend getting an Issue Report and attaching.  Even if you don't catch it right away, an Issue Report has some history still captured in it depending on how long it's been since you noticed the behavior you want more info on.  So...don't skip getting the Issue Report.

**Comment by sdawson2003** [comment]
The insulin was definitely there in Loop too.  Unfortunately it's been probably 2 weeks now since this happened.  But Loop had 8-9U on board (a lot for her breakfast), and we ended up having to give a lot of juice to prevent the low.

**Comment by Kdisimone** [comment]
@sdawson2003 have you seen this behavior since? Have you updated your Loop app in the meantime?
