### ISSUE TITLE
Unable to Loop

### ISSUE THREAD

**Issue by ElizabethZ85** [LoopKit/Loop#859]
I just hooked up to Loop for the first time this afternoon and the circle turns yellow.  It has said numerous error messages (latest one is “pump error, command refused”) and then eventually turns red.  When I change it to open loop, it turns green.  Does anyone have advice?

**Comment by Kdisimone** [comment]
Command refused is a limited set of causes;
1. Temp basal type (in pump menu, under Basal section) is set to percentage instead of units per hour
2. Pump suspended
3. Pump has an extended bolus active
4. Pump has a prime screen on pump that hasn’t been finished after a rewind. 
5. Incompatible pump (like a 723 with 2.5 firmware)

**Comment by ElizabethZ85** [comment]
Thank you! I adjusted the percent to units and that seemed to have resolved the issue! I appreciate your prompt response, thanks again.


Sent from Yahoo Mail for iPhone


On Sunday, January 6, 2019, 20:10, katie disimone <notifications@github.com> wrote:


Command refused is a limited set of causes;
   
   - Temp basal type (in pump menu, under Basal section) is set to percentage instead of units per hour
   - Pump suspended
   - Pump has an extended bolus active
   - Pump has a prime screen on pump that hasn’t been finished after a rewind.
   - Incompatible pump (like a 723 with 2.5 firmware)

**Comment by Kdisimone** [comment]
Great!  Glad to hear.
