### ISSUE TITLE
Blank Bolus Recommendation or No Bolus Recommendation

### ISSUE THREAD

**Issue by JKeller86** [LoopKit/Loop#897]
**Bug Details**
Enter carbs and a blank bolus screen will pop up, or no bolus screen will pop up at all when it should be recommending one. BS is not low, and is not projected to trend below the suspend threshold... The carbs show up however, the algorithm seems to just ignore they exist. After a few minutes (literally, 5 - 10 minutes) I can press the bolus button and get a suggested bolus (which seems to be much smaller than it should have been originally, probably because the basals have ramped up at that point).

**To Reproduce**
N/A - intermittent behavior, unable to reproduce on demand.  

**Expected behavior**
A bolus recommendation should be made

**Screenshots**
Video Screen Capture Attachment Here: https://youtu.be/4JPf_4ZgS3o 

**Phone**
 - Hardware: iPhone XS Max
 - OS Version: iOS 12.1.4 (16D57)

**Loop Version**
 - Version Number: 1.9.4 & 1.9.5DEV
 - Repo: LoopKit/Loop

**CGM**
 - Device: Dexcom G6
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: Medtronic
 - Model: 523
 - Firmware version:  2.3A

**Comment by Kdisimone** [comment]
This behavior is because Loop is not running at the time when you have entered the carbs, therefore there is no prediction calculated with which to offer a bolus recommendation. Often the delay in Loop running is due to a backlog of NS uploading. try deleting your NS service from Loop settings and see if that helps speed/clean up your Loop operations. If it does, then work on fixing your NS site so that it is operating properly through mlab cleanup. Instructions are in Loopdocs' Nightscout section.
