### ISSUE TITLE
Problem with insulin delivery accounting in Open Loop and/or Neutral temps

### ISSUE THREAD

**Issue by Kdisimone** [LoopKit/Loop#904]
**Describe the bug**
Last night, while running on open loop for many hours, I noticed that IOB and main screen displays for insulin were incorrect periodically.

Additionally, there appear to be other reports surfacing in FB and messages from others that are likely seeing the same that I was able to capture last night (data attached below).

**Attach an Issue Report**

Two sets of info: 1st while Loop was in error, 2nd next loop corrected first.

**Set of First Info: While IOB and main screen were incorrect**

Loop Report 1 was captured when the Loop main screen and IOB were errantly showing a high temp basal and much higher IOB (7+ units) than actually present (3+ units). (Screenshots below)

[Loop Issue Report 1.pdf](https://github.com/LoopKit/Loop/files/2963568/Loop.1.pdf)

**Set of Second Info: While IOB and main screen corrected itself on the next loop**

[Loop Issue Report 2.pdf](https://github.com/LoopKit/Loop/files/2963570/Loop.2.pdf)

**To Reproduce**
1. Run Loop in open loop mode for awhile
2. Watch loop display for awhile, seems to reproduce itself within 30 minutes or less I expect. IOB will jump and insulin delivery graph will display a high temp basal for one loop run...then correct itself on next loop run. 

**Expected behavior**
Neutral temps or open loop should produce insulin delivery graph of 0 change and IOB should not increase.

**Screenshots**

First part (associated with Loop Report 1)

![IMG_6900](https://user-images.githubusercontent.com/12402160/54310302-50d09e80-458f-11e9-8123-643c0502255d.PNG)
![IMG_2365](https://user-images.githubusercontent.com/12402160/54310373-78c00200-458f-11e9-94a5-05d19cc642bf.PNG)

Second part (associated with Loop Report 2)

![IMG_6901](https://user-images.githubusercontent.com/12402160/54310472-ae64eb00-458f-11e9-924e-f72229bae224.PNG)
![IMG_2366](https://user-images.githubusercontent.com/12402160/54310479-b1f87200-458f-11e9-94bc-6852eacfa4bc.PNG)

**Phone**
 - Hardware: iphone 7
 - OS Version: ios 12.1.4

**Loop Version**
 - Version Number: 1.9.5-dev-holly
 - Repo: katie

**CGM**
 - Device: G6
 - Manager app: dexcom app

**Pump**
 - Manufacturer: Medtronic
 - Model: 723
 - Firmware version: 2.4 1.1 0B 0B

**Additional context**
@ps2 remember that other report I had mentioned in Slack convo previously? What she was seeing is very much the same as what I've captured here. Open loop mode has odd displays and IOB that are transiently (and incorrectly) showing a high temp basal was set. There's also a report of someone seeing same behavior in a FB post right now, but since FB is glitching I'm having trouble getting a link to it in here. I'll grab it when available.

**Comment by Kdisimone** [comment]
Another example....been open looping for over 12 hours and only added insulin in that time is from the bolus showing on screen (8 units) yet Loop is reporting over 15.5 units on board. 

![IMG_78F40A101C76-1](https://user-images.githubusercontent.com/12402160/54310959-dbfe6400-4590-11e9-881b-aa4f773c1f91.jpeg)

**Comment by Kdisimone** [comment]
and then fixes itself next Loop run.  


![IMG_D285614BC95D-1](https://user-images.githubusercontent.com/12402160/54311243-6a72e580-4591-11e9-8e49-04002e88f476.jpeg)

**Comment by Kdisimone** [comment]
Just fixed the original post with correct Loop Issue Reports (sorry, original post had wrong ones...all good now)

**Comment by elnjensen** [comment]
For what it's worth, I don't think this is only an open-Loop problem.  I see it periodically with closed Loop.  For me it's always after a bolus (which seems consistent with above examples), where it temporarily roughly doubles the bolus IOB.   It seems like it is double-counting the bolus temporarily - wonder if it could be registering both the reservoir change and the bolus entry in history for a short period of time.

**Comment by elnjensen** [comment]
Coincidentally, I saw this happen shortly after posting the comment above.  Screenshots below are only seconds apart - Loop completed and erased the problem just as I was finishing the first screenshot so I didn't have time to grab an issue report in the high-IOB state. Note that the difference in IOB (2.83 units) is very close to my most recent bolus, 2.8 units at 9:27 PM.  You can see in the first screenshot that it is rendered there as both a high temp basal and a bolus, and then the spurious temp basal spike goes away. I'm attaching an issue report after the second screenshot, but I'll keep watching and see if I can capture both before and after issue reports. 

![IMG_3206](https://user-images.githubusercontent.com/2545845/55767918-ca519480-5a48-11e9-8805-b0b28c96b5dc.PNG)

![IMG_3207](https://user-images.githubusercontent.com/2545845/55767924-ce7db200-5a48-11e9-9404-ab9cd54c9a50.PNG)

[Loop Report 2019-04-08 215100-0400.md.txt](https://github.com/LoopKit/Loop/files/3056854/Loop.Report.2019-04-08.215100-0400.md.txt)

**Comment by ps2** [comment]
The double bolus counting issue is known and expected behavior, due to the transition time when have read pump history, and don't see a bolus, but are tracking one temporarily, and are also seeing reservoir increases. It's not easily fixable w/o introducing the possibility of undercounting insulin, which is much worse than overcounting for a small period: https://github.com/LoopKit/LoopKit/pull/254/files

**Comment by elnjensen** [comment]
I've seen that in the past with recent boluses, and understand what you're saying, but this behavior seems different to me, since it can happen much longer after a bolus than I would expect based on simply not yet seeing the bolus in recent pump history.  If you look at Katie's examples above, the first case is a solid two hours after the bolus, and the second is about an hour.   In my case it was 20 minutes.  I'll keep an eye on it and see if I can catch another case with a full set of issue reports to document this better, but still wondering if there's something going on beyond the expected behavior.

**Comment by Kdisimone** [comment]
@ps2 we still are getting a fair amount of these reports in Looped group. People are quite confused by this display issue.

**Comment by ps2** [comment]
@Kdisimone Are you seeing them for omnipod or medtronic, or both? They are likely separate issues; medtronic is going to be expected to some extent (though there may be improvements we can make if we capture good data about the problem).  Omnipod I think we should be able to eliminate the issue, but again, we need to capture good info.  Issue reports for both would be good.  Maybe it's time to split this up into two tickets, and capture fresh reports. Since this ticket has been opened, there have been a good number of changes to DoseStore.

**Comment by ps2** [comment]
I'd appreciate any help in triaging this: creating new tickets for the separate issues, and directing people to attach issue reports to the appropriate tickets.

**Comment by marydaisy** [comment]
Hi, I've never posted in GitHub before so please lmk if I should be doing anything differently. I've been using Loop for 3.5 years and it's been a life saver. But for about the last year I have had major trust issues. The Loop display is frequently inaccurate, and the issue has occurred despite a new phone and through multiple versions of Loop (I use a Minimed 722).  I'm currently using Loop v2.1.0. The display will predict a very negative number showing a lot of IOB. When this first occurred, I ate a ton of carbs and ended up high, and noted a few minutes after eating the display corrected itself (without me entering any of the carb grams). But now I know it does this, so every time I see higher than expected IOB I constantly monitor the screen to see if it's a glitch or real. And intervene accordingly. It usually resolves within about 10 minutes, but it's very time-consuming to closely monitor and my distrust makes me fear one day it will be real IOB, and I won't eat enough in time because I assume the display is wrong. I have some screen shots if that would help? 

The other night I caught Loop delivering a 3 unit bolus I really don't recall initiating, which furthers my distrust. I have some screen shots of this and I sent myself an "issue report". Please let me know what you need. I'm unable to read the report to see why it initiated a bolus, which might help me determine if it was a user error vs a very scary glitch.  I'm afraid to where Loop right now and have borrowed a Tandem Control IQ but strongly prefer the Loop algorithm and features so would really appreciate being able to help on this issue in any way possible. Thank you all so very much!

**Comment by marydaisy** [comment]
![image](https://user-images.githubusercontent.com/9502542/79814362-ea41b680-8332-11ea-8841-6973a0ec5018.png)

**Comment by marydaisy** [comment]
![IMG_5798](https://user-images.githubusercontent.com/9502542/79815228-f4fd4b00-8334-11ea-9c4e-0adb1c48cb59.png)
![IMG_5797](https://user-images.githubusercontent.com/9502542/79815232-faf32c00-8334-11ea-9c98-8c87b72f67ae.png)

**Comment by marydaisy** [comment]
![IMG_6497](https://user-images.githubusercontent.com/9502542/79815331-57eee200-8335-11ea-8ba6-234aa661add8.png)
![IMG_6496](https://user-images.githubusercontent.com/9502542/79815340-5c1aff80-8335-11ea-92e0-0798a556d262.png)

These were taken April 9 at 8:22pm & 8:28pm

**Comment by loyalchallenger** [comment]
> @Kdisimone Are you seeing them for omnipod or medtronic, or both? They are likely separate issues; medtronic is going to be expected to some extent (though there may be improvements we can make if we capture good data about the problem). Omnipod I think we should be able to eliminate the issue, but again, we need to capture good info. Issue reports for both would be good. Maybe it's time to split this up into two tickets, and capture fresh reports. Since this ticket has been opened, there have been a good number of changes to DoseStore.

![982F1C09-CBD4-4341-B250-740E9E04F3DE](https://user-images.githubusercontent.com/50498256/79815355-65a46780-8335-11ea-8b78-93822ea91429.png)

**Comment by marydaisy** [comment]
So I opened a new issue for the 3 unit bolus. And all of the issues I'm reporting here have been Minimed 722. I have another screen shot from Aug last year but won't post unless helpful. I'll do an "issue report" next time I get the incorrect IOB display.

**Comment by marydaisy** [comment]
I'm updating Loop now and will post again if it occurs, with an "issue report" and screen shots. LMK if anything else would be helpful thank you!

**Comment by tohvanah** [comment]
We are observing similar issues on our new Loop setup.

**Setup:** iPhone SE, iOS 13.7, Loop 2.2.4 (LoopWorkspace master), OmniPod, Dexcom G6

**Loop Report 25 minutes *before* observing the issue.**

[Loop Report 2021-03-01 07:09:02-05:00.txt](https://github.com/LoopKit/Loop/files/6069250/Loop.Report.2021-03-01.07.09.02-05.00.txt)
*I don't even remember why I created *this* report, but it seems useful: it reflects the correct IOB.

**Incident #1**

<img width="503" alt="Napkin 30 03-02-21, 9 14 18 AM" src="https://user-images.githubusercontent.com/1719586/109661152-abc27e00-7b37-11eb-9815-f2c8f605957e.png">
[Loop Report 2021-03-01 07:44:27-05:00.txt](https://github.com/LoopKit/Loop/files/6069257/Loop.Report.2021-03-01.07.44.27-05.00.txt)


**Incident #2**

<img width="721" alt="Napkin 30 03-02-21, 9 20 44 AM" src="https://user-images.githubusercontent.com/1719586/109661991-913cd480-7b38-11eb-99ea-48546f2009c8.png">
[Loop Report 2021-03-01 17:04:34-05:00.txt](https://github.com/LoopKit/Loop/files/6069260/Loop.Report.2021-03-01.17.04.34-05.00.txt)
