### ISSUE TITLE
Difficulty for VoiceOver users navigating basal picker

### ISSUE THREAD

**Issue by geoffstacey** [LoopKit/Loop#930]
**Describe the bug**
VO treats the basal picker on "Basal Rates" page as one cell making it very difficult if not impossible for blind users to navigate.  

**Attach an Issue Report**
[Loop Report 2019-04-26 09:15:42-04:00.pdf](https://github.com/LoopKit/Loop/files/3121598/Loop.Report.2019-04-26.09.15.42-04.00.pdf)

**To Reproduce**
1. turn on voiceover
2. Click on settings
3. right swipe 13 times until VO reads basal rates,  Single finger double tap, right swipe 4 times until VO reads "12 am ...", single finger double tap

**Expected behavior**
VO curser should highlight each input cell ie hour, min, am/pm, basal rate.  When VO curser is on hour it would read hour and the hour selected swiping up or down would adjust the value...right swipe would move to next field etc.  An example would be the apple clock app
**Screenshots**
![IMG_0179](https://user-images.githubusercontent.com/33763691/56813499-0b98c100-680b-11e9-9cc3-90920bc4e643.jpeg)
![IMG_0180](https://user-images.githubusercontent.com/33763691/56813596-47cc2180-680b-11e9-8ba5-c5c1b6597bd5.jpeg)
![IMG_0181](https://user-images.githubusercontent.com/33763691/56813601-4d296c00-680b-11e9-9b78-74d4c77e712a.jpeg)
![IMG_0182](https://user-images.githubusercontent.com/33763691/56813611-54507a00-680b-11e9-9aa2-a8789f42bacb.jpeg)

**Phone**
 - Hardware: iPhone XR
 - OS Version: iOS 12.2

**Loop Version**
 - Version Number: 1.10.1DEV
 - Repo: Omnipod test branch

**CGM**
 - Device: Dexcom G5
 - Manager app: Dexcom App

**Pump**
 - Manufacturer: OmniPod
 - Model: 
 - Firmware version: 

**Additional context**

**Comment by vpdn** [comment]
I can reproduce the problem and could have a look. Since I only started looking into the project, I'm not sure what the state is regarding accessibility / VO support and whether it makes sense to focus on this screen? If there's some VO user here that could point to the most pressing issues, I'd be very happy to have a look into other issues as well.

Regarding this issue: 
- Currently, tapping "Add" doesn't report back what is being added. I think it would make sense to post a UIAccessibilityLayoutChangedNotification with sth like "three am thirty minutes [pause] zero point two units per hour"
- Instead of "zero, zero slash hr" VO should probably say sth like "12am zero minutes [pause] zero units per hour"
- An entry can be collapse or expanded. From an A11y perspective, it would make sense to indicate that an entry can be expanded (as an additional accessibility hint)
- When expanded, VO should move from overview to time to units? (currently not editable at all)
