### ISSUE TITLE
feature request: configurable glucose graph eventually field

### ISSUE THREAD

**Issue by naromero77** [LoopKit/Loop#933]
Hi,

This is a feature request. By default, the glucose chart displays an extrapolation of the eventual blood glucose. As a user, it would be much more useful to have display the blood glucose at a user specified time in the future. For example 30 minutes, 1 hr, 2 hr, etc., into the future. There reason are as follows:
1. I have not found the extrapolation to be very accurate past a couple of hours anyways
2. Stuff happens, and blood glucose 4+ hrs away is not that useful to the caretaker of a T1

**Comment by elnjensen** [comment]
The main reason that it is shown that far out is not necessarily that that prediction is expected to be accurate (often you hope it isn't!), but rather that that shows what Loop is using to make its dosing decisions.  For example, if your eventual blood glucose number is above your target range (and you aren't otherwise predicted to go below target in the meantime), it will give you insulin to return you to target.  Seeing what that forecast line looks like, and what the currently-predicted "eventual" number is, is essential to understanding how Loop operates.
